In [1]:
import pybaseball as pyb
from pybaseball import statcast, pitching_stats, playerid_lookup, statcast_pitcher, statcast_pitcher_pitch_arsenal, pitching_stats_bref, pitching_stats_range
import numpy as np
import math
import pandas as pd
import glob
import os
import re
import unicodedata
from datetime import datetime
from itertools import groupby
from operator import itemgetter

C:\Users\johns\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
all_2008_stats_df = pd.read_csv('all_2008_stats_df.csv', index_col=0)

In [3]:
all_2008_stats_df.drop(columns=['batter', 'events', 'description', 'zone',
                                'des', 'game_type', 'stand', 'home_team',
                                'away_team', 'type', 'hit_location', 'bb_type',
                                'balls', 'strikes', 'pfx_x', 'spin_dir', 
                                'pfx_z', 'plate_x', 'plate_z', 'on_3b',
                                'on_2b', 'on_1b', 'outs_when_up', 'inning',
                                'inning_topbot', 'hc_x', 'hc_y', 'fielder_2',
                                'umpire', 'sv_id', 'hit_distance_sc', 'sz_top',
                                 'sz_bot', 'launch_speed', 'launch_angle', 'game_pk',
                                'pitcher.1', 'fielder_2.1', 'fielder_3', 'fielder_4',
                                'fielder_5', 'fielder_6', 'fielder_7', 'fielder_8',
                                'fielder_9', 'estimated_ba_using_speedangle',
                                'estimated_woba_using_speedangle', 'babip_value',
                                'launch_speed_angle', 'woba_value', 'woba_denom', 'iso_value', 
                                'at_bat_number', 'pitch_number', 'home_score', 'away_score',
                                'bat_score', 'fld_score', 'post_home_score', 'post_bat_score',
                                'post_fld_score', 'post_away_score', 'if_fielding_alignment',
                                'of_fielding_alignment', 'delta_home_win_exp',
                                'delta_run_exp', 'spin_rate_deprecated', 'break_angle_deprecated',
                               'break_length_deprecated', 'tfs_deprecated', 'tfs_zulu_deprecated'], inplace=True)
all_2008_stats_df.head()

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,...,vz0,ax,ay,az,effective_speed,release_spin_rate,release_extension,release_pos_y,pitch_name,spin_axis
0,FF,2008-09-28,94.4,2.17,6.08,"Rhodes, Arthur",121125,L,2008,-8.707990,...,-6.509925,14.542,26.437,-13.292,NaN,NaN,NaN,54.5,4-Seam Fastball,NaN
1,FF,2008-09-28,93.0,2.21,6.03,"Rhodes, Arthur",121125,L,2008,-5.173211,...,-4.206386,11.045,23.637,-14.797,NaN,NaN,NaN,54.5,4-Seam Fastball,NaN
2,NaN,2008-09-26,NaN,NaN,NaN,"Rhodes, Arthur",121125,L,2008,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,2008-09-26,NaN,NaN,NaN,"Rhodes, Arthur",121125,L,2008,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,FF,2008-09-22,92.2,1.87,6.72,"Rhodes, Arthur",121125,L,2008,-8.500073,...,-6.349345,13.193,25.168,-14.613,NaN,NaN,NaN,54.5,4-Seam Fastball,NaN

In [4]:
all_2008_stats_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 459185 entries, 0 to 459184
Data columns (total 21 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   pitch_type         437522 non-null  object
 1   game_date          459185 non-null  object
 2   release_speed      437503 non-null  float64
 3   release_pos_x      437492 non-null  float64
 4   release_pos_z      437492 non-null  float64
 5   player_name        459185 non-null  object
 6   pitcher            459185 non-null  int64
 7   p_throws           459185 non-null  object
 8   game_year          459185 non-null  int64
 9   vx0                437492 non-null  float64
 10  vy0                437492 non-null  float64
 11  vz0                437492 non-null  float64
 12  ax                 437503 non-null  float64
 13  ay                 437503 non-null  float64
 14  az                 437503 non-null  float64
 15  effective_speed    0 non-null       float64
 16  release_spin_rate  0 non-null       float64
 17  release_extension  0 non-null       float64
 18  release_pos_y      437492 non-null  float64
 19  pitch_name         437522 non-null  object
 20  spin_axis          0 non-null       float64
dtypes: float64(14), int64(2), object(5)
memory usage: 77.1+ MB

In [5]:
all_2008_stats_df.drop(columns=['spin_axis', 'effective_speed',
                               'release_spin_rate', 'release_extension'], inplace=True)
all_2008_stats_df.head()

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,vy0,vz0,ax,ay,az,release_pos_y,pitch_name
0,FF,2008-09-28,94.4,2.17,6.08,"Rhodes, Arthur",121125,L,2008,-8.707990,-137.912339,-6.509925,14.542,26.437,-13.292,54.5,4-Seam Fastball
1,FF,2008-09-28,93.0,2.21,6.03,"Rhodes, Arthur",121125,L,2008,-5.173211,-136.112715,-4.206386,11.045,23.637,-14.797,54.5,4-Seam Fastball
2,NaN,2008-09-26,NaN,NaN,NaN,"Rhodes, Arthur",121125,L,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,2008-09-26,NaN,NaN,NaN,"Rhodes, Arthur",121125,L,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,FF,2008-09-22,92.2,1.87,6.72,"Rhodes, Arthur",121125,L,2008,-8.500073,-134.717333,-6.349345,13.193,25.168,-14.613,54.5,4-Seam Fastball

In [6]:
all_2008_stats_df = all_2008_stats_df.dropna(axis=0)

In [7]:
all_2008_stats_df.reset_index(inplace=True)

In [8]:
all_2008_stats_df.drop('index', axis=1)

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,vy0,vz0,ax,ay,az,release_pos_y,pitch_name
0,FF,2008-09-28,94.4,2.17,6.08,"Rhodes, Arthur",121125,L,2008,-8.707990,-137.912339,-6.509925,14.542,26.437,-13.292,54.5,4-Seam Fastball
1,FF,2008-09-28,93.0,2.21,6.03,"Rhodes, Arthur",121125,L,2008,-5.173211,-136.112715,-4.206386,11.045,23.637,-14.797,54.5,4-Seam Fastball
2,FF,2008-09-22,92.2,1.87,6.72,"Rhodes, Arthur",121125,L,2008,-8.500073,-134.717333,-6.349345,13.193,25.168,-14.613,54.5,4-Seam Fastball
3,SL,2008-09-22,83.5,1.67,6.77,"Rhodes, Arthur",121125,L,2008,-6.031356,-122.057007,-2.945559,-3.884,20.604,-31.864,54.5,Slider
4,FF,2008-09-22,92.7,1.94,6.68,"Rhodes, Arthur",121125,L,2008,-9.150760,-135.540457,-7.791941,16.832,28.019,-16.931,54.5,4-Seam Fastball
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
437487,SI,2008-04-05,91.7,-1.14,6.77,"Wainwright, Adam",425794,R,2008,7.410180,-134.463290,-7.755931,-15.885,38.429,-11.659,54.5,Sinker
437488,SI,2008-04-05,91.2,-1.23,6.71,"Wainwright, Adam",425794,R,2008,3.898923,-133.801230,-6.896768,-12.754,36.411,-12.260,54.5,Sinker
437489,SI,2008-04-05,91.5,-0.97,6.65,"Wainwright, Adam",425794,R,2008,4.816129,-133.904804,-10.691690,-12.569,32.474,-14.471,54.5,Sinker
437490,CU,2008-04-05,72.3,-1.15,6.93,"Wainwright, Adam",425794,R,2008,-0.206400,-106.350093,0.634643,7.885,26.262,-39.158,54.5,Curveball
437491,SI,2008-04-05,90.0,-1.01,6.71,"Wainwright, Adam",425794,R,2008,4.157547,-131.951764,-6.921964,-11.635,33.916,-15.532,54.5,Sinker

In [9]:
# Group by 'game_date' and 'pitcher' to calculate the total pitches
total_pitches = all_2008_stats_df.groupby(['game_date', 'pitcher']).size().reset_index(name='total_pitches')

# Group by 'game_date', 'pitcher', and 'pitch_type' to calculate the sum total of each pitch_type
total_pitches_by_type = all_2008_stats_df.groupby(['game_date', 'pitcher', 'pitch_type']).size().reset_index(name='count_by_pitch_type')

# Calculate averages of the specified metrics for each pitch type, grouped by game_date and pitcher
avg_metrics = all_2008_stats_df.groupby(['game_date', 'pitcher', 'pitch_type']).agg({
    'release_speed': 'mean',
    'release_pos_x': 'mean',
    'release_pos_z': 'mean',
    'vx0': 'mean',
    'vy0': 'mean',
    'vz0': 'mean',
    'ax': 'mean',
    'ay': 'mean',
    'az': 'mean',
    'release_pos_y': 'mean',
}).reset_index()

# Merging total pitches and total pitches by type back if needed
# This step depends on how you want to structure your final DataFrame. You can merge these summary DataFrames
# based on 'game_date' and 'pitcher' columns to get a comprehensive summary DataFrame.

# Example merge (you can adjust or expand based on what you exactly need):
grouped_2008_df = total_pitches.merge(total_pitches_by_type, on=['game_date', 'pitcher'], how='left')
grouped_2008_df = grouped_2008_df.merge(avg_metrics, on=['game_date', 'pitcher', 'pitch_type'], how='left')

# Note: This example assumes you want to merge all these statistics back together. You might adjust the merging
# strategy based on your analysis needs, including how you want to handle the multi-level grouping and aggregation.
grouped_2008_df

,game_date,pitcher,total_pitches,pitch_type,count_by_pitch_type,release_speed,release_pos_x,release_pos_z,vx0,vy0,vz0,ax,ay,az,release_pos_y
0,2008-03-28,112526,39,FF,10,93.610000,-1.094000,6.136000,4.088171,-137.324284,-4.636060,-9.542600,35.855500,-10.000600,54.5
1,2008-03-28,112526,39,SI,17,92.500000,-1.200000,5.975882,7.145081,-135.639909,-3.658293,-16.398000,33.460706,-15.712059,54.5
2,2008-03-28,112526,39,SL,12,84.333333,-1.324167,6.185000,3.248877,-123.762940,-2.673402,1.235917,28.714667,-25.267833,54.5
3,2008-03-28,118120,1,SI,1,86.600000,-3.640000,5.470000,11.619602,-127.018486,-2.052596,-13.153000,39.843000,-21.961000,54.5
4,2008-03-28,121556,8,FF,4,90.050000,0.390000,5.875000,-3.588131,-132.336308,-4.748622,8.256500,37.847000,-12.092000,54.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28419,2008-09-30,448147,89,CH,3,84.500000,-1.880000,6.210000,5.939837,-123.876961,-4.448008,-8.085667,28.021667,-16.695667,54.5
28420,2008-09-30,448147,89,CU,4,79.400000,-1.940000,6.652500,3.044706,-116.456223,-0.357078,3.595000,23.050000,-31.974500,54.5
28421,2008-09-30,448147,89,FC,21,89.338095,-1.937619,6.466190,6.012968,-130.845059,-5.931220,2.147714,29.167286,-18.180381,54.5
28422,2008-09-30,448147,89,IN,4,70.450000,-1.627500,6.847500,12.260053,-102.571315,4.133443,-5.203750,17.883250,-21.419750,54.5
28423,2008-09-30,448147,89,SI,57,93.314035,-2.057018,6.360175,7.062591,-136.663128,-6.380256,-16.457825,33.602649,-14.203825,54.5

In [11]:
grouped_2008_df['game_date'] = pd.to_datetime(grouped_2008_df['game_date'])
grouped_2008_df['season'] = grouped_2008_df['game_date'].dt.year

# Step 1: Season Total Pitches
season_total_pitches = grouped_2008_df.groupby(['pitcher', 'season'])['total_pitches'].sum().reset_index(name='season_total_pitches')

# Step 2: Season Total by Pitch Type
season_total_by_pitch_type = grouped_2008_df.groupby(['pitcher', 'season', 'pitch_type'])['count_by_pitch_type'].sum().reset_index(name='season_total_count_by_pitch_type')

# Weighted Averages Calculation Setup
weighted_avg_columns = ['release_speed', 'release_pos_x', 'release_pos_z', 'vx0', 'vy0', 'vz0', 'ax', 'ay', 'az', 'release_pos_y']
for col in weighted_avg_columns:
    grouped_2008_df[f'{col}_product'] = grouped_2008_df[col] * grouped_2008_df['count_by_pitch_type']

weighted_avg_aggregations = {f'{col}_product': 'sum' for col in weighted_avg_columns}
weighted_avg_aggregations['count_by_pitch_type'] = 'sum'

# Aggregate for weighted averages
weighted_avg_df = grouped_2008_df.groupby(['pitcher', 'season', 'pitch_type']).agg(weighted_avg_aggregations).reset_index()

# Calculate weighted averages
for col in weighted_avg_columns:
    weighted_avg_df[f'{col}_weighted_avg'] = weighted_avg_df[f'{col}_product'] / weighted_avg_df['count_by_pitch_type']

# Cleanup
weighted_avg_df.drop(columns=[f'{col}_product' for col in weighted_avg_columns], inplace=True)

# Merge season totals and weighted averages
final_2008_df = pd.merge(season_total_pitches, season_total_by_pitch_type, on=['pitcher', 'season'])
final_2008_df = pd.merge(final_2008_df, weighted_avg_df, on=['pitcher', 'season', 'pitch_type'])

final_2008_df.head()

,pitcher,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,110683,2008,10287,CH,183,183,82.641530,-2.031639,6.010710,5.030589,-121.086910,-3.236765,-7.208295,25.458301,-22.841470,54.5
1,110683,2008,10287,CU,89,89,75.425843,-2.171910,6.275506,3.901072,-110.627789,-1.246458,4.697427,21.880798,-30.597461,54.5
2,110683,2008,10287,FC,6,6,90.566667,-2.036667,6.021667,6.288426,-132.625534,-3.528409,-0.497500,27.095833,-16.729000,54.5
3,110683,2008,10287,FF,286,286,92.263986,-1.918287,5.976259,5.195557,-135.256725,-4.764332,-4.447133,32.437836,-14.849983,54.5
4,110683,2008,10287,IN,2,2,50.600000,-1.390000,7.635000,-0.433396,-73.714833,7.335296,1.334000,10.275000,-27.784500,54.5

In [12]:
final_2008_df.to_csv('final_2008_df.csv')