In [1]:
import pybaseball as pyb
from pybaseball import statcast, pitching_stats, playerid_lookup, statcast_pitcher, statcast_pitcher_pitch_arsenal, pitching_stats_bref, pitching_stats_range
import numpy as np
import math
import pandas as pd
import glob
import os
import re
import unicodedata
from datetime import datetime
from itertools import groupby
from operator import itemgetter

C:\Users\johns\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
all_2009_stats_df = pd.read_csv('all_2009_stats_df.csv', index_col=0)

In [3]:
all_2009_stats_df.drop(columns=['batter', 'events', 'description', 'zone',
                                'des', 'game_type', 'stand', 'home_team',
                                'away_team', 'type', 'hit_location', 'bb_type',
                                'balls', 'strikes', 'pfx_x', 'spin_dir', 
                                'pfx_z', 'plate_x', 'plate_z', 'on_3b',
                                'on_2b', 'on_1b', 'outs_when_up', 'inning',
                                'inning_topbot', 'hc_x', 'hc_y', 'fielder_2',
                                'umpire', 'sv_id', 'hit_distance_sc', 'sz_top',
                                 'sz_bot', 'launch_speed', 'launch_angle', 'game_pk',
                                'pitcher.1', 'fielder_2.1', 'fielder_3', 'fielder_4',
                                'fielder_5', 'fielder_6', 'fielder_7', 'fielder_8',
                                'fielder_9', 'estimated_ba_using_speedangle',
                                'estimated_woba_using_speedangle', 'babip_value',
                                'launch_speed_angle', 'woba_value', 'woba_denom', 'iso_value', 
                                'at_bat_number', 'pitch_number', 'home_score', 'away_score',
                                'bat_score', 'fld_score', 'post_home_score', 'post_bat_score',
                                'post_fld_score', 'post_away_score', 'if_fielding_alignment',
                                'of_fielding_alignment', 'delta_home_win_exp',
                                'delta_run_exp', 'spin_rate_deprecated', 'break_angle_deprecated',
                               'break_length_deprecated', 'tfs_deprecated', 'tfs_zulu_deprecated'], inplace=True)
all_2009_stats_df.head()

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,...,vz0,ax,ay,az,effective_speed,release_spin_rate,release_extension,release_pos_y,pitch_name,spin_axis
0,SL,2009-09-22,80.1,1.67,6.67,"Rhodes, Arthur",121125,L,2009,-4.389443,...,-5.082563,-3.957,19.039,-37.673,NaN,NaN,NaN,54.5,Slider,NaN
1,SL,2009-09-22,80.7,1.57,6.62,"Rhodes, Arthur",121125,L,2009,-4.559784,...,-4.151201,-4.269,21.402,-35.174,NaN,NaN,NaN,54.5,Slider,NaN
2,FF,2009-09-22,90.9,1.71,6.57,"Rhodes, Arthur",121125,L,2009,-7.138286,...,-7.508049,11.578,26.497,-14.777,NaN,NaN,NaN,54.5,4-Seam Fastball,NaN
3,SL,2009-09-22,80.7,1.73,6.67,"Rhodes, Arthur",121125,L,2009,-2.243166,...,-1.890828,-4.287,20.830,-32.739,NaN,NaN,NaN,54.5,Slider,NaN
4,SL,2009-09-22,82.5,1.60,6.67,"Rhodes, Arthur",121125,L,2009,-4.248895,...,-2.382552,-5.676,21.849,-31.268,NaN,NaN,NaN,54.5,Slider,NaN

In [10]:
all_2009_stats_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 443084 entries, 0 to 443083
Data columns (total 18 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   index          443084 non-null  int64
 1   pitch_type     443084 non-null  object
 2   game_date      443084 non-null  object
 3   release_speed  443084 non-null  float64
 4   release_pos_x  443084 non-null  float64
 5   release_pos_z  443084 non-null  float64
 6   player_name    443084 non-null  object
 7   pitcher        443084 non-null  int64
 8   p_throws       443084 non-null  object
 9   game_year      443084 non-null  int64
 10  vx0            443084 non-null  float64
 11  vy0            443084 non-null  float64
 12  vz0            443084 non-null  float64
 13  ax             443084 non-null  float64
 14  ay             443084 non-null  float64
 15  az             443084 non-null  float64
 16  release_pos_y  443084 non-null  float64
 17  pitch_name     443084 non-null  object
dtypes: float64(10), int64(3), object(5)
memory usage: 60.8+ MB

In [5]:
all_2009_stats_df.drop(columns=['spin_axis', 'effective_speed',
                               'release_spin_rate', 'release_extension'], inplace=True)
all_2009_stats_df.head()

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,vy0,vz0,ax,ay,az,release_pos_y,pitch_name
0,SL,2009-09-22,80.1,1.67,6.67,"Rhodes, Arthur",121125,L,2009,-4.389443,-117.087026,-5.082563,-3.957,19.039,-37.673,54.5,Slider
1,SL,2009-09-22,80.7,1.57,6.62,"Rhodes, Arthur",121125,L,2009,-4.559784,-118.109257,-4.151201,-4.269,21.402,-35.174,54.5,Slider
2,FF,2009-09-22,90.9,1.71,6.57,"Rhodes, Arthur",121125,L,2009,-7.138286,-132.926061,-7.508049,11.578,26.497,-14.777,54.5,4-Seam Fastball
3,SL,2009-09-22,80.7,1.73,6.67,"Rhodes, Arthur",121125,L,2009,-2.243166,-118.148051,-1.890828,-4.287,20.830,-32.739,54.5,Slider
4,SL,2009-09-22,82.5,1.60,6.67,"Rhodes, Arthur",121125,L,2009,-4.248895,-120.829471,-2.382552,-5.676,21.849,-31.268,54.5,Slider

In [7]:
all_2009_stats_df = all_2009_stats_df.dropna(axis=0)

In [8]:
all_2009_stats_df.reset_index(inplace=True)

In [9]:
all_2009_stats_df.drop('index', axis=1)

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,vy0,vz0,ax,ay,az,release_pos_y,pitch_name
0,SL,2009-09-22,80.1,1.67,6.67,"Rhodes, Arthur",121125,L,2009,-4.389443,-117.087026,-5.082563,-3.957,19.039,-37.673,54.5,Slider
1,SL,2009-09-22,80.7,1.57,6.62,"Rhodes, Arthur",121125,L,2009,-4.559784,-118.109257,-4.151201,-4.269,21.402,-35.174,54.5,Slider
2,FF,2009-09-22,90.9,1.71,6.57,"Rhodes, Arthur",121125,L,2009,-7.138286,-132.926061,-7.508049,11.578,26.497,-14.777,54.5,4-Seam Fastball
3,SL,2009-09-22,80.7,1.73,6.67,"Rhodes, Arthur",121125,L,2009,-2.243166,-118.148051,-1.890828,-4.287,20.830,-32.739,54.5,Slider
4,SL,2009-09-22,82.5,1.60,6.67,"Rhodes, Arthur",121125,L,2009,-4.248895,-120.829471,-2.382552,-5.676,21.849,-31.268,54.5,Slider
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
443079,SI,2009-04-06,94.1,-0.92,6.72,"Wainwright, Adam",425794,R,2009,0.327870,-137.873328,-7.892886,-13.299,34.915,-10.835,54.5,Sinker
443080,FC,2009-04-06,86.2,-1.13,6.61,"Wainwright, Adam",425794,R,2009,3.660575,-126.088355,-8.242482,3.947,27.835,-29.235,54.5,Cutter
443081,SI,2009-04-06,91.6,-1.13,6.68,"Wainwright, Adam",425794,R,2009,4.595713,-134.329080,-5.774637,-12.951,34.036,-15.586,54.5,Sinker
443082,SI,2009-04-06,94.0,-1.05,6.44,"Wainwright, Adam",425794,R,2009,5.847546,-137.487764,-8.413200,-16.420,32.830,-16.306,54.5,Sinker
443083,SI,2009-04-06,92.2,-1.31,6.41,"Wainwright, Adam",425794,R,2009,4.925305,-135.262242,-6.260075,-18.510,32.758,-18.798,54.5,Sinker

In [11]:
# Group by 'game_date' and 'pitcher' to calculate the total pitches
total_pitches = all_2009_stats_df.groupby(['game_date', 'pitcher']).size().reset_index(name='total_pitches')

# Group by 'game_date', 'pitcher', and 'pitch_type' to calculate the sum total of each pitch_type
total_pitches_by_type = all_2009_stats_df.groupby(['game_date', 'pitcher', 'pitch_type']).size().reset_index(name='count_by_pitch_type')

# Calculate averages of the specified metrics for each pitch type, grouped by game_date and pitcher
avg_metrics = all_2009_stats_df.groupby(['game_date', 'pitcher', 'pitch_type']).agg({
    'release_speed': 'mean',
    'release_pos_x': 'mean',
    'release_pos_z': 'mean',
    'vx0': 'mean',
    'vy0': 'mean',
    'vz0': 'mean',
    'ax': 'mean',
    'ay': 'mean',
    'az': 'mean',
    'release_pos_y': 'mean',
}).reset_index()

# Merging total pitches and total pitches by type back if needed
# This step depends on how you want to structure your final DataFrame. You can merge these summary DataFrames
# based on 'game_date' and 'pitcher' columns to get a comprehensive summary DataFrame.

# Example merge (you can adjust or expand based on what you exactly need):
grouped_2009_df = total_pitches.merge(total_pitches_by_type, on=['game_date', 'pitcher'], how='left')
grouped_2009_df = grouped_2009_df.merge(avg_metrics, on=['game_date', 'pitcher', 'pitch_type'], how='left')

# Note: This example assumes you want to merge all these statistics back together. You might adjust the merging
# strategy based on your analysis needs, including how you want to handle the multi-level grouping and aggregation.
grouped_2009_df

,game_date,pitcher,total_pitches,pitch_type,count_by_pitch_type,release_speed,release_pos_x,release_pos_z,vx0,vy0,vz0,ax,ay,az,release_pos_y
0,2009-04-05,113961,9,FF,6,90.050000,2.201667,6.741667,-8.485284,-131.516927,-9.666082,10.709167,28.296500,-11.721167,54.5
1,2009-04-05,113961,9,SL,3,81.866667,2.620000,6.576667,-7.452117,-119.644304,-4.436836,-4.361667,22.589000,-26.094333,54.5
2,2009-04-05,117955,97,FC,1,85.000000,-2.350000,6.370000,9.284933,-124.190979,-4.935491,-1.538000,24.912000,-25.779000,54.5
3,2009-04-05,117955,97,SI,59,89.418644,-2.445424,6.341017,9.345379,-130.922073,-4.287697,-19.156220,30.986729,-24.077678,54.5
4,2009-04-05,117955,97,SL,37,83.156757,-2.577838,6.246757,5.409004,-121.786644,-2.635946,1.751784,24.685108,-30.038378,54.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28445,2009-10-06,435261,23,SL,6,84.300000,-2.970000,6.281667,5.155707,-123.486762,-0.897622,1.893833,23.242000,-29.624167,54.5
28446,2009-10-06,519144,92,CH,7,81.771429,-2.531429,6.271429,9.012146,-119.538790,-2.434296,-13.452143,22.791714,-25.110714,54.5
28447,2009-10-06,519144,92,FF,38,93.139474,-2.389211,6.437368,9.119490,-136.204660,-5.239991,-11.874053,28.893737,-13.801026,54.5
28448,2009-10-06,519144,92,SI,40,91.167500,-2.699750,6.208250,9.627457,-133.374449,-3.939914,-19.468350,28.288000,-22.817825,54.5
28449,2009-10-06,519144,92,SL,7,83.185714,-2.500000,6.431429,10.282546,-121.370113,-5.054979,-0.330714,24.008571,-29.756714,54.5

In [12]:
grouped_2009_df['game_date'] = pd.to_datetime(grouped_2009_df['game_date'])
grouped_2009_df['season'] = grouped_2009_df['game_date'].dt.year

# Step 1: Season Total Pitches
season_total_pitches = grouped_2009_df.groupby(['pitcher', 'season'])['total_pitches'].sum().reset_index(name='season_total_pitches')

# Step 2: Season Total by Pitch Type
season_total_by_pitch_type = grouped_2009_df.groupby(['pitcher', 'season', 'pitch_type'])['count_by_pitch_type'].sum().reset_index(name='season_total_count_by_pitch_type')

# Weighted Averages Calculation Setup
weighted_avg_columns = ['release_speed', 'release_pos_x', 'release_pos_z', 'vx0', 'vy0', 'vz0', 'ax', 'ay', 'az', 'release_pos_y']
for col in weighted_avg_columns:
    grouped_2009_df[f'{col}_product'] = grouped_2009_df[col] * grouped_2009_df['count_by_pitch_type']

weighted_avg_aggregations = {f'{col}_product': 'sum' for col in weighted_avg_columns}
weighted_avg_aggregations['count_by_pitch_type'] = 'sum'

# Aggregate for weighted averages
weighted_avg_df = grouped_2009_df.groupby(['pitcher', 'season', 'pitch_type']).agg(weighted_avg_aggregations).reset_index()

# Calculate weighted averages
for col in weighted_avg_columns:
    weighted_avg_df[f'{col}_weighted_avg'] = weighted_avg_df[f'{col}_product'] / weighted_avg_df['count_by_pitch_type']

# Cleanup
weighted_avg_df.drop(columns=[f'{col}_product' for col in weighted_avg_columns], inplace=True)

# Merge season totals and weighted averages
final_2009_df = pd.merge(season_total_pitches, season_total_by_pitch_type, on=['pitcher', 'season'])
final_2009_df = pd.merge(final_2009_df, weighted_avg_df, on=['pitcher', 'season', 'pitch_type'])

final_2009_df.head()

,pitcher,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,110683,2009,4267,CH,41,41,85.012195,-2.218537,5.706829,5.855133,-124.551149,-1.272244,-7.955195,26.476366,-27.023293,54.5
1,110683,2009,4267,CU,22,22,78.181818,-2.452727,5.734091,4.520884,-114.570196,-0.254067,4.821545,20.927591,-30.535500,54.5
2,110683,2009,4267,FF,137,137,93.719708,-2.247007,5.639781,6.880657,-137.275166,-3.722603,-7.989927,31.474693,-15.681956,54.5
3,110683,2009,4267,IN,1,1,53.500000,-2.340000,7.130000,-6.899020,-78.119736,4.971030,1.072000,11.680000,-27.760000,54.5
4,110683,2009,4267,SI,652,652,93.240031,-2.178834,5.575031,7.831769,-136.577136,-3.124205,-16.850879,31.951578,-21.594371,54.5

In [13]:
final_2009_df.to_csv('final_2009_df.csv')