In [32]:
import pybaseball as pyb
from pybaseball import statcast, pitching_stats, playerid_lookup, statcast_pitcher, statcast_pitcher_pitch_arsenal, pitching_stats_bref, pitching_stats_range
import numpy as np
import math
import pandas as pd
import glob
import os
import re
import unicodedata
from datetime import datetime
from itertools import groupby
from operator import itemgetter
from sklearn.preprocessing import OneHotEncoder

First, load in DF from data_cleaning_notebook_1 'cleaning_filtered_df.csv'

Drop all info prior to 2008.

Then rename 'Year' to 'season'.

In [23]:
cleaning_filtered_df = pd.read_csv('~/Documents/Flatiron/Project_5_/data/cleaning_filtered_df.csv', index_col=0)
cleaning_filtered_df

,Name,Age,Year,Throws,IP,G,GS,CG,SHO,sDR,Career Start,Career End,Inactive Years
0,ed acosta,28,1972,1,89.0,46,2,0,0,1,1972,1972,[]
1,doyle alexander,21,1972,1,106.1,35,9,2,2,3,1972,1989,[]
2,lloyd allen,22,1972,1,85.1,42,6,0,0,5,1972,1975,[]
3,steve arlin,26,1972,1,250.0,38,37,12,3,22,1972,1974,[]
4,stan bahnsen,27,1972,1,252.1,43,41,5,1,32,1972,1981,"[1979, 1980]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16566,brandon woodruff,30,2023,1,67.0,11,11,1,1,0,2017,2023,[]
16567,kyle wright,27,2023,1,31.0,9,7,0,0,0,2019,2023,[]
16568,ryan yarbrough,31,2023,0,89.2,25,9,0,0,0,2018,2023,[]
16571,rob zastryzny,31,2023,0,20.2,21,1,0,0,0,2016,2023,"[2017, 2018, 2019, 2020, 2021, 2022]"
16572,angel zerpa,23,2023,0,42.2,15,3,0,0,1,2021,2023,[]

In [24]:
cleaning_filtered_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15060 entries, 0 to 16572
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            15060 non-null  object
 1   Age             15060 non-null  int64
 2   Year            15060 non-null  int64
 3   Throws          15060 non-null  int64
 4   IP              15060 non-null  float64
 5   G               15060 non-null  int64
 6   GS              15060 non-null  int64
 7   CG              15060 non-null  int64
 8   SHO             15060 non-null  int64
 9   sDR             15060 non-null  int64
 10  Career Start    15060 non-null  int64
 11  Career End      15060 non-null  int64
 12  Inactive Years  15060 non-null  object
dtypes: float64(1), int64(10), object(2)
memory usage: 1.6+ MB

In [25]:
cleaning_filtered_df = cleaning_filtered_df[cleaning_filtered_df['Year'] >= 2008]

In [26]:
cleaning_filtered_df

,Name,Age,Year,Throws,IP,G,GS,CG,SHO,sDR,Career Start,Career End,Inactive Years
10745,alfredo aceves,25,2008,1,30.0,6,4,0,0,0,2008,2013,"[2010, 2012]"
10746,nick adenhart,21,2008,1,12.0,3,3,0,0,0,2008,2009,[]
10747,matt albers,25,2008,1,49.0,28,3,0,0,2,2006,2016,"[2009, 2010, 2011, 2012, 2013, 2014, 2015]"
10748,alberto arias,24,2008,1,21.2,15,2,0,0,0,2008,2008,[]
10749,alberto arias,24,2008,1,8.0,3,2,0,0,0,2008,2008,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16566,brandon woodruff,30,2023,1,67.0,11,11,1,1,0,2017,2023,[]
16567,kyle wright,27,2023,1,31.0,9,7,0,0,0,2019,2023,[]
16568,ryan yarbrough,31,2023,0,89.2,25,9,0,0,0,2018,2023,[]
16571,rob zastryzny,31,2023,0,20.2,21,1,0,0,0,2016,2023,"[2017, 2018, 2019, 2020, 2021, 2022]"
16572,angel zerpa,23,2023,0,42.2,15,3,0,0,1,2021,2023,[]

In [27]:
cleaning_filtered_df = cleaning_filtered_df.rename(columns={'Year': 'season'})

Will merge cleaning_filtered_df with yearly DF later.

Now, load in data by year.

Start with 2008.

In [9]:
all_2008_stats_df = pd.read_csv('~/Documents/Flatiron/Project_5_/data/all_2008_stats_df.csv', index_col=0)

In [10]:
all_2008_stats_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 459185 entries, 0 to 459184
Data columns (total 92 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   pitch_type                       437522 non-null  object
 1   game_date                        459185 non-null  object
 2   release_speed                    437503 non-null  float64
 3   release_pos_x                    437492 non-null  float64
 4   release_pos_z                    437492 non-null  float64
 5   player_name                      459185 non-null  object
 6   batter                           459185 non-null  int64
 7   pitcher                          459185 non-null  int64
 8   events                           122796 non-null  object
 9   description                      459185 non-null  object
 10  spin_dir                         0 non-null       float64
 11  spin_rate_deprecated             0 non-null       float64
 12  break_angle_deprecated           0 non-null       float64
 13  break_length_deprecated          0 non-null       float64
 14  zone                             437503 non-null  float64
 15  des                              459184 non-null  object
 16  game_type                        459185 non-null  object
 17  stand                            459185 non-null  object
 18  p_throws                         459185 non-null  object
 19  home_team                        459185 non-null  object
 20  away_team                        459185 non-null  object
 21  type                             459185 non-null  object
 22  hit_location                     108130 non-null  float64
 23  bb_type                          90752 non-null   object
 24  balls                            459185 non-null  int64
 25  strikes                          459185 non-null  int64
 26  game_year                        459185 non-null  int64
 27  pfx_x                            437492 non-null  float64
 28  pfx_z                            437492 non-null  float64
 29  plate_x                          437503 non-null  float64
 30  plate_z                          437503 non-null  float64
 31  on_3b                            43982 non-null   float64
 32  on_2b                            87192 non-null   float64
 33  on_1b                            138014 non-null  float64
 34  outs_when_up                     459185 non-null  int64
 35  inning                           459185 non-null  int64
 36  inning_topbot                    459185 non-null  object
 37  hc_x                             82377 non-null   float64
 38  hc_y                             82377 non-null   float64
 39  tfs_deprecated                   0 non-null       float64
 40  tfs_zulu_deprecated              0 non-null       float64
 41  fielder_2                        459185 non-null  int64
 42  umpire                           0 non-null       float64
 43  sv_id                            437521 non-null  object
 44  vx0                              437492 non-null  float64
 45  vy0                              437492 non-null  float64
 46  vz0                              437492 non-null  float64
 47  ax                               437503 non-null  float64
 48  ay                               437503 non-null  float64
 49  az                               437503 non-null  float64
 50  sz_top                           437503 non-null  float64
 51  sz_bot                           437503 non-null  float64
 52  hit_distance_sc                  0 non-null       float64
 53  launch_speed                     0 non-null       float64
 54  launch_angle                     0 non-null       float64
 55  effective_speed                  0 non-null       float64
 56  release_spin_rate                0 non-null       float64
 57  release_extension                0 non-null       float64
 58  game_pk                          459185 non-null  int64
 59  pitcher.1                        459185 non-null  int64
 60  fielder_2.1                      459185 non-null  int64
 61  fielder_3                        459185 non-null  int64
 62  fielder_4                        459185 non-null  int64
 63  fielder_5                        459185 non-null  int64
 64  fielder_6                        459185 non-null  int64
 65  fielder_7                        459185 non-null  int64
 66  fielder_8                        459185 non-null  int64
 67  fielder_9                        459185 non-null  int64
 68  release_pos_y                    437492 non-null  float64
 69  estimated_ba_using_speedangle    0 non-null       float64
 70  estimated_woba_using_speedangle  0 non-null       float64
 71  woba_value                       122797 non-null  float64
 72  woba_denom                       0 non-null       float64
 73  babip_value                      122797 non-null  float64
 74  iso_value                        122797 non-null  float64
 75  launch_speed_angle               0 non-null       float64
 76  at_bat_number                    459185 non-null  int64
 77  pitch_number                     459185 non-null  int64
 78  pitch_name                       437522 non-null  object
 79  home_score                       459185 non-null  int64
 80  away_score                       459185 non-null  int64
 81  bat_score                        459185 non-null  int64
 82  fld_score                        459185 non-null  int64
 83  post_away_score                  459185 non-null  int64
 84  post_home_score                  459185 non-null  int64
 85  post_bat_score                   459185 non-null  int64
 86  post_fld_score                   459185 non-null  int64
 87  if_fielding_alignment            0 non-null       float64
 88  of_fielding_alignment            0 non-null       float64
 89  spin_axis                        0 non-null       float64
 90  delta_home_win_exp               459185 non-null  float64
 91  delta_run_exp                    449456 non-null  float64
dtypes: float64(48), int64(28), object(16)
memory usage: 325.8+ MB

In [11]:
all_2008_stats_df.drop(columns=['batter', 'events', 'description', 'zone',
                                'des', 'game_type', 'stand', 'home_team',
                                'away_team', 'type', 'hit_location', 'bb_type',
                                'balls', 'strikes', 'pfx_x', 'spin_dir', 
                                'pfx_z', 'plate_x', 'plate_z', 'on_3b',
                                'on_2b', 'on_1b', 'outs_when_up', 'inning',
                                'inning_topbot', 'hc_x', 'hc_y', 'fielder_2',
                                'umpire', 'sv_id', 'hit_distance_sc', 'sz_top',
                                 'sz_bot', 'launch_speed', 'launch_angle', 'game_pk',
                                'pitcher.1', 'fielder_2.1', 'fielder_3', 'fielder_4',
                                'fielder_5', 'fielder_6', 'fielder_7', 'fielder_8',
                                'fielder_9', 'estimated_ba_using_speedangle',
                                'estimated_woba_using_speedangle', 'babip_value',
                                'launch_speed_angle', 'woba_value', 'woba_denom', 'iso_value', 
                                'at_bat_number', 'pitch_number', 'home_score', 'away_score',
                                'bat_score', 'fld_score', 'post_home_score', 'post_bat_score',
                                'post_fld_score', 'post_away_score', 'if_fielding_alignment',
                                'of_fielding_alignment', 'delta_home_win_exp',
                                'delta_run_exp', 'spin_rate_deprecated', 'break_angle_deprecated',
                               'break_length_deprecated', 'tfs_deprecated', 'tfs_zulu_deprecated',
                               'spin_axis', 'effective_speed', 'release_spin_rate', 'release_extension'], inplace=True)
all_2008_stats_df.head()

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,vy0,vz0,ax,ay,az,release_pos_y,pitch_name
0,FF,2008-09-28,94.4,2.17,6.08,"Rhodes, Arthur",121125,L,2008,-8.707990,-137.912339,-6.509925,14.542,26.437,-13.292,54.5,4-Seam Fastball
1,FF,2008-09-28,93.0,2.21,6.03,"Rhodes, Arthur",121125,L,2008,-5.173211,-136.112715,-4.206386,11.045,23.637,-14.797,54.5,4-Seam Fastball
2,NaN,2008-09-26,NaN,NaN,NaN,"Rhodes, Arthur",121125,L,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,2008-09-26,NaN,NaN,NaN,"Rhodes, Arthur",121125,L,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,FF,2008-09-22,92.2,1.87,6.72,"Rhodes, Arthur",121125,L,2008,-8.500073,-134.717333,-6.349345,13.193,25.168,-14.613,54.5,4-Seam Fastball

In [12]:
all_2008_stats_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 459185 entries, 0 to 459184
Data columns (total 17 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   pitch_type     437522 non-null  object
 1   game_date      459185 non-null  object
 2   release_speed  437503 non-null  float64
 3   release_pos_x  437492 non-null  float64
 4   release_pos_z  437492 non-null  float64
 5   player_name    459185 non-null  object
 6   pitcher        459185 non-null  int64
 7   p_throws       459185 non-null  object
 8   game_year      459185 non-null  int64
 9   vx0            437492 non-null  float64
 10  vy0            437492 non-null  float64
 11  vz0            437492 non-null  float64
 12  ax             437503 non-null  float64
 13  ay             437503 non-null  float64
 14  az             437503 non-null  float64
 15  release_pos_y  437492 non-null  float64
 16  pitch_name     437522 non-null  object
dtypes: float64(10), int64(2), object(5)
memory usage: 63.1+ MB

In [13]:
all_2008_stats_df = all_2008_stats_df.dropna(axis=0)

In [14]:
all_2008_stats_df.reset_index(inplace=True)

In [15]:
all_2008_stats_df.drop('index', axis=1)

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,vy0,vz0,ax,ay,az,release_pos_y,pitch_name
0,FF,2008-09-28,94.4,2.17,6.08,"Rhodes, Arthur",121125,L,2008,-8.707990,-137.912339,-6.509925,14.542,26.437,-13.292,54.5,4-Seam Fastball
1,FF,2008-09-28,93.0,2.21,6.03,"Rhodes, Arthur",121125,L,2008,-5.173211,-136.112715,-4.206386,11.045,23.637,-14.797,54.5,4-Seam Fastball
2,FF,2008-09-22,92.2,1.87,6.72,"Rhodes, Arthur",121125,L,2008,-8.500073,-134.717333,-6.349345,13.193,25.168,-14.613,54.5,4-Seam Fastball
3,SL,2008-09-22,83.5,1.67,6.77,"Rhodes, Arthur",121125,L,2008,-6.031356,-122.057007,-2.945559,-3.884,20.604,-31.864,54.5,Slider
4,FF,2008-09-22,92.7,1.94,6.68,"Rhodes, Arthur",121125,L,2008,-9.150760,-135.540457,-7.791941,16.832,28.019,-16.931,54.5,4-Seam Fastball
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
437487,SI,2008-04-05,91.7,-1.14,6.77,"Wainwright, Adam",425794,R,2008,7.410180,-134.463290,-7.755931,-15.885,38.429,-11.659,54.5,Sinker
437488,SI,2008-04-05,91.2,-1.23,6.71,"Wainwright, Adam",425794,R,2008,3.898923,-133.801230,-6.896768,-12.754,36.411,-12.260,54.5,Sinker
437489,SI,2008-04-05,91.5,-0.97,6.65,"Wainwright, Adam",425794,R,2008,4.816129,-133.904804,-10.691690,-12.569,32.474,-14.471,54.5,Sinker
437490,CU,2008-04-05,72.3,-1.15,6.93,"Wainwright, Adam",425794,R,2008,-0.206400,-106.350093,0.634643,7.885,26.262,-39.158,54.5,Curveball
437491,SI,2008-04-05,90.0,-1.01,6.71,"Wainwright, Adam",425794,R,2008,4.157547,-131.951764,-6.921964,-11.635,33.916,-15.532,54.5,Sinker

In [16]:
# Group by 'game_date' and 'pitcher' to calculate the total pitches
total_pitches = all_2008_stats_df.groupby(['game_date', 'pitcher', 'player_name']).size().reset_index(name='total_pitches')

# Group by 'game_date', 'pitcher', and 'pitch_type' to calculate the sum total of each pitch_type
total_pitches_by_type = all_2008_stats_df.groupby(['game_date', 'pitcher', 'player_name', 'pitch_type']).size().reset_index(name='count_by_pitch_type')

# Calculate averages of the specified metrics for each pitch type, grouped by game_date and pitcher
avg_metrics = all_2008_stats_df.groupby(['game_date', 'pitcher', 'player_name', 'pitch_type']).agg({
    'release_speed': 'mean',
    'release_pos_x': 'mean',
    'release_pos_z': 'mean',
    'vx0': 'mean',
    'vy0': 'mean',
    'vz0': 'mean',
    'ax': 'mean',
    'ay': 'mean',
    'az': 'mean',
    'release_pos_y': 'mean',
}).reset_index()

grouped_2008_df = total_pitches.merge(total_pitches_by_type, on=['game_date', 'pitcher', 'player_name'], how='left')
grouped_2008_df = grouped_2008_df.merge(avg_metrics, on=['game_date', 'pitcher', 'player_name', 'pitch_type'], how='left')

grouped_2008_df

,game_date,pitcher,player_name,total_pitches,pitch_type,count_by_pitch_type,release_speed,release_pos_x,release_pos_z,vx0,vy0,vz0,ax,ay,az,release_pos_y
0,2008-03-28,112526,"Colon, Bartolo",39,FF,10,93.610000,-1.094000,6.136000,4.088171,-137.324284,-4.636060,-9.542600,35.855500,-10.000600,54.5
1,2008-03-28,112526,"Colon, Bartolo",39,SI,17,92.500000,-1.200000,5.975882,7.145081,-135.639909,-3.658293,-16.398000,33.460706,-15.712059,54.5
2,2008-03-28,112526,"Colon, Bartolo",39,SL,12,84.333333,-1.324167,6.185000,3.248877,-123.762940,-2.673402,1.235917,28.714667,-25.267833,54.5
3,2008-03-28,118120,"Maddux, Greg",1,SI,1,86.600000,-3.640000,5.470000,11.619602,-127.018486,-2.052596,-13.153000,39.843000,-21.961000,54.5
4,2008-03-28,121556,"Rusch, Glendon",8,FF,4,90.050000,0.390000,5.875000,-3.588131,-132.336308,-4.748622,8.256500,37.847000,-12.092000,54.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28419,2008-09-30,448147,"Blackburn, Nick",89,CH,3,84.500000,-1.880000,6.210000,5.939837,-123.876961,-4.448008,-8.085667,28.021667,-16.695667,54.5
28420,2008-09-30,448147,"Blackburn, Nick",89,CU,4,79.400000,-1.940000,6.652500,3.044706,-116.456223,-0.357078,3.595000,23.050000,-31.974500,54.5
28421,2008-09-30,448147,"Blackburn, Nick",89,FC,21,89.338095,-1.937619,6.466190,6.012968,-130.845059,-5.931220,2.147714,29.167286,-18.180381,54.5
28422,2008-09-30,448147,"Blackburn, Nick",89,IN,4,70.450000,-1.627500,6.847500,12.260053,-102.571315,4.133443,-5.203750,17.883250,-21.419750,54.5
28423,2008-09-30,448147,"Blackburn, Nick",89,SI,57,93.314035,-2.057018,6.360175,7.062591,-136.663128,-6.380256,-16.457825,33.602649,-14.203825,54.5

In [17]:
grouped_2008_df['game_date'] = pd.to_datetime(grouped_2008_df['game_date'])
grouped_2008_df['season'] = grouped_2008_df['game_date'].dt.year

# Step 1: Season Total Pitches
season_total_pitches = grouped_2008_df.groupby(['pitcher', 'player_name', 'season'])['total_pitches'].sum().reset_index(name='season_total_pitches')

# Step 2: Season Total by Pitch Type
season_total_by_pitch_type = grouped_2008_df.groupby(['pitcher', 'player_name', 'season', 'pitch_type'])['count_by_pitch_type'].sum().reset_index(name='season_total_count_by_pitch_type')

# Weighted Averages Calculation Setup
weighted_avg_columns = ['release_speed', 'release_pos_x', 'release_pos_z', 'vx0', 'vy0', 'vz0', 'ax', 'ay', 'az', 'release_pos_y']
for col in weighted_avg_columns:
    grouped_2008_df[f'{col}_product'] = grouped_2008_df[col] * grouped_2008_df['count_by_pitch_type']

weighted_avg_aggregations = {f'{col}_product': 'sum' for col in weighted_avg_columns}
weighted_avg_aggregations['count_by_pitch_type'] = 'sum'

# Aggregate for weighted averages
weighted_avg_df = grouped_2008_df.groupby(['pitcher', 'player_name', 'season', 'pitch_type']).agg(weighted_avg_aggregations).reset_index()

# Calculate weighted averages
for col in weighted_avg_columns:
    weighted_avg_df[f'{col}_weighted_avg'] = weighted_avg_df[f'{col}_product'] / weighted_avg_df['count_by_pitch_type']

# Cleanup
weighted_avg_df.drop(columns=[f'{col}_product' for col in weighted_avg_columns], inplace=True)

# Merge season totals and weighted averages
final_2008_df = pd.merge(season_total_pitches, season_total_by_pitch_type, on=['pitcher', 'player_name', 'season'])
final_2008_df = pd.merge(final_2008_df, weighted_avg_df, on=['pitcher', 'player_name', 'season', 'pitch_type'])

final_2008_df.head()

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,110683,"Batista, Miguel",2008,10287,CH,183,183,82.641530,-2.031639,6.010710,5.030589,-121.086910,-3.236765,-7.208295,25.458301,-22.841470,54.5
1,110683,"Batista, Miguel",2008,10287,CU,89,89,75.425843,-2.171910,6.275506,3.901072,-110.627789,-1.246458,4.697427,21.880798,-30.597461,54.5
2,110683,"Batista, Miguel",2008,10287,FC,6,6,90.566667,-2.036667,6.021667,6.288426,-132.625534,-3.528409,-0.497500,27.095833,-16.729000,54.5
3,110683,"Batista, Miguel",2008,10287,FF,286,286,92.263986,-1.918287,5.976259,5.195557,-135.256725,-4.764332,-4.447133,32.437836,-14.849983,54.5
4,110683,"Batista, Miguel",2008,10287,IN,2,2,50.600000,-1.390000,7.635000,-0.433396,-73.714833,7.335296,1.334000,10.275000,-27.784500,54.5

In [18]:
final_2008_df['player_name'] = final_2008_df['player_name'].str.lower().str.strip().str.replace(r'\*$', '', regex=True)
final_2008_df

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,110683,"batista, miguel",2008,10287,CH,183,183,82.641530,-2.031639,6.010710,5.030589,-121.086910,-3.236765,-7.208295,25.458301,-22.841470,54.5
1,110683,"batista, miguel",2008,10287,CU,89,89,75.425843,-2.171910,6.275506,3.901072,-110.627789,-1.246458,4.697427,21.880798,-30.597461,54.5
2,110683,"batista, miguel",2008,10287,FC,6,6,90.566667,-2.036667,6.021667,6.288426,-132.625534,-3.528409,-0.497500,27.095833,-16.729000,54.5
3,110683,"batista, miguel",2008,10287,FF,286,286,92.263986,-1.918287,5.976259,5.195557,-135.256725,-4.764332,-4.447133,32.437836,-14.849983,54.5
4,110683,"batista, miguel",2008,10287,IN,2,2,50.600000,-1.390000,7.635000,-0.433396,-73.714833,7.335296,1.334000,10.275000,-27.784500,54.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1574,502188,"samardzija, jeff",2008,1820,FS,99,99,86.302020,-2.333232,6.583636,6.802709,-126.226226,-5.324773,-10.927303,24.940687,-24.107939,54.5
1575,502188,"samardzija, jeff",2008,1820,IN,6,6,68.650000,-2.868333,6.941667,-1.886758,-100.577489,0.512961,-3.539833,14.873000,-23.343500,54.5
1576,502188,"samardzija, jeff",2008,1820,PO,1,1,84.900000,-3.120000,6.670000,-2.171512,-124.318167,7.649149,-9.647000,25.217000,-21.831000,54.5
1577,502188,"samardzija, jeff",2008,1820,SI,83,83,95.686747,-2.495542,6.357831,9.600795,-139.918356,-4.335994,-21.198133,31.507867,-20.720253,54.5
1578,502188,"samardzija, jeff",2008,1820,SL,45,45,83.173333,-2.405333,6.608444,5.891971,-121.694904,-2.673257,-1.077689,22.177911,-29.623311,54.5

In [19]:
print(final_2008_df['player_name'].unique())

['batista, miguel' 'brocail, doug' 'byrd, paul' 'carpenter, chris'
 'colon, bartolo' 'dessens, elmer' 'estes, shawn' 'eyre, scott'
 'glavine, tom' 'gordon, tom' 'hampton, mike' 'hawkins, latroy'
 'hernandez, livan' 'isringhausen, jason' 'lieber, jon' 'loaiza, esteban'
 'lowe, derek' 'maddux, greg' 'martinez, pedro' 'mercker, kent'
 'millwood, kevin' 'moehler, brian' 'morris, matt' 'moyer, jamie'
 'mussina, mike' 'nomo, hideo' 'oliver, darren' 'park, chan ho'
 'pettitte, andy' 'reyes, dennys' 'rhodes, arthur' 'rogers, kenny'
 'rusch, glendon' 'smoltz, john' 'springer, russ' 'sturtze, tanyon'
 'suppan, jeff' 'tavarez, julian' 'tomko, brett' 'torres, salomon'
 'trachsel, steve' 'villone, ron' 'wakefield, tim' 'weathers, david'
 'williams, woody' 'wright, jamey' 'looper, braden' 'washburn, jarrod'
 'ponson, sidney' 'dempster, ryan' 'elarton, scott' 'wood, kerry'
 'vazquez, javier' 'pavano, carl' 'perez, odalis' 'nunez, vladimir'
 'halladay, roy' 'schoeneweis, scott' 'wolf, randy' 'figueroa, nelson'
 'redman, mark' 'nathan, joe' 'davis, doug' 'marquis, jason'
 'moss, damian' 'fogg, josh' 'wells, kip' 'burnett, a.j.' 'armas, tony'
 'lilly, ted' 'westbrook, jake' 'mulder, mark' 'glover, gary'
 'penny, brad' 'franklin, ryan' 'zito, barry' 'hudson, tim'
 'padilla, vicente' 'meche, gil' 'durbin, chad' 'downs, scott'
 'chacon, shawn' 'santana, johan' 'arroyo, bronson' 'benoit, joaquÃ­n'
 'beckett, josh' 'belisle, matt' 'garland, jon' 'buehrle, mark'
 'sabathia, cc' 'vargas, claudio' 'sheets, ben' 'eaton, adam'
 'dickey, r.a.' 'pineiro, joel' 'affeldt, jeremy' 'lohse, kyle'
 'duckworth, brandon' 'cook, aaron' 'oswalt, roy' 'redding, tim'
 'silva, carlos' 'ramirez, horacio' 'moseley, dustin' 'fossum, casey'
 'zambrano, carlos' 'jennings, jason' 'lackey, john' 'de la rosa, jorge'
 'backe, brandon' 'bedard, erik' 'sosa, jorge' 'myers, brett'
 'peavy, jake' 'harang, aaron' 'pÃ©rez, oliver' 'saarloos, kirk'
 'hernandez, runelvys' 'hendrickson, mark' 'robertson, nate'
 'davis, jason' 'tallet, brian' 'guthrie, jeremy' 'wang, chien-ming'
 'gobble, jimmy' 'wellemeyer, todd' 'mcclung, seth' 'kuo, hung-chih'
 'cabrera, daniel' 'webb, brandon' 'carrasco, d.j.' 'ledezma, wilfredo'
 'contreras, jose' 'wainwright, adam' 'bonser, boof' 'bonderman, jeremy'
 'greinke, zack' 'harden, rich' 'floyd, gavin' 'willis, dontrelle'
 'haren, dan' 'hill, shawn' 'jackson, edwin' 'maine, john'
 'santana, ervin' 'correia, kevin' 'gaudin, chad' 'simon, alfredo'
 'blanton, joe' 'snell, ian' 'mcgowan, dustin' 'germano, justin'
 'maholm, paul' 'cain, matt' 'hamels, cole' 'kazmir, scott' 'young, chris'
 'danks, john' 'thompson, brad' 'hernandez, roberto' 'francis, jeff'
 'hernÃ¡ndez, fÃ©lix' 'petit, yusmeiro' 'bush, dave' 'loe, kameron'
 'verlander, justin' 'liriano, francisco' 'tejeda, robinson'
 'saunders, joe' 'jimÃ©nez, ubaldo' 'hammel, jason' 'burres, brian'
 'rodriguez, wandy' 'mendoza, luis' 'sÃ¡nchez, anÃ­bal' 'davies, kyle'
 'rowland-smith, ryan' 'reyes, anthony' 'duke, zach' 'olsen, scott'
 'mccarthy, brandon' 'miner, zach' 'niemann, jeff' 'karstens, jeff'
 'laffey, aaron' 'feldman, scott' 'nolasco, ricky' 'marshall, sean'
 'stults, eric' 'chavez, jesse' 'eveland, dana' 'litsch, jesse'
 'bannister, brian' 'blackburn, nick' 'parra, manny' 'hill, rich'
 'shields, james' 'wells, randy' 'garcÃ­a, jaime' 'volquez, edinson'
 'weaver, jered' 'wilson, c.j.' 'galarraga, armando' 'billingsley, chad'
 'gallardo, yovani' 'marcum, shaun' 'owings, micah' 'lester, jon'
 'kendrick, kyle' 'gorzelanny, tom' 'kennedy, ian' 'miller, andrew'
 'leblanc, wade' 'scherzer, max' 'lincecum, tim' 'buchholz, clay'
 'morrow, brandon' 'richard, clayton' 'villanueva, carlos' 'hensley, clay'
 'ohlendorf, ross' 'price, david' 'sÃ¡nchez, jonathan' 'cueto, johnny'
 'bergmann, jason' 'bailey, homer' 'harrison, matt' 'jurrjens, jair'
 'reyes, jo-jo' 'happ, j.a.' 'sonnanstine, andy' 'volstad, chris'
 'lannan, john' 'slowey, kevin' 'humber, philip' 'hochevar, luke'
 'pelfrey, mike' 'sowers, jeremy' 'braden, dallas' 'gonzÃ¡lez, gio'
 'hughes, phil' 'estrada, marco' 'morales, franklin' 'masterson, justin'
 'niese, jonathon' 'kershaw, clayton' 'hunter, tommy' 'garza, matt'
 'kuroda, hiroki' 'matsuzaka, daisuke' 'samardzija, jeff']

In [20]:
def remove_accents(input_str):
    nfkd_form = unicodedata.normalize('NFKD', input_str)
    return "".join([c for c in nfkd_form if not unicodedata.combining(c)])

def clean_name(name):
    name = name.lower()
    name = remove_accents(name)
    name = re.sub(r'[-.]', '', name)
    name = re.sub(r'\s+', ' ', name).strip()
    return name

final_2008_df['player_name'] = final_2008_df['player_name'].apply(clean_name)

In [21]:
# Convert 'player_name' from "last name, first name" to "first name last name"
final_2008_df['Name'] = final_2008_df['player_name'].apply(lambda x: ' '.join(x.split(', ')[::-1]))

Finally!

Now merge the two DF on 'Name' and 'season'.

In [28]:
# Now, you can perform the merge using 'Name' and 'season' as the keys for both DataFrames
better_2008_df = pd.merge(final_2008_df, 
                          cleaning_filtered_df[['Name', 'season', 'Age']],
                          on=['Name', 'season'],
                          how='left')

In [29]:
better_2008_df

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg,Name,Age
0,110683,"batista, miguel",2008,10287,CH,183,183,82.641530,-2.031639,6.010710,5.030589,-121.086910,-3.236765,-7.208295,25.458301,-22.841470,54.5,miguel batista,37.0
1,110683,"batista, miguel",2008,10287,CU,89,89,75.425843,-2.171910,6.275506,3.901072,-110.627789,-1.246458,4.697427,21.880798,-30.597461,54.5,miguel batista,37.0
2,110683,"batista, miguel",2008,10287,FC,6,6,90.566667,-2.036667,6.021667,6.288426,-132.625534,-3.528409,-0.497500,27.095833,-16.729000,54.5,miguel batista,37.0
3,110683,"batista, miguel",2008,10287,FF,286,286,92.263986,-1.918287,5.976259,5.195557,-135.256725,-4.764332,-4.447133,32.437836,-14.849983,54.5,miguel batista,37.0
4,110683,"batista, miguel",2008,10287,IN,2,2,50.600000,-1.390000,7.635000,-0.433396,-73.714833,7.335296,1.334000,10.275000,-27.784500,54.5,miguel batista,37.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1621,502188,"samardzija, jeff",2008,1820,FS,99,99,86.302020,-2.333232,6.583636,6.802709,-126.226226,-5.324773,-10.927303,24.940687,-24.107939,54.5,jeff samardzija,NaN
1622,502188,"samardzija, jeff",2008,1820,IN,6,6,68.650000,-2.868333,6.941667,-1.886758,-100.577489,0.512961,-3.539833,14.873000,-23.343500,54.5,jeff samardzija,NaN
1623,502188,"samardzija, jeff",2008,1820,PO,1,1,84.900000,-3.120000,6.670000,-2.171512,-124.318167,7.649149,-9.647000,25.217000,-21.831000,54.5,jeff samardzija,NaN
1624,502188,"samardzija, jeff",2008,1820,SI,83,83,95.686747,-2.495542,6.357831,9.600795,-139.918356,-4.335994,-21.198133,31.507867,-20.720253,54.5,jeff samardzija,NaN
1625,502188,"samardzija, jeff",2008,1820,SL,45,45,83.173333,-2.405333,6.608444,5.891971,-121.694904,-2.673257,-1.077689,22.177911,-29.623311,54.5,jeff samardzija,NaN

In [30]:
better_2008_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1626 entries, 0 to 1625
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   pitcher                           1626 non-null   int64
 1   player_name                       1626 non-null   object
 2   season                            1626 non-null   int32
 3   season_total_pitches              1626 non-null   int64
 4   pitch_type                        1626 non-null   object
 5   season_total_count_by_pitch_type  1626 non-null   int64
 6   count_by_pitch_type               1626 non-null   int64
 7   release_speed_weighted_avg        1626 non-null   float64
 8   release_pos_x_weighted_avg        1626 non-null   float64
 9   release_pos_z_weighted_avg        1626 non-null   float64
 10  vx0_weighted_avg                  1626 non-null   float64
 11  vy0_weighted_avg                  1626 non-null   float64
 12  vz0_weighted_avg                  1626 non-null   float64
 13  ax_weighted_avg                   1626 non-null   float64
 14  ay_weighted_avg                   1626 non-null   float64
 15  az_weighted_avg                   1626 non-null   float64
 16  release_pos_y_weighted_avg        1626 non-null   float64
 17  Name                              1626 non-null   object
 18  Age                               1358 non-null   float64
dtypes: float64(11), int32(1), int64(4), object(3)
memory usage: 235.1+ KB

In [31]:
"""
better_2008_df.to_csv('data/better_2008_df.csv')
"""

"\nbetter_2008_df.to_csv('better_2008_df.csv')\n"

This process was done for all years from 2008-2023.

Will concat all 'better' DF in data_cleaning_notebook_4

In [2]:
"""
all_2010_stats_df = pd.read_csv('~/Documents/Flatiron/Project_5_/data/all_2010_stats_df.csv', index_col=0)
"""

In [3]:
"""
all_2010_stats_df.info()
"""

<class 'pandas.core.frame.DataFrame'>
Index: 474758 entries, 0 to 474757
Data columns (total 92 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   pitch_type                       471786 non-null  object
 1   game_date                        474758 non-null  object
 2   release_speed                    471783 non-null  float64
 3   release_pos_x                    471770 non-null  float64
 4   release_pos_z                    471770 non-null  float64
 5   player_name                      474758 non-null  object
 6   batter                           474758 non-null  int64
 7   pitcher                          474758 non-null  int64
 8   events                           124976 non-null  object
 9   description                      474758 non-null  object
 10  spin_dir                         0 non-null       float64
 11  spin_rate_deprecated             0 non-null       float64
 12  break_angle_deprecated           0 non-null       float64
 13  break_length_deprecated          0 non-null       float64
 14  zone                             471783 non-null  float64
 15  des                              474757 non-null  object
 16  game_type                        474758 non-null  object
 17  stand                            474758 non-null  object
 18  p_throws                         474758 non-null  object
 19  home_team                        474758 non-null  object
 20  away_team                        474758 non-null  object
 21  type                             474758 non-null  object
 22  hit_location                     110347 non-null  float64
 23  bb_type                          91270 non-null   object
 24  balls                            474758 non-null  int64
 25  strikes                          474758 non-null  int64
 26  game_year                        474758 non-null  int64
 27  pfx_x                            471770 non-null  float64
 28  pfx_z                            471770 non-null  float64
 29  plate_x                          471783 non-null  float64
 30  plate_z                          471783 non-null  float64
 31  on_3b                            44276 non-null   float64
 32  on_2b                            87596 non-null   float64
 33  on_1b                            140420 non-null  float64
 34  outs_when_up                     474758 non-null  int64
 35  inning                           474758 non-null  int64
 36  inning_topbot                    474758 non-null  object
 37  hc_x                             84545 non-null   float64
 38  hc_y                             84545 non-null   float64
 39  tfs_deprecated                   0 non-null       float64
 40  tfs_zulu_deprecated              0 non-null       float64
 41  fielder_2                        474758 non-null  int64
 42  umpire                           0 non-null       float64
 43  sv_id                            471806 non-null  object
 44  vx0                              471770 non-null  float64
 45  vy0                              471770 non-null  float64
 46  vz0                              471770 non-null  float64
 47  ax                               471783 non-null  float64
 48  ay                               471783 non-null  float64
 49  az                               471783 non-null  float64
 50  sz_top                           471783 non-null  float64
 51  sz_bot                           471783 non-null  float64
 52  hit_distance_sc                  0 non-null       float64
 53  launch_speed                     0 non-null       float64
 54  launch_angle                     0 non-null       float64
 55  effective_speed                  0 non-null       float64
 56  release_spin_rate                0 non-null       float64
 57  release_extension                0 non-null       float64
 58  game_pk                          474758 non-null  int64
 59  pitcher.1                        474758 non-null  int64
 60  fielder_2.1                      474758 non-null  int64
 61  fielder_3                        474758 non-null  int64
 62  fielder_4                        474758 non-null  int64
 63  fielder_5                        474758 non-null  int64
 64  fielder_6                        474758 non-null  int64
 65  fielder_7                        474758 non-null  int64
 66  fielder_8                        474758 non-null  int64
 67  fielder_9                        474758 non-null  int64
 68  release_pos_y                    471770 non-null  float64
 69  estimated_ba_using_speedangle    0 non-null       float64
 70  estimated_woba_using_speedangle  0 non-null       float64
 71  woba_value                       124977 non-null  float64
 72  woba_denom                       0 non-null       float64
 73  babip_value                      124977 non-null  float64
 74  iso_value                        124977 non-null  float64
 75  launch_speed_angle               0 non-null       float64
 76  at_bat_number                    474758 non-null  int64
 77  pitch_number                     474758 non-null  int64
 78  pitch_name                       471786 non-null  object
 79  home_score                       474758 non-null  int64
 80  away_score                       474758 non-null  int64
 81  bat_score                        474758 non-null  int64
 82  fld_score                        474758 non-null  int64
 83  post_away_score                  474758 non-null  int64
 84  post_home_score                  474758 non-null  int64
 85  post_bat_score                   474758 non-null  int64
 86  post_fld_score                   474758 non-null  int64
 87  if_fielding_alignment            0 non-null       float64
 88  of_fielding_alignment            0 non-null       float64
 89  spin_axis                        0 non-null       float64
 90  delta_home_win_exp               474758 non-null  float64
 91  delta_run_exp                    472124 non-null  float64
dtypes: float64(48), int64(28), object(16)
memory usage: 336.9+ MB

In [4]:
"""
all_2010_stats_df.drop(columns=['batter', 'events', 'description', 'zone',
                                'des', 'game_type', 'stand', 'home_team',
                                'away_team', 'type', 'hit_location', 'bb_type',
                                'balls', 'strikes', 'pfx_x', 'spin_dir', 
                                'pfx_z', 'plate_x', 'plate_z', 'on_3b',
                                'on_2b', 'on_1b', 'outs_when_up', 'inning',
                                'inning_topbot', 'hc_x', 'hc_y', 'fielder_2',
                                'umpire', 'sv_id', 'hit_distance_sc', 'sz_top',
                                 'sz_bot', 'launch_speed', 'launch_angle', 'game_pk',
                                'pitcher.1', 'fielder_2.1', 'fielder_3', 'fielder_4',
                                'fielder_5', 'fielder_6', 'fielder_7', 'fielder_8',
                                'fielder_9', 'estimated_ba_using_speedangle',
                                'estimated_woba_using_speedangle', 'babip_value',
                                'launch_speed_angle', 'woba_value', 'woba_denom', 'iso_value', 
                                'at_bat_number', 'pitch_number', 'home_score', 'away_score',
                                'bat_score', 'fld_score', 'post_home_score', 'post_bat_score',
                                'post_fld_score', 'post_away_score', 'if_fielding_alignment',
                                'of_fielding_alignment', 'delta_home_win_exp',
                                'delta_run_exp', 'spin_rate_deprecated', 'break_angle_deprecated',
                               'break_length_deprecated', 'tfs_deprecated', 'tfs_zulu_deprecated'], inplace=True)
all_2010_stats_df.head()
"""

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,...,vz0,ax,ay,az,effective_speed,release_spin_rate,release_extension,release_pos_y,pitch_name,spin_axis
0,SL,2010-10-03,82.8,1.82,6.45,"Rhodes, Arthur",121125,L,2010,-4.524183,...,-7.207636,-4.792,18.730,-31.203,NaN,NaN,NaN,54.5,Slider,NaN
1,SL,2010-10-03,81.1,1.76,6.46,"Rhodes, Arthur",121125,L,2010,-4.633618,...,-4.330090,-5.080,21.113,-34.174,NaN,NaN,NaN,54.5,Slider,NaN
2,FF,2010-10-03,90.3,1.94,6.31,"Rhodes, Arthur",121125,L,2010,-10.432844,...,-8.518459,6.879,25.487,-13.112,NaN,NaN,NaN,54.5,4-Seam Fastball,NaN
3,SL,2010-10-03,80.4,1.71,6.55,"Rhodes, Arthur",121125,L,2010,-4.970231,...,-2.309743,-3.617,22.976,-31.884,NaN,NaN,NaN,54.5,Slider,NaN
4,SL,2010-10-03,80.7,1.76,6.52,"Rhodes, Arthur",121125,L,2010,-3.735821,...,-2.970547,-4.951,19.275,-32.490,NaN,NaN,NaN,54.5,Slider,NaN

In [5]:
"""
all_2010_stats_df.info()
"""

<class 'pandas.core.frame.DataFrame'>
Index: 474758 entries, 0 to 474757
Data columns (total 21 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   pitch_type         471786 non-null  object
 1   game_date          474758 non-null  object
 2   release_speed      471783 non-null  float64
 3   release_pos_x      471770 non-null  float64
 4   release_pos_z      471770 non-null  float64
 5   player_name        474758 non-null  object
 6   pitcher            474758 non-null  int64
 7   p_throws           474758 non-null  object
 8   game_year          474758 non-null  int64
 9   vx0                471770 non-null  float64
 10  vy0                471770 non-null  float64
 11  vz0                471770 non-null  float64
 12  ax                 471783 non-null  float64
 13  ay                 471783 non-null  float64
 14  az                 471783 non-null  float64
 15  effective_speed    0 non-null       float64
 16  release_spin_rate  0 non-null       float64
 17  release_extension  0 non-null       float64
 18  release_pos_y      471770 non-null  float64
 19  pitch_name         471786 non-null  object
 20  spin_axis          0 non-null       float64
dtypes: float64(14), int64(2), object(5)
memory usage: 79.7+ MB

In [5]:
"""
all_2010_stats_df.drop(columns=['spin_axis', 'effective_speed',
                               'release_spin_rate', 'release_extension'], inplace=True)
all_2010_stats_df.head()
"""

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,vy0,vz0,ax,ay,az,release_pos_y,pitch_name
0,SL,2010-10-03,82.8,1.82,6.45,"Rhodes, Arthur",121125,L,2010,-4.524183,-120.941924,-7.207636,-4.792,18.730,-31.203,54.5,Slider
1,SL,2010-10-03,81.1,1.76,6.46,"Rhodes, Arthur",121125,L,2010,-4.633618,-118.613714,-4.330090,-5.080,21.113,-34.174,54.5,Slider
2,FF,2010-10-03,90.3,1.94,6.31,"Rhodes, Arthur",121125,L,2010,-10.432844,-131.690814,-8.518459,6.879,25.487,-13.112,54.5,4-Seam Fastball
3,SL,2010-10-03,80.4,1.71,6.55,"Rhodes, Arthur",121125,L,2010,-4.970231,-117.732494,-2.309743,-3.617,22.976,-31.884,54.5,Slider
4,SL,2010-10-03,80.7,1.76,6.52,"Rhodes, Arthur",121125,L,2010,-3.735821,-118.137504,-2.970547,-4.951,19.275,-32.490,54.5,Slider

In [6]:
"""
all_2010_stats_df = all_2010_stats_df.dropna(axis=0)
"""

In [7]:
"""
all_2010_stats_df.reset_index(inplace=True)
"""

In [8]:
"""
all_2010_stats_df.drop('index', axis=1)
"""

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,vy0,vz0,ax,ay,az,release_pos_y,pitch_name
0,SL,2010-10-03,82.8,1.82,6.45,"Rhodes, Arthur",121125,L,2010,-4.524183,-120.941924,-7.207636,-4.792,18.730,-31.203,54.5,Slider
1,SL,2010-10-03,81.1,1.76,6.46,"Rhodes, Arthur",121125,L,2010,-4.633618,-118.613714,-4.330090,-5.080,21.113,-34.174,54.5,Slider
2,FF,2010-10-03,90.3,1.94,6.31,"Rhodes, Arthur",121125,L,2010,-10.432844,-131.690814,-8.518459,6.879,25.487,-13.112,54.5,4-Seam Fastball
3,SL,2010-10-03,80.4,1.71,6.55,"Rhodes, Arthur",121125,L,2010,-4.970231,-117.732494,-2.309743,-3.617,22.976,-31.884,54.5,Slider
4,SL,2010-10-03,80.7,1.76,6.52,"Rhodes, Arthur",121125,L,2010,-3.735821,-118.137504,-2.970547,-4.951,19.275,-32.490,54.5,Slider
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
471765,SI,2010-04-07,91.6,-1.45,6.52,"Wainwright, Adam",425794,R,2010,6.006385,-134.106993,-8.357035,-12.274,29.424,-14.815,54.5,Sinker
471766,SI,2010-04-07,92.1,-1.29,6.58,"Wainwright, Adam",425794,R,2010,2.420999,-134.859547,-8.452956,-9.856,27.434,-14.636,54.5,Sinker
471767,SI,2010-04-07,91.8,-1.33,6.57,"Wainwright, Adam",425794,R,2010,6.437927,-134.534191,-5.116190,-9.857,29.613,-15.215,54.5,Sinker
471768,SI,2010-04-07,90.7,-1.28,6.65,"Wainwright, Adam",425794,R,2010,6.967487,-132.758436,-5.594620,-12.097,27.412,-20.002,54.5,Sinker
471769,SI,2010-04-07,92.2,-1.20,6.58,"Wainwright, Adam",425794,R,2010,4.381647,-135.087374,-4.197580,-11.508,27.207,-20.746,54.5,Sinker

In [10]:
"""
# Group by 'game_date' and 'pitcher' to calculate the total pitches
total_pitches = all_2010_stats_df.groupby(['game_date', 'pitcher', 'player_name']).size().reset_index(name='total_pitches')

# Group by 'game_date', 'pitcher', and 'pitch_type' to calculate the sum total of each pitch_type
total_pitches_by_type = all_2010_stats_df.groupby(['game_date', 'pitcher', 'player_name', 'pitch_type']).size().reset_index(name='count_by_pitch_type')

# Calculate averages of the specified metrics for each pitch type, grouped by game_date and pitcher
avg_metrics = all_2010_stats_df.groupby(['game_date', 'pitcher', 'player_name', 'pitch_type']).agg({
    'release_speed': 'mean',
    'release_pos_x': 'mean',
    'release_pos_z': 'mean',
    'vx0': 'mean',
    'vy0': 'mean',
    'vz0': 'mean',
    'ax': 'mean',
    'ay': 'mean',
    'az': 'mean',
    'release_pos_y': 'mean',
}).reset_index()

grouped_2010_df = total_pitches.merge(total_pitches_by_type, on=['game_date', 'pitcher', 'player_name'], how='left')
grouped_2010_df = grouped_2010_df.merge(avg_metrics, on=['game_date', 'pitcher', 'player_name', 'pitch_type'], how='left')

grouped_2010_df
"""

,game_date,pitcher,player_name,total_pitches,pitch_type,count_by_pitch_type,release_speed,release_pos_x,release_pos_z,vx0,vy0,vz0,ax,ay,az,release_pos_y
0,2010-04-04,120221,"Park, Chan Ho",21,CH,2,87.050000,-2.490000,5.720000,9.087924,-127.385128,-3.527226,-14.719500,26.835000,-20.092500,54.5
1,2010-04-04,120221,"Park, Chan Ho",21,CU,1,78.000000,-2.110000,5.950000,-0.087149,-114.401575,-0.474097,12.470000,19.322000,-30.707000,54.5
2,2010-04-04,120221,"Park, Chan Ho",21,FF,3,91.133333,-2.570000,5.866667,9.074657,-133.437334,-2.499592,-12.893000,30.009333,-13.226000,54.5
3,2010-04-04,120221,"Park, Chan Ho",21,SI,8,91.775000,-2.601250,5.691250,10.073392,-134.236923,-4.211243,-17.814000,28.639750,-12.917125,54.5
4,2010-04-04,120221,"Park, Chan Ho",21,SL,7,87.042857,-2.475714,5.797143,5.953335,-127.485161,-3.244534,1.911143,25.899714,-19.806571,54.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30332,2010-10-03,502009,"Latos, Mat",82,SI,20,94.400000,-1.066000,7.158500,4.675690,-138.064485,-8.157394,-10.385150,29.800800,-12.266400,54.5
30333,2010-10-03,502009,"Latos, Mat",82,SL,20,83.315000,-1.167000,7.045500,2.368084,-122.025905,-3.337774,3.778100,22.953200,-32.809150,54.5
30334,2010-10-03,519242,"Sale, Chris",30,CH,1,86.800000,3.840000,4.630000,-14.132285,-126.900365,-0.657864,20.948000,32.936000,-30.684000,54.5
30335,2010-10-03,519242,"Sale, Chris",30,SI,16,96.787500,3.454375,4.821875,-13.145404,-141.462686,-1.185453,19.623938,35.102375,-23.544313,54.5
30336,2010-10-03,519242,"Sale, Chris",30,SL,13,84.007692,3.500769,4.907692,-7.918955,-123.014666,1.566799,-0.857692,25.381769,-34.969692,54.5

In [11]:
"""
grouped_2010_df['game_date'] = pd.to_datetime(grouped_2010_df['game_date'])
grouped_2010_df['season'] = grouped_2010_df['game_date'].dt.year

# Step 1: Season Total Pitches
season_total_pitches = grouped_2010_df.groupby(['pitcher', 'player_name', 'season'])['total_pitches'].sum().reset_index(name='season_total_pitches')

# Step 2: Season Total by Pitch Type
season_total_by_pitch_type = grouped_2010_df.groupby(['pitcher', 'player_name', 'season', 'pitch_type'])['count_by_pitch_type'].sum().reset_index(name='season_total_count_by_pitch_type')

# Weighted Averages Calculation Setup
weighted_avg_columns = ['release_speed', 'release_pos_x', 'release_pos_z', 'vx0', 'vy0', 'vz0', 'ax', 'ay', 'az', 'release_pos_y']
for col in weighted_avg_columns:
    grouped_2010_df[f'{col}_product'] = grouped_2010_df[col] * grouped_2010_df['count_by_pitch_type']

weighted_avg_aggregations = {f'{col}_product': 'sum' for col in weighted_avg_columns}
weighted_avg_aggregations['count_by_pitch_type'] = 'sum'

# Aggregate for weighted averages
weighted_avg_df = grouped_2010_df.groupby(['pitcher', 'player_name', 'season', 'pitch_type']).agg(weighted_avg_aggregations).reset_index()

# Calculate weighted averages
for col in weighted_avg_columns:
    weighted_avg_df[f'{col}_weighted_avg'] = weighted_avg_df[f'{col}_product'] / weighted_avg_df['count_by_pitch_type']

# Cleanup
weighted_avg_df.drop(columns=[f'{col}_product' for col in weighted_avg_columns], inplace=True)

# Merge season totals and weighted averages
final_2010_df = pd.merge(season_total_pitches, season_total_by_pitch_type, on=['pitcher', 'player_name', 'season'])
final_2010_df = pd.merge(final_2010_df, weighted_avg_df, on=['pitcher', 'player_name', 'season', 'pitch_type'])

final_2010_df.head()
"""

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,110683,"Batista, Miguel",2010,4616,CH,28,28,84.150000,-1.638929,5.812143,4.123418,-123.258496,-2.012025,-8.174357,24.109786,-28.231107,54.5
1,110683,"Batista, Miguel",2010,4616,CU,3,3,74.666667,-1.730000,6.416667,1.452707,-109.676484,1.382751,6.491333,21.171667,-35.056667,54.5
2,110683,"Batista, Miguel",2010,4616,FF,164,164,93.057927,-1.578171,5.767683,5.209686,-136.354024,-4.331219,-7.577841,30.875140,-15.486085,54.5
3,110683,"Batista, Miguel",2010,4616,IN,13,13,58.238462,-1.419231,6.918462,1.722914,-84.907173,5.705495,-0.975154,11.299538,-27.589308,54.5
4,110683,"Batista, Miguel",2010,4616,PO,2,2,83.900000,-0.875000,5.840000,11.418994,-122.524630,-0.118320,-7.160500,23.998500,-17.308000,54.5

In [12]:
#final_2010_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1587 entries, 0 to 1586
Data columns (total 17 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   pitcher                           1587 non-null   int64
 1   player_name                       1587 non-null   object
 2   season                            1587 non-null   int32
 3   season_total_pitches              1587 non-null   int64
 4   pitch_type                        1587 non-null   object
 5   season_total_count_by_pitch_type  1587 non-null   int64
 6   count_by_pitch_type               1587 non-null   int64
 7   release_speed_weighted_avg        1587 non-null   float64
 8   release_pos_x_weighted_avg        1587 non-null   float64
 9   release_pos_z_weighted_avg        1587 non-null   float64
 10  vx0_weighted_avg                  1587 non-null   float64
 11  vy0_weighted_avg                  1587 non-null   float64
 12  vz0_weighted_avg                  1587 non-null   float64
 13  ax_weighted_avg                   1587 non-null   float64
 14  ay_weighted_avg                   1587 non-null   float64
 15  az_weighted_avg                   1587 non-null   float64
 16  release_pos_y_weighted_avg        1587 non-null   float64
dtypes: float64(10), int32(1), int64(4), object(2)
memory usage: 204.7+ KB

In [13]:
#final_2010_df

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,110683,"Batista, Miguel",2010,4616,CH,28,28,84.150000,-1.638929,5.812143,4.123418,-123.258496,-2.012025,-8.174357,24.109786,-28.231107,54.5
1,110683,"Batista, Miguel",2010,4616,CU,3,3,74.666667,-1.730000,6.416667,1.452707,-109.676484,1.382751,6.491333,21.171667,-35.056667,54.5
2,110683,"Batista, Miguel",2010,4616,FF,164,164,93.057927,-1.578171,5.767683,5.209686,-136.354024,-4.331219,-7.577841,30.875140,-15.486085,54.5
3,110683,"Batista, Miguel",2010,4616,IN,13,13,58.238462,-1.419231,6.918462,1.722914,-84.907173,5.705495,-0.975154,11.299538,-27.589308,54.5
4,110683,"Batista, Miguel",2010,4616,PO,2,2,83.900000,-0.875000,5.840000,11.418994,-122.524630,-0.118320,-7.160500,23.998500,-17.308000,54.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1582,544931,"Strasburg, Stephen",2010,4444,SL,2,2,97.350000,-1.145000,5.795000,1.440628,-142.620785,-5.159263,3.370000,31.474000,-24.252500,54.5
1583,545404,"Beachy, Brandon",2010,1020,CH,64,64,81.890625,-1.774375,5.996875,5.621112,-119.886628,-3.046023,-12.838531,23.017531,-24.187719,54.5
1584,545404,"Beachy, Brandon",2010,1020,CU,32,32,75.550000,-1.090313,6.538750,1.666819,-110.839633,1.525629,5.741781,20.311625,-40.895781,54.5
1585,545404,"Beachy, Brandon",2010,1020,FF,173,173,91.664162,-1.306936,6.509017,3.887371,-134.266070,-6.845491,-5.322584,29.586035,-13.371699,54.5
1586,545404,"Beachy, Brandon",2010,1020,IN,10,10,72.360000,-2.018000,7.025000,-0.900278,-105.900601,1.444490,-4.447600,18.077800,-22.011600,54.5

In [20]:
"""
final_2010_df['player_name'] = final_2010_df['player_name'].str.lower().str.strip().str.replace(r'\*$', '', regex=True)
final_2010_df
"""

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,110683,"batista, miguel",2010,4616,CH,28,28,84.150000,-1.638929,5.812143,4.123418,-123.258496,-2.012025,-8.174357,24.109786,-28.231107,54.5
1,110683,"batista, miguel",2010,4616,CU,3,3,74.666667,-1.730000,6.416667,1.452707,-109.676484,1.382751,6.491333,21.171667,-35.056667,54.5
2,110683,"batista, miguel",2010,4616,FF,164,164,93.057927,-1.578171,5.767683,5.209686,-136.354024,-4.331219,-7.577841,30.875140,-15.486085,54.5
3,110683,"batista, miguel",2010,4616,IN,13,13,58.238462,-1.419231,6.918462,1.722914,-84.907173,5.705495,-0.975154,11.299538,-27.589308,54.5
4,110683,"batista, miguel",2010,4616,PO,2,2,83.900000,-0.875000,5.840000,11.418994,-122.524630,-0.118320,-7.160500,23.998500,-17.308000,54.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1582,544931,"strasburg, stephen",2010,4444,SL,2,2,97.350000,-1.145000,5.795000,1.440628,-142.620785,-5.159263,3.370000,31.474000,-24.252500,54.5
1583,545404,"beachy, brandon",2010,1020,CH,64,64,81.890625,-1.774375,5.996875,5.621112,-119.886628,-3.046023,-12.838531,23.017531,-24.187719,54.5
1584,545404,"beachy, brandon",2010,1020,CU,32,32,75.550000,-1.090313,6.538750,1.666819,-110.839633,1.525629,5.741781,20.311625,-40.895781,54.5
1585,545404,"beachy, brandon",2010,1020,FF,173,173,91.664162,-1.306936,6.509017,3.887371,-134.266070,-6.845491,-5.322584,29.586035,-13.371699,54.5
1586,545404,"beachy, brandon",2010,1020,IN,10,10,72.360000,-2.018000,7.025000,-0.900278,-105.900601,1.444490,-4.447600,18.077800,-22.011600,54.5

In [21]:
#print(final_2010_df['player_name'].unique())

['batista, miguel' 'carpenter, chris' 'dessens, elmer' 'hampton, mike'
 'hawkins, latroy' 'hernandez, livan' 'lowe, derek' 'millwood, kevin'
 'moehler, brian' 'moyer, jamie' 'oliver, darren' 'park, chan ho'
 'pettitte, andy' 'reyes, dennys' 'rhodes, arthur' 'springer, russ'
 'suppan, jeff' 'wakefield, tim' 'wright, jamey' 'dempster, ryan'
 'ortiz, russ' 'wood, kerry' 'vazquez, javier' 'pavano, carl'
 'chen, bruce' 'halladay, roy' 'ortiz, ramon' 'schoeneweis, scott'
 'wolf, randy' 'figueroa, nelson' 'benson, kris' 'davis, doug'
 'marquis, jason' 'burnett, a.j.' 'lilly, ted' 'westbrook, jake'
 'lopez, rodrigo' 'penny, brad' 'franklin, ryan' 'weaver, jeff'
 'zito, barry' 'hudson, tim' 'padilla, vicente' 'meche, gil'
 'durbin, chad' 'downs, scott' 'santana, johan' 'arroyo, bronson'
 'benoit, joaquÃ­n' 'beckett, josh' 'belisle, matt' 'garland, jon'
 'buehrle, mark' 'sabathia, cc' 'vargas, claudio' 'sheets, ben'
 'dickey, r.a.' 'pineiro, joel' 'affeldt, jeremy' 'lohse, kyle'
 'cook, aaron' 'oswalt, roy' 'silva, carlos' 'ramirez, horacio'
 'moseley, dustin' 'zambrano, carlos' 'lackey, john' 'de la rosa, jorge'
 'chacin, gustavo' 'lewis, colby' 'sosa, jorge' 'myers, brett'
 'peavy, jake' 'harang, aaron' 'pÃ©rez, oliver' 'hendrickson, mark'
 'robertson, nate' 'tallet, brian' 'guthrie, jeremy' 'wellemeyer, todd'
 'kuo, hung-chih' 'capuano, chris' 'carrasco, d.j.' 'ledezma, wilfredo'
 'contreras, jose' 'wainwright, adam' 'bonser, boof' 'bonderman, jeremy'
 'greinke, zack' 'harden, rich' 'floyd, gavin' 'willis, dontrelle'
 'haren, dan' 'hill, shawn' 'jackson, edwin' 'maine, john'
 'santana, ervin' 'narveson, chris' 'correia, kevin' 'mitre, sergio'
 'gaudin, chad' 'simon, alfredo' 'blanton, joe' 'snell, ian'
 'germano, justin' 'maholm, paul' 'cain, matt' 'hamels, cole'
 'kazmir, scott' 'stauffer, tim' 'young, chris' 'danks, john'
 'thompson, brad' 'hernandez, roberto' 'francis, jeff' 'hernÃ¡ndez, fÃ©lix'
 'bush, dave' 'loe, kameron' 'verlander, justin' 'liriano, francisco'
 'tejeda, robinson' 'saunders, joe' 'jimÃ©nez, ubaldo' 'hammel, jason'
 'burres, brian' 'rodriguez, wandy' 'mendoza, luis' 'sÃ¡nchez, anÃ­bal'
 'davies, kyle' 'rowland-smith, ryan' 'duke, zach' 'olsen, scott'
 'niemann, jeff' 'karstens, jeff' 'laffey, aaron' 'feldman, scott'
 'nolasco, ricky' 'marshall, sean' 'chavez, jesse' 'eveland, dana'
 'litsch, jesse' 'detwiler, ross' 'cecil, brett' 'bannister, brian'
 'blackburn, nick' 'parra, manny' 'hill, rich' 'bergesen, brad'
 'shields, james' 'wells, randy' 'garcÃ­a, jaime' 'harrell, lucas'
 'volquez, edinson' 'vargas, jason' 'weaver, jered' 'wilson, c.j.'
 'medlen, kris' 'fister, doug' 'matusz, brian' 'galarraga, armando'
 'billingsley, chad' 'davis, wade' 'gallardo, yovani' 'marcum, shaun'
 'owings, micah' 'lester, jon' 'kendrick, kyle' 'gorzelanny, tom'
 'kennedy, ian' 'miller, andrew' 'leblanc, wade' 'scherzer, max'
 'huff, david' 'lincecum, tim' 'buchholz, clay' 'morrow, brandon'
 'richard, clayton' 'arrieta, jake' 'villanueva, carlos' 'hensley, clay'
 'ohlendorf, ross' 'price, david' 'sÃ¡nchez, jonathan' 'cueto, johnny'
 'bergmann, jason' 'bailey, homer' 'harrison, matt' 'jurrjens, jair'
 'reyes, jo-jo' "o'sullivan, sean" 'happ, j.a.' 'luebke, cory'
 'sonnanstine, andy' 'volstad, chris' 'tomlin, josh' 'lannan, john'
 'slowey, kevin' 'humber, philip' 'hochevar, luke' 'pelfrey, mike'
 'romero, ricky' 'braden, dallas' 'gonzÃ¡lez, gio' 'hughes, phil'
 'hanson, tommy' 'estrada, marco' 'paulino, felipe' 'morales, franklin'
 'doubront, felix' 'nova, ivÃ¡n' 'ogando, alexi' 'chacÃ­n, jhoulys'
 'rogers, esmil' 'carrasco, carlos' 'anderson, brett' 'worley, vance'
 'ross, tyson' 'drabek, kyle' 'wood, travis' 'masterson, justin'
 'hellickson, jeremy' 'niese, jonathon' 'kershaw, clayton'
 'cashner, andrew' 'duensing, brian' 'hunter, tommy' 'stammen, craig'
 'garza, matt' 'kuroda, hiroki' 'matsuzaka, daisuke' 'pineda, michael'
 'tillman, chris' 'minor, mike' 'latos, mat' 'norris, bud'
 'samardzija, jeff' 'leake, mike' 'cahill, trevor' 'holland, derek'
 'bumgarner, madison' 'gee, dillon' 'porcello, rick' 'sale, chris'
 'zimmermann, jordan' 'hudson, daniel' 'strasburg, stephen'
 'beachy, brandon']

In [34]:
"""
def remove_accents(input_str):
    nfkd_form = unicodedata.normalize('NFKD', input_str)
    return "".join([c for c in nfkd_form if not unicodedata.combining(c)])

def clean_name(name):
    name = name.lower()
    name = remove_accents(name)
    name = re.sub(r'[-.]', '', name)
    name = re.sub(r'\s+', ' ', name).strip()
    return name

final_2010_df['player_name'] = final_2010_df['player_name'].apply(clean_name)
"""

'\ndef remove_accents(input_str):\n    nfkd_form = unicodedata.normalize(\'NFKD\', input_str)\n    return "".join([c for c in nfkd_form if not unicodedata.combining(c)])\n\ndef clean_name(name):\n    name = name.lower()\n    name = remove_accents(name)\n    name = re.sub(r\'[-.]\', \'\', name)\n    name = re.sub(r\'\\s+\', \' \', name).strip()\n    return name\n\nfinal_2010_df[\'player_name\'] = final_2010_df[\'player_name\'].apply(clean_name)\n'

In [23]:
#final_2010_df

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,110683,"batista, miguel",2010,4616,CH,28,28,84.150000,-1.638929,5.812143,4.123418,-123.258496,-2.012025,-8.174357,24.109786,-28.231107,54.5
1,110683,"batista, miguel",2010,4616,CU,3,3,74.666667,-1.730000,6.416667,1.452707,-109.676484,1.382751,6.491333,21.171667,-35.056667,54.5
2,110683,"batista, miguel",2010,4616,FF,164,164,93.057927,-1.578171,5.767683,5.209686,-136.354024,-4.331219,-7.577841,30.875140,-15.486085,54.5
3,110683,"batista, miguel",2010,4616,IN,13,13,58.238462,-1.419231,6.918462,1.722914,-84.907173,5.705495,-0.975154,11.299538,-27.589308,54.5
4,110683,"batista, miguel",2010,4616,PO,2,2,83.900000,-0.875000,5.840000,11.418994,-122.524630,-0.118320,-7.160500,23.998500,-17.308000,54.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1582,544931,"strasburg, stephen",2010,4444,SL,2,2,97.350000,-1.145000,5.795000,1.440628,-142.620785,-5.159263,3.370000,31.474000,-24.252500,54.5
1583,545404,"beachy, brandon",2010,1020,CH,64,64,81.890625,-1.774375,5.996875,5.621112,-119.886628,-3.046023,-12.838531,23.017531,-24.187719,54.5
1584,545404,"beachy, brandon",2010,1020,CU,32,32,75.550000,-1.090313,6.538750,1.666819,-110.839633,1.525629,5.741781,20.311625,-40.895781,54.5
1585,545404,"beachy, brandon",2010,1020,FF,173,173,91.664162,-1.306936,6.509017,3.887371,-134.266070,-6.845491,-5.322584,29.586035,-13.371699,54.5
1586,545404,"beachy, brandon",2010,1020,IN,10,10,72.360000,-2.018000,7.025000,-0.900278,-105.900601,1.444490,-4.447600,18.077800,-22.011600,54.5

In [29]:
"""
# Convert 'player_name' from "last name, first name" to "first name last name"
final_2010_df['Name'] = final_2010_df['player_name'].apply(lambda x: ' '.join(x.split(', ')[::-1]))
"""

In [30]:
#final_2010_df

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg,Name
0,110683,"batista, miguel",2010,4616,CH,28,28,84.150000,-1.638929,5.812143,4.123418,-123.258496,-2.012025,-8.174357,24.109786,-28.231107,54.5,miguel batista
1,110683,"batista, miguel",2010,4616,CU,3,3,74.666667,-1.730000,6.416667,1.452707,-109.676484,1.382751,6.491333,21.171667,-35.056667,54.5,miguel batista
2,110683,"batista, miguel",2010,4616,FF,164,164,93.057927,-1.578171,5.767683,5.209686,-136.354024,-4.331219,-7.577841,30.875140,-15.486085,54.5,miguel batista
3,110683,"batista, miguel",2010,4616,IN,13,13,58.238462,-1.419231,6.918462,1.722914,-84.907173,5.705495,-0.975154,11.299538,-27.589308,54.5,miguel batista
4,110683,"batista, miguel",2010,4616,PO,2,2,83.900000,-0.875000,5.840000,11.418994,-122.524630,-0.118320,-7.160500,23.998500,-17.308000,54.5,miguel batista
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1582,544931,"strasburg, stephen",2010,4444,SL,2,2,97.350000,-1.145000,5.795000,1.440628,-142.620785,-5.159263,3.370000,31.474000,-24.252500,54.5,stephen strasburg
1583,545404,"beachy, brandon",2010,1020,CH,64,64,81.890625,-1.774375,5.996875,5.621112,-119.886628,-3.046023,-12.838531,23.017531,-24.187719,54.5,brandon beachy
1584,545404,"beachy, brandon",2010,1020,CU,32,32,75.550000,-1.090313,6.538750,1.666819,-110.839633,1.525629,5.741781,20.311625,-40.895781,54.5,brandon beachy
1585,545404,"beachy, brandon",2010,1020,FF,173,173,91.664162,-1.306936,6.509017,3.887371,-134.266070,-6.845491,-5.322584,29.586035,-13.371699,54.5,brandon beachy
1586,545404,"beachy, brandon",2010,1020,IN,10,10,72.360000,-2.018000,7.025000,-0.900278,-105.900601,1.444490,-4.447600,18.077800,-22.011600,54.5,brandon beachy

In [35]:
"""
# Now, you can perform the merge using 'Name' and 'season' as the keys for both DataFrames
better_2010_df = pd.merge(final_2010_df, 
                          cleaning_filtered_df[['Name', 'season', 'Age']],
                          on=['Name', 'season'],
                          how='left')
"""

In [36]:
#better_2010_df

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg,Name,Age
0,110683,"batista, miguel",2010,4616,CH,28,28,84.150000,-1.638929,5.812143,4.123418,-123.258496,-2.012025,-8.174357,24.109786,-28.231107,54.5,miguel batista,39.0
1,110683,"batista, miguel",2010,4616,CU,3,3,74.666667,-1.730000,6.416667,1.452707,-109.676484,1.382751,6.491333,21.171667,-35.056667,54.5,miguel batista,39.0
2,110683,"batista, miguel",2010,4616,FF,164,164,93.057927,-1.578171,5.767683,5.209686,-136.354024,-4.331219,-7.577841,30.875140,-15.486085,54.5,miguel batista,39.0
3,110683,"batista, miguel",2010,4616,IN,13,13,58.238462,-1.419231,6.918462,1.722914,-84.907173,5.705495,-0.975154,11.299538,-27.589308,54.5,miguel batista,39.0
4,110683,"batista, miguel",2010,4616,PO,2,2,83.900000,-0.875000,5.840000,11.418994,-122.524630,-0.118320,-7.160500,23.998500,-17.308000,54.5,miguel batista,39.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1588,544931,"strasburg, stephen",2010,4444,SL,2,2,97.350000,-1.145000,5.795000,1.440628,-142.620785,-5.159263,3.370000,31.474000,-24.252500,54.5,stephen strasburg,21.0
1589,545404,"beachy, brandon",2010,1020,CH,64,64,81.890625,-1.774375,5.996875,5.621112,-119.886628,-3.046023,-12.838531,23.017531,-24.187719,54.5,brandon beachy,23.0
1590,545404,"beachy, brandon",2010,1020,CU,32,32,75.550000,-1.090313,6.538750,1.666819,-110.839633,1.525629,5.741781,20.311625,-40.895781,54.5,brandon beachy,23.0
1591,545404,"beachy, brandon",2010,1020,FF,173,173,91.664162,-1.306936,6.509017,3.887371,-134.266070,-6.845491,-5.322584,29.586035,-13.371699,54.5,brandon beachy,23.0
1592,545404,"beachy, brandon",2010,1020,IN,10,10,72.360000,-2.018000,7.025000,-0.900278,-105.900601,1.444490,-4.447600,18.077800,-22.011600,54.5,brandon beachy,23.0

In [37]:
#better_2010_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1593 entries, 0 to 1592
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   pitcher                           1593 non-null   int64
 1   player_name                       1593 non-null   object
 2   season                            1593 non-null   int32
 3   season_total_pitches              1593 non-null   int64
 4   pitch_type                        1593 non-null   object
 5   season_total_count_by_pitch_type  1593 non-null   int64
 6   count_by_pitch_type               1593 non-null   int64
 7   release_speed_weighted_avg        1593 non-null   float64
 8   release_pos_x_weighted_avg        1593 non-null   float64
 9   release_pos_z_weighted_avg        1593 non-null   float64
 10  vx0_weighted_avg                  1593 non-null   float64
 11  vy0_weighted_avg                  1593 non-null   float64
 12  vz0_weighted_avg                  1593 non-null   float64
 13  ax_weighted_avg                   1593 non-null   float64
 14  ay_weighted_avg                   1593 non-null   float64
 15  az_weighted_avg                   1593 non-null   float64
 16  release_pos_y_weighted_avg        1593 non-null   float64
 17  Name                              1593 non-null   object
 18  Age                               1325 non-null   float64
dtypes: float64(11), int32(1), int64(4), object(3)
memory usage: 230.4+ KB

In [39]:
"""
# Filter the DataFrame to show only rows where 'Age' is NaN
nan_age_rows = better_2010_df[better_2010_df['Age'].isna()]
nan_age_rows
"""

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg,Name,Age
14,113296,"dessens, elmer",2010,2892,CH,43,43,82.367442,-1.771860,6.211860,4.606984,-120.627157,-3.929832,-8.364558,24.211512,-24.296163,54.5,elmer dessens,NaN
15,113296,"dessens, elmer",2010,2892,CU,30,30,76.476667,-1.772667,6.200667,3.720013,-112.167720,0.209245,3.806467,20.363267,-35.633033,54.5,elmer dessens,NaN
16,113296,"dessens, elmer",2010,2892,FF,179,179,89.054749,-1.718547,6.203966,5.256251,-130.456371,-4.679089,-5.058715,27.798844,-17.629855,54.5,elmer dessens,NaN
17,113296,"dessens, elmer",2010,2892,IN,15,15,56.160000,-2.298000,6.697333,4.211218,-81.788541,7.283926,-1.837267,10.340733,-27.985267,54.5,elmer dessens,NaN
18,113296,"dessens, elmer",2010,2892,PO,3,3,79.000000,-1.726667,6.070000,8.175246,-115.468926,0.263475,-5.851333,22.264667,-21.336667,54.5,elmer dessens,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1490,501381,"pineda, michael",2010,40,FF,6,6,94.600000,-2.588333,6.225000,6.093135,-138.353182,-4.458742,-6.936167,27.391333,-17.348000,54.5,michael pineda,NaN
1491,501381,"pineda, michael",2010,40,SL,2,2,81.100000,-2.825000,5.990000,4.163681,-118.763081,0.504452,4.353000,21.547000,-34.129500,54.5,michael pineda,NaN
1567,519242,"sale, chris",2010,966,CH,25,25,87.924000,3.582400,4.924000,-10.244336,-128.693787,0.362468,18.509560,29.073440,-30.220920,54.5,chris sale,NaN
1568,519242,"sale, chris",2010,966,SI,238,238,96.969748,3.399664,5.051513,-12.394546,-141.753724,-1.725190,19.738950,34.464836,-21.209382,54.5,chris sale,NaN
1569,519242,"sale, chris",2010,966,SL,109,109,83.393578,3.447706,5.151743,-7.496532,-122.109077,1.046640,-1.554532,25.616633,-33.267266,54.5,chris sale,NaN

In [41]:
#better_2010_df.to_csv('data/better_2010_df.csv')

2009 DF

In [42]:
#all_2009_stats_df = pd.read_csv('~/Documents/Flatiron/Project_5_/data/all_2009_stats_df.csv', index_col=0)

In [43]:
"""
all_2009_stats_df.drop(columns=['batter', 'events', 'description', 'zone',
                                'des', 'game_type', 'stand', 'home_team',
                                'away_team', 'type', 'hit_location', 'bb_type',
                                'balls', 'strikes', 'pfx_x', 'spin_dir', 
                                'pfx_z', 'plate_x', 'plate_z', 'on_3b',
                                'on_2b', 'on_1b', 'outs_when_up', 'inning',
                                'inning_topbot', 'hc_x', 'hc_y', 'fielder_2',
                                'umpire', 'sv_id', 'hit_distance_sc', 'sz_top',
                                 'sz_bot', 'launch_speed', 'launch_angle', 'game_pk',
                                'pitcher.1', 'fielder_2.1', 'fielder_3', 'fielder_4',
                                'fielder_5', 'fielder_6', 'fielder_7', 'fielder_8',
                                'fielder_9', 'estimated_ba_using_speedangle',
                                'estimated_woba_using_speedangle', 'babip_value',
                                'launch_speed_angle', 'woba_value', 'woba_denom', 'iso_value', 
                                'at_bat_number', 'pitch_number', 'home_score', 'away_score',
                                'bat_score', 'fld_score', 'post_home_score', 'post_bat_score',
                                'post_fld_score', 'post_away_score', 'if_fielding_alignment',
                                'of_fielding_alignment', 'delta_home_win_exp',
                                'delta_run_exp', 'spin_rate_deprecated', 'break_angle_deprecated',
                               'break_length_deprecated', 'tfs_deprecated', 'tfs_zulu_deprecated'], inplace=True)
all_2009_stats_df.head()
"""

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,...,vz0,ax,ay,az,effective_speed,release_spin_rate,release_extension,release_pos_y,pitch_name,spin_axis
0,SL,2009-09-22,80.1,1.67,6.67,"Rhodes, Arthur",121125,L,2009,-4.389443,...,-5.082563,-3.957,19.039,-37.673,NaN,NaN,NaN,54.5,Slider,NaN
1,SL,2009-09-22,80.7,1.57,6.62,"Rhodes, Arthur",121125,L,2009,-4.559784,...,-4.151201,-4.269,21.402,-35.174,NaN,NaN,NaN,54.5,Slider,NaN
2,FF,2009-09-22,90.9,1.71,6.57,"Rhodes, Arthur",121125,L,2009,-7.138286,...,-7.508049,11.578,26.497,-14.777,NaN,NaN,NaN,54.5,4-Seam Fastball,NaN
3,SL,2009-09-22,80.7,1.73,6.67,"Rhodes, Arthur",121125,L,2009,-2.243166,...,-1.890828,-4.287,20.830,-32.739,NaN,NaN,NaN,54.5,Slider,NaN
4,SL,2009-09-22,82.5,1.60,6.67,"Rhodes, Arthur",121125,L,2009,-4.248895,...,-2.382552,-5.676,21.849,-31.268,NaN,NaN,NaN,54.5,Slider,NaN

In [44]:
#all_2009_stats_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 448937 entries, 0 to 448936
Data columns (total 21 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   pitch_type         443096 non-null  object
 1   game_date          448937 non-null  object
 2   release_speed      443089 non-null  float64
 3   release_pos_x      443084 non-null  float64
 4   release_pos_z      443084 non-null  float64
 5   player_name        448937 non-null  object
 6   pitcher            448937 non-null  int64
 7   p_throws           448937 non-null  object
 8   game_year          448937 non-null  int64
 9   vx0                443084 non-null  float64
 10  vy0                443084 non-null  float64
 11  vz0                443084 non-null  float64
 12  ax                 443089 non-null  float64
 13  ay                 443089 non-null  float64
 14  az                 443089 non-null  float64
 15  effective_speed    0 non-null       float64
 16  release_spin_rate  0 non-null       float64
 17  release_extension  0 non-null       float64
 18  release_pos_y      443084 non-null  float64
 19  pitch_name         443096 non-null  object
 20  spin_axis          0 non-null       float64
dtypes: float64(14), int64(2), object(5)
memory usage: 75.4+ MB

In [45]:
"""
all_2009_stats_df.drop(columns=['spin_axis', 'effective_speed',
                               'release_spin_rate', 'release_extension'], inplace=True)
all_2009_stats_df.head()
"""

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,vy0,vz0,ax,ay,az,release_pos_y,pitch_name
0,SL,2009-09-22,80.1,1.67,6.67,"Rhodes, Arthur",121125,L,2009,-4.389443,-117.087026,-5.082563,-3.957,19.039,-37.673,54.5,Slider
1,SL,2009-09-22,80.7,1.57,6.62,"Rhodes, Arthur",121125,L,2009,-4.559784,-118.109257,-4.151201,-4.269,21.402,-35.174,54.5,Slider
2,FF,2009-09-22,90.9,1.71,6.57,"Rhodes, Arthur",121125,L,2009,-7.138286,-132.926061,-7.508049,11.578,26.497,-14.777,54.5,4-Seam Fastball
3,SL,2009-09-22,80.7,1.73,6.67,"Rhodes, Arthur",121125,L,2009,-2.243166,-118.148051,-1.890828,-4.287,20.830,-32.739,54.5,Slider
4,SL,2009-09-22,82.5,1.60,6.67,"Rhodes, Arthur",121125,L,2009,-4.248895,-120.829471,-2.382552,-5.676,21.849,-31.268,54.5,Slider

In [46]:
#all_2009_stats_df = all_2009_stats_df.dropna(axis=0)

In [49]:
#all_2009_stats_df.reset_index(inplace=True)

In [50]:
#all_2009_stats_df.drop('index', axis=1)

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,vy0,vz0,ax,ay,az,release_pos_y,pitch_name
0,SL,2009-09-22,80.1,1.67,6.67,"Rhodes, Arthur",121125,L,2009,-4.389443,-117.087026,-5.082563,-3.957,19.039,-37.673,54.5,Slider
1,SL,2009-09-22,80.7,1.57,6.62,"Rhodes, Arthur",121125,L,2009,-4.559784,-118.109257,-4.151201,-4.269,21.402,-35.174,54.5,Slider
2,FF,2009-09-22,90.9,1.71,6.57,"Rhodes, Arthur",121125,L,2009,-7.138286,-132.926061,-7.508049,11.578,26.497,-14.777,54.5,4-Seam Fastball
3,SL,2009-09-22,80.7,1.73,6.67,"Rhodes, Arthur",121125,L,2009,-2.243166,-118.148051,-1.890828,-4.287,20.830,-32.739,54.5,Slider
4,SL,2009-09-22,82.5,1.60,6.67,"Rhodes, Arthur",121125,L,2009,-4.248895,-120.829471,-2.382552,-5.676,21.849,-31.268,54.5,Slider
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
443079,SI,2009-04-06,94.1,-0.92,6.72,"Wainwright, Adam",425794,R,2009,0.327870,-137.873328,-7.892886,-13.299,34.915,-10.835,54.5,Sinker
443080,FC,2009-04-06,86.2,-1.13,6.61,"Wainwright, Adam",425794,R,2009,3.660575,-126.088355,-8.242482,3.947,27.835,-29.235,54.5,Cutter
443081,SI,2009-04-06,91.6,-1.13,6.68,"Wainwright, Adam",425794,R,2009,4.595713,-134.329080,-5.774637,-12.951,34.036,-15.586,54.5,Sinker
443082,SI,2009-04-06,94.0,-1.05,6.44,"Wainwright, Adam",425794,R,2009,5.847546,-137.487764,-8.413200,-16.420,32.830,-16.306,54.5,Sinker
443083,SI,2009-04-06,92.2,-1.31,6.41,"Wainwright, Adam",425794,R,2009,4.925305,-135.262242,-6.260075,-18.510,32.758,-18.798,54.5,Sinker

In [51]:
"""
# Group by 'game_date' and 'pitcher' to calculate the total pitches
total_pitches = all_2009_stats_df.groupby(['game_date', 'pitcher', 'player_name']).size().reset_index(name='total_pitches')

# Group by 'game_date', 'pitcher', and 'pitch_type' to calculate the sum total of each pitch_type
total_pitches_by_type = all_2009_stats_df.groupby(['game_date', 'pitcher', 'player_name', 'pitch_type']).size().reset_index(name='count_by_pitch_type')

# Calculate averages of the specified metrics for each pitch type, grouped by game_date and pitcher
avg_metrics = all_2009_stats_df.groupby(['game_date', 'pitcher', 'player_name', 'pitch_type']).agg({
    'release_speed': 'mean',
    'release_pos_x': 'mean',
    'release_pos_z': 'mean',
    'vx0': 'mean',
    'vy0': 'mean',
    'vz0': 'mean',
    'ax': 'mean',
    'ay': 'mean',
    'az': 'mean',
    'release_pos_y': 'mean',
}).reset_index()

grouped_2009_df = total_pitches.merge(total_pitches_by_type, on=['game_date', 'pitcher', 'player_name'], how='left')
grouped_2009_df = grouped_2009_df.merge(avg_metrics, on=['game_date', 'pitcher', 'player_name', 'pitch_type'], how='left')

grouped_2009_df
"""

,game_date,pitcher,player_name,total_pitches,pitch_type,count_by_pitch_type,release_speed,release_pos_x,release_pos_z,vx0,vy0,vz0,ax,ay,az,release_pos_y
0,2009-04-05,113961,"Eyre, Scott",9,FF,6,90.050000,2.201667,6.741667,-8.485284,-131.516927,-9.666082,10.709167,28.296500,-11.721167,54.5
1,2009-04-05,113961,"Eyre, Scott",9,SL,3,81.866667,2.620000,6.576667,-7.452117,-119.644304,-4.436836,-4.361667,22.589000,-26.094333,54.5
2,2009-04-05,117955,"Lowe, Derek",97,FC,1,85.000000,-2.350000,6.370000,9.284933,-124.190979,-4.935491,-1.538000,24.912000,-25.779000,54.5
3,2009-04-05,117955,"Lowe, Derek",97,SI,59,89.418644,-2.445424,6.341017,9.345379,-130.922073,-4.287697,-19.156220,30.986729,-24.077678,54.5
4,2009-04-05,117955,"Lowe, Derek",97,SL,37,83.156757,-2.577838,6.246757,5.409004,-121.786644,-2.635946,1.751784,24.685108,-30.038378,54.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28445,2009-10-06,435261,"Miner, Zach",23,SL,6,84.300000,-2.970000,6.281667,5.155707,-123.486762,-0.897622,1.893833,23.242000,-29.624167,54.5
28446,2009-10-06,519144,"Porcello, Rick",92,CH,7,81.771429,-2.531429,6.271429,9.012146,-119.538790,-2.434296,-13.452143,22.791714,-25.110714,54.5
28447,2009-10-06,519144,"Porcello, Rick",92,FF,38,93.139474,-2.389211,6.437368,9.119490,-136.204660,-5.239991,-11.874053,28.893737,-13.801026,54.5
28448,2009-10-06,519144,"Porcello, Rick",92,SI,40,91.167500,-2.699750,6.208250,9.627457,-133.374449,-3.939914,-19.468350,28.288000,-22.817825,54.5
28449,2009-10-06,519144,"Porcello, Rick",92,SL,7,83.185714,-2.500000,6.431429,10.282546,-121.370113,-5.054979,-0.330714,24.008571,-29.756714,54.5

In [52]:
"""
grouped_2009_df['game_date'] = pd.to_datetime(grouped_2009_df['game_date'])
grouped_2009_df['season'] = grouped_2009_df['game_date'].dt.year

# Step 1: Season Total Pitches
season_total_pitches = grouped_2009_df.groupby(['pitcher', 'player_name', 'season'])['total_pitches'].sum().reset_index(name='season_total_pitches')

# Step 2: Season Total by Pitch Type
season_total_by_pitch_type = grouped_2009_df.groupby(['pitcher', 'player_name', 'season', 'pitch_type'])['count_by_pitch_type'].sum().reset_index(name='season_total_count_by_pitch_type')

# Weighted Averages Calculation Setup
weighted_avg_columns = ['release_speed', 'release_pos_x', 'release_pos_z', 'vx0', 'vy0', 'vz0', 'ax', 'ay', 'az', 'release_pos_y']
for col in weighted_avg_columns:
    grouped_2009_df[f'{col}_product'] = grouped_2009_df[col] * grouped_2009_df['count_by_pitch_type']

weighted_avg_aggregations = {f'{col}_product': 'sum' for col in weighted_avg_columns}
weighted_avg_aggregations['count_by_pitch_type'] = 'sum'

# Aggregate for weighted averages
weighted_avg_df = grouped_2009_df.groupby(['pitcher', 'player_name', 'season', 'pitch_type']).agg(weighted_avg_aggregations).reset_index()

# Calculate weighted averages
for col in weighted_avg_columns:
    weighted_avg_df[f'{col}_weighted_avg'] = weighted_avg_df[f'{col}_product'] / weighted_avg_df['count_by_pitch_type']

# Cleanup
weighted_avg_df.drop(columns=[f'{col}_product' for col in weighted_avg_columns], inplace=True)

# Merge season totals and weighted averages
final_2009_df = pd.merge(season_total_pitches, season_total_by_pitch_type, on=['pitcher', 'player_name', 'season'])
final_2009_df = pd.merge(final_2009_df, weighted_avg_df, on=['pitcher', 'player_name', 'season', 'pitch_type'])

final_2009_df.head()
"""

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,110683,"Batista, Miguel",2009,4267,CH,41,41,85.012195,-2.218537,5.706829,5.855133,-124.551149,-1.272244,-7.955195,26.476366,-27.023293,54.5
1,110683,"Batista, Miguel",2009,4267,CU,22,22,78.181818,-2.452727,5.734091,4.520884,-114.570196,-0.254067,4.821545,20.927591,-30.535500,54.5
2,110683,"Batista, Miguel",2009,4267,FF,137,137,93.719708,-2.247007,5.639781,6.880657,-137.275166,-3.722603,-7.989927,31.474693,-15.681956,54.5
3,110683,"Batista, Miguel",2009,4267,IN,1,1,53.500000,-2.340000,7.130000,-6.899020,-78.119736,4.971030,1.072000,11.680000,-27.760000,54.5
4,110683,"Batista, Miguel",2009,4267,SI,652,652,93.240031,-2.178834,5.575031,7.831769,-136.577136,-3.124205,-16.850879,31.951578,-21.594371,54.5

In [53]:
#final_2009_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1584 entries, 0 to 1583
Data columns (total 17 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   pitcher                           1584 non-null   int64
 1   player_name                       1584 non-null   object
 2   season                            1584 non-null   int32
 3   season_total_pitches              1584 non-null   int64
 4   pitch_type                        1584 non-null   object
 5   season_total_count_by_pitch_type  1584 non-null   int64
 6   count_by_pitch_type               1584 non-null   int64
 7   release_speed_weighted_avg        1584 non-null   float64
 8   release_pos_x_weighted_avg        1584 non-null   float64
 9   release_pos_z_weighted_avg        1584 non-null   float64
 10  vx0_weighted_avg                  1584 non-null   float64
 11  vy0_weighted_avg                  1584 non-null   float64
 12  vz0_weighted_avg                  1584 non-null   float64
 13  ax_weighted_avg                   1584 non-null   float64
 14  ay_weighted_avg                   1584 non-null   float64
 15  az_weighted_avg                   1584 non-null   float64
 16  release_pos_y_weighted_avg        1584 non-null   float64
dtypes: float64(10), int32(1), int64(4), object(2)
memory usage: 204.3+ KB

In [54]:
#final_2009_df

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,110683,"Batista, Miguel",2009,4267,CH,41,41,85.012195,-2.218537,5.706829,5.855133,-124.551149,-1.272244,-7.955195,26.476366,-27.023293,54.5
1,110683,"Batista, Miguel",2009,4267,CU,22,22,78.181818,-2.452727,5.734091,4.520884,-114.570196,-0.254067,4.821545,20.927591,-30.535500,54.5
2,110683,"Batista, Miguel",2009,4267,FF,137,137,93.719708,-2.247007,5.639781,6.880657,-137.275166,-3.722603,-7.989927,31.474693,-15.681956,54.5
3,110683,"Batista, Miguel",2009,4267,IN,1,1,53.500000,-2.340000,7.130000,-6.899020,-78.119736,4.971030,1.072000,11.680000,-27.760000,54.5
4,110683,"Batista, Miguel",2009,4267,SI,652,652,93.240031,-2.178834,5.575031,7.831769,-136.577136,-3.124205,-16.850879,31.951578,-21.594371,54.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1579,519455,"Zimmermann, Jordan",2009,6204,SL,248,248,86.192339,-2.075968,5.774960,4.629122,-126.239399,-1.572362,4.630371,23.980105,-28.553698,54.5
1580,543339,"Hudson, Daniel",2009,1144,CH,63,63,84.504762,-2.669683,5.010635,8.794285,-123.684311,-1.079443,-16.393984,25.872667,-26.518984,54.5
1581,543339,"Hudson, Daniel",2009,1144,CU,7,7,74.614286,-1.985714,5.717143,5.478231,-109.339602,0.932781,1.708000,19.771286,-32.701714,54.5
1582,543339,"Hudson, Daniel",2009,1144,FF,200,200,94.038500,-2.793500,5.024450,9.915154,-137.548811,-2.881965,-14.649815,30.972195,-15.124185,54.5
1583,543339,"Hudson, Daniel",2009,1144,SL,47,47,84.963830,-2.614681,5.405319,6.982745,-124.400905,-1.464148,-1.748787,24.961830,-26.658362,54.5

In [55]:
"""
final_2009_df['player_name'] = final_2009_df['player_name'].str.lower().str.strip().str.replace(r'\*$', '', regex=True)
final_2009_df
"""

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,110683,"batista, miguel",2009,4267,CH,41,41,85.012195,-2.218537,5.706829,5.855133,-124.551149,-1.272244,-7.955195,26.476366,-27.023293,54.5
1,110683,"batista, miguel",2009,4267,CU,22,22,78.181818,-2.452727,5.734091,4.520884,-114.570196,-0.254067,4.821545,20.927591,-30.535500,54.5
2,110683,"batista, miguel",2009,4267,FF,137,137,93.719708,-2.247007,5.639781,6.880657,-137.275166,-3.722603,-7.989927,31.474693,-15.681956,54.5
3,110683,"batista, miguel",2009,4267,IN,1,1,53.500000,-2.340000,7.130000,-6.899020,-78.119736,4.971030,1.072000,11.680000,-27.760000,54.5
4,110683,"batista, miguel",2009,4267,SI,652,652,93.240031,-2.178834,5.575031,7.831769,-136.577136,-3.124205,-16.850879,31.951578,-21.594371,54.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1579,519455,"zimmermann, jordan",2009,6204,SL,248,248,86.192339,-2.075968,5.774960,4.629122,-126.239399,-1.572362,4.630371,23.980105,-28.553698,54.5
1580,543339,"hudson, daniel",2009,1144,CH,63,63,84.504762,-2.669683,5.010635,8.794285,-123.684311,-1.079443,-16.393984,25.872667,-26.518984,54.5
1581,543339,"hudson, daniel",2009,1144,CU,7,7,74.614286,-1.985714,5.717143,5.478231,-109.339602,0.932781,1.708000,19.771286,-32.701714,54.5
1582,543339,"hudson, daniel",2009,1144,FF,200,200,94.038500,-2.793500,5.024450,9.915154,-137.548811,-2.881965,-14.649815,30.972195,-15.124185,54.5
1583,543339,"hudson, daniel",2009,1144,SL,47,47,84.963830,-2.614681,5.405319,6.982745,-124.400905,-1.464148,-1.748787,24.961830,-26.658362,54.5

In [56]:
#print(final_2010_df['player_name'].unique())

['batista, miguel' 'carpenter, chris' 'dessens, elmer' 'hampton, mike'
 'hawkins, latroy' 'hernandez, livan' 'lowe, derek' 'millwood, kevin'
 'moehler, brian' 'moyer, jamie' 'oliver, darren' 'park, chan ho'
 'pettitte, andy' 'reyes, dennys' 'rhodes, arthur' 'springer, russ'
 'suppan, jeff' 'wakefield, tim' 'wright, jamey' 'dempster, ryan'
 'ortiz, russ' 'wood, kerry' 'vazquez, javier' 'pavano, carl'
 'chen, bruce' 'halladay, roy' 'ortiz, ramon' 'schoeneweis, scott'
 'wolf, randy' 'figueroa, nelson' 'benson, kris' 'davis, doug'
 'marquis, jason' 'burnett, aj' 'lilly, ted' 'westbrook, jake'
 'lopez, rodrigo' 'penny, brad' 'franklin, ryan' 'weaver, jeff'
 'zito, barry' 'hudson, tim' 'padilla, vicente' 'meche, gil'
 'durbin, chad' 'downs, scott' 'santana, johan' 'arroyo, bronson'
 'benoit, joaquin' 'beckett, josh' 'belisle, matt' 'garland, jon'
 'buehrle, mark' 'sabathia, cc' 'vargas, claudio' 'sheets, ben'
 'dickey, ra' 'pineiro, joel' 'affeldt, jeremy' 'lohse, kyle'
 'cook, aaron' 'oswalt, roy' 'silva, carlos' 'ramirez, horacio'
 'moseley, dustin' 'zambrano, carlos' 'lackey, john' 'de la rosa, jorge'
 'chacin, gustavo' 'lewis, colby' 'sosa, jorge' 'myers, brett'
 'peavy, jake' 'harang, aaron' 'perez, oliver' 'hendrickson, mark'
 'robertson, nate' 'tallet, brian' 'guthrie, jeremy' 'wellemeyer, todd'
 'kuo, hungchih' 'capuano, chris' 'carrasco, dj' 'ledezma, wilfredo'
 'contreras, jose' 'wainwright, adam' 'bonser, boof' 'bonderman, jeremy'
 'greinke, zack' 'harden, rich' 'floyd, gavin' 'willis, dontrelle'
 'haren, dan' 'hill, shawn' 'jackson, edwin' 'maine, john'
 'santana, ervin' 'narveson, chris' 'correia, kevin' 'mitre, sergio'
 'gaudin, chad' 'simon, alfredo' 'blanton, joe' 'snell, ian'
 'germano, justin' 'maholm, paul' 'cain, matt' 'hamels, cole'
 'kazmir, scott' 'stauffer, tim' 'young, chris' 'danks, john'
 'thompson, brad' 'hernandez, roberto' 'francis, jeff' 'hernandez, felix'
 'bush, dave' 'loe, kameron' 'verlander, justin' 'liriano, francisco'
 'tejeda, robinson' 'saunders, joe' 'jimenez, ubaldo' 'hammel, jason'
 'burres, brian' 'rodriguez, wandy' 'mendoza, luis' 'sanchez, anibal'
 'davies, kyle' 'rowlandsmith, ryan' 'duke, zach' 'olsen, scott'
 'niemann, jeff' 'karstens, jeff' 'laffey, aaron' 'feldman, scott'
 'nolasco, ricky' 'marshall, sean' 'chavez, jesse' 'eveland, dana'
 'litsch, jesse' 'detwiler, ross' 'cecil, brett' 'bannister, brian'
 'blackburn, nick' 'parra, manny' 'hill, rich' 'bergesen, brad'
 'shields, james' 'wells, randy' 'garcia, jaime' 'harrell, lucas'
 'volquez, edinson' 'vargas, jason' 'weaver, jered' 'wilson, cj'
 'medlen, kris' 'fister, doug' 'matusz, brian' 'galarraga, armando'
 'billingsley, chad' 'davis, wade' 'gallardo, yovani' 'marcum, shaun'
 'owings, micah' 'lester, jon' 'kendrick, kyle' 'gorzelanny, tom'
 'kennedy, ian' 'miller, andrew' 'leblanc, wade' 'scherzer, max'
 'huff, david' 'lincecum, tim' 'buchholz, clay' 'morrow, brandon'
 'richard, clayton' 'arrieta, jake' 'villanueva, carlos' 'hensley, clay'
 'ohlendorf, ross' 'price, david' 'sanchez, jonathan' 'cueto, johnny'
 'bergmann, jason' 'bailey, homer' 'harrison, matt' 'jurrjens, jair'
 'reyes, jojo' "o'sullivan, sean" 'happ, ja' 'luebke, cory'
 'sonnanstine, andy' 'volstad, chris' 'tomlin, josh' 'lannan, john'
 'slowey, kevin' 'humber, philip' 'hochevar, luke' 'pelfrey, mike'
 'romero, ricky' 'braden, dallas' 'gonzalez, gio' 'hughes, phil'
 'hanson, tommy' 'estrada, marco' 'paulino, felipe' 'morales, franklin'
 'doubront, felix' 'nova, ivan' 'ogando, alexi' 'chacin, jhoulys'
 'rogers, esmil' 'carrasco, carlos' 'anderson, brett' 'worley, vance'
 'ross, tyson' 'drabek, kyle' 'wood, travis' 'masterson, justin'
 'hellickson, jeremy' 'niese, jonathon' 'kershaw, clayton'
 'cashner, andrew' 'duensing, brian' 'hunter, tommy' 'stammen, craig'
 'garza, matt' 'kuroda, hiroki' 'matsuzaka, daisuke' 'pineda, michael'
 'tillman, chris' 'minor, mike' 'latos, mat' 'norris, bud'
 'samardzija, jeff' 'leake, mike' 'cahill, trevor' 'holland, derek'
 'bumgarner, madison' 'gee, dillon' 'porcello, rick' 'sale, chris'
 'zimmermann, jordan' 'hudson, daniel' 'strasburg, stephen'
 'beachy, brandon']

In [58]:
"""
def remove_accents(input_str):
    nfkd_form = unicodedata.normalize('NFKD', input_str)
    return "".join([c for c in nfkd_form if not unicodedata.combining(c)])

def clean_name(name):
    name = name.lower()
    name = remove_accents(name)
    name = re.sub(r'[-.]', '', name)
    name = re.sub(r'\s+', ' ', name).strip()
    return name

final_2009_df['player_name'] = final_2009_df['player_name'].apply(clean_name)
"""

In [59]:
#final_2009_df

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,110683,"batista, miguel",2009,4267,CH,41,41,85.012195,-2.218537,5.706829,5.855133,-124.551149,-1.272244,-7.955195,26.476366,-27.023293,54.5
1,110683,"batista, miguel",2009,4267,CU,22,22,78.181818,-2.452727,5.734091,4.520884,-114.570196,-0.254067,4.821545,20.927591,-30.535500,54.5
2,110683,"batista, miguel",2009,4267,FF,137,137,93.719708,-2.247007,5.639781,6.880657,-137.275166,-3.722603,-7.989927,31.474693,-15.681956,54.5
3,110683,"batista, miguel",2009,4267,IN,1,1,53.500000,-2.340000,7.130000,-6.899020,-78.119736,4.971030,1.072000,11.680000,-27.760000,54.5
4,110683,"batista, miguel",2009,4267,SI,652,652,93.240031,-2.178834,5.575031,7.831769,-136.577136,-3.124205,-16.850879,31.951578,-21.594371,54.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1579,519455,"zimmermann, jordan",2009,6204,SL,248,248,86.192339,-2.075968,5.774960,4.629122,-126.239399,-1.572362,4.630371,23.980105,-28.553698,54.5
1580,543339,"hudson, daniel",2009,1144,CH,63,63,84.504762,-2.669683,5.010635,8.794285,-123.684311,-1.079443,-16.393984,25.872667,-26.518984,54.5
1581,543339,"hudson, daniel",2009,1144,CU,7,7,74.614286,-1.985714,5.717143,5.478231,-109.339602,0.932781,1.708000,19.771286,-32.701714,54.5
1582,543339,"hudson, daniel",2009,1144,FF,200,200,94.038500,-2.793500,5.024450,9.915154,-137.548811,-2.881965,-14.649815,30.972195,-15.124185,54.5
1583,543339,"hudson, daniel",2009,1144,SL,47,47,84.963830,-2.614681,5.405319,6.982745,-124.400905,-1.464148,-1.748787,24.961830,-26.658362,54.5

In [60]:
"""
# Convert 'player_name' from "last name, first name" to "first name last name"
final_2009_df['Name'] = final_2009_df['player_name'].apply(lambda x: ' '.join(x.split(', ')[::-1]))
"""

In [61]:
#final_2009_df

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg,Name
0,110683,"batista, miguel",2009,4267,CH,41,41,85.012195,-2.218537,5.706829,5.855133,-124.551149,-1.272244,-7.955195,26.476366,-27.023293,54.5,miguel batista
1,110683,"batista, miguel",2009,4267,CU,22,22,78.181818,-2.452727,5.734091,4.520884,-114.570196,-0.254067,4.821545,20.927591,-30.535500,54.5,miguel batista
2,110683,"batista, miguel",2009,4267,FF,137,137,93.719708,-2.247007,5.639781,6.880657,-137.275166,-3.722603,-7.989927,31.474693,-15.681956,54.5,miguel batista
3,110683,"batista, miguel",2009,4267,IN,1,1,53.500000,-2.340000,7.130000,-6.899020,-78.119736,4.971030,1.072000,11.680000,-27.760000,54.5,miguel batista
4,110683,"batista, miguel",2009,4267,SI,652,652,93.240031,-2.178834,5.575031,7.831769,-136.577136,-3.124205,-16.850879,31.951578,-21.594371,54.5,miguel batista
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1579,519455,"zimmermann, jordan",2009,6204,SL,248,248,86.192339,-2.075968,5.774960,4.629122,-126.239399,-1.572362,4.630371,23.980105,-28.553698,54.5,jordan zimmermann
1580,543339,"hudson, daniel",2009,1144,CH,63,63,84.504762,-2.669683,5.010635,8.794285,-123.684311,-1.079443,-16.393984,25.872667,-26.518984,54.5,daniel hudson
1581,543339,"hudson, daniel",2009,1144,CU,7,7,74.614286,-1.985714,5.717143,5.478231,-109.339602,0.932781,1.708000,19.771286,-32.701714,54.5,daniel hudson
1582,543339,"hudson, daniel",2009,1144,FF,200,200,94.038500,-2.793500,5.024450,9.915154,-137.548811,-2.881965,-14.649815,30.972195,-15.124185,54.5,daniel hudson
1583,543339,"hudson, daniel",2009,1144,SL,47,47,84.963830,-2.614681,5.405319,6.982745,-124.400905,-1.464148,-1.748787,24.961830,-26.658362,54.5,daniel hudson

In [62]:
"""
# Now, you can perform the merge using 'Name' and 'season' as the keys for both DataFrames
better_2009_df = pd.merge(final_2009_df, 
                          cleaning_filtered_df[['Name', 'season', 'Age']],
                          on=['Name', 'season'],
                          how='left')
"""

In [63]:
#better_2009_df

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg,Name,Age
0,110683,"batista, miguel",2009,4267,CH,41,41,85.012195,-2.218537,5.706829,5.855133,-124.551149,-1.272244,-7.955195,26.476366,-27.023293,54.5,miguel batista,NaN
1,110683,"batista, miguel",2009,4267,CU,22,22,78.181818,-2.452727,5.734091,4.520884,-114.570196,-0.254067,4.821545,20.927591,-30.535500,54.5,miguel batista,NaN
2,110683,"batista, miguel",2009,4267,FF,137,137,93.719708,-2.247007,5.639781,6.880657,-137.275166,-3.722603,-7.989927,31.474693,-15.681956,54.5,miguel batista,NaN
3,110683,"batista, miguel",2009,4267,IN,1,1,53.500000,-2.340000,7.130000,-6.899020,-78.119736,4.971030,1.072000,11.680000,-27.760000,54.5,miguel batista,NaN
4,110683,"batista, miguel",2009,4267,SI,652,652,93.240031,-2.178834,5.575031,7.831769,-136.577136,-3.124205,-16.850879,31.951578,-21.594371,54.5,miguel batista,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1604,519455,"zimmermann, jordan",2009,6204,SL,248,248,86.192339,-2.075968,5.774960,4.629122,-126.239399,-1.572362,4.630371,23.980105,-28.553698,54.5,jordan zimmermann,23.0
1605,543339,"hudson, daniel",2009,1144,CH,63,63,84.504762,-2.669683,5.010635,8.794285,-123.684311,-1.079443,-16.393984,25.872667,-26.518984,54.5,daniel hudson,22.0
1606,543339,"hudson, daniel",2009,1144,CU,7,7,74.614286,-1.985714,5.717143,5.478231,-109.339602,0.932781,1.708000,19.771286,-32.701714,54.5,daniel hudson,22.0
1607,543339,"hudson, daniel",2009,1144,FF,200,200,94.038500,-2.793500,5.024450,9.915154,-137.548811,-2.881965,-14.649815,30.972195,-15.124185,54.5,daniel hudson,22.0
1608,543339,"hudson, daniel",2009,1144,SL,47,47,84.963830,-2.614681,5.405319,6.982745,-124.400905,-1.464148,-1.748787,24.961830,-26.658362,54.5,daniel hudson,22.0

In [64]:
#better_2009_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1609 entries, 0 to 1608
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   pitcher                           1609 non-null   int64
 1   player_name                       1609 non-null   object
 2   season                            1609 non-null   int32
 3   season_total_pitches              1609 non-null   int64
 4   pitch_type                        1609 non-null   object
 5   season_total_count_by_pitch_type  1609 non-null   int64
 6   count_by_pitch_type               1609 non-null   int64
 7   release_speed_weighted_avg        1609 non-null   float64
 8   release_pos_x_weighted_avg        1609 non-null   float64
 9   release_pos_z_weighted_avg        1609 non-null   float64
 10  vx0_weighted_avg                  1609 non-null   float64
 11  vy0_weighted_avg                  1609 non-null   float64
 12  vz0_weighted_avg                  1609 non-null   float64
 13  ax_weighted_avg                   1609 non-null   float64
 14  ay_weighted_avg                   1609 non-null   float64
 15  az_weighted_avg                   1609 non-null   float64
 16  release_pos_y_weighted_avg        1609 non-null   float64
 17  Name                              1609 non-null   object
 18  Age                               1384 non-null   float64
dtypes: float64(11), int32(1), int64(4), object(3)
memory usage: 232.7+ KB

In [65]:
#better_2009_df.to_csv('data/better_2009_df.csv')

2011

In [84]:
#all_2011_stats_df = pd.read_csv('~/Documents/Flatiron/Project_5_/data/all_2011_stats_df.csv', index_col=0)

In [85]:
"""
all_2011_stats_df.drop(columns=['batter', 'events', 'description', 'zone',
                                'des', 'game_type', 'stand', 'home_team',
                                'away_team', 'type', 'hit_location', 'bb_type',
                                'balls', 'strikes', 'pfx_x', 'spin_dir', 
                                'pfx_z', 'plate_x', 'plate_z', 'on_3b',
                                'on_2b', 'on_1b', 'outs_when_up', 'inning',
                                'inning_topbot', 'hc_x', 'hc_y', 'fielder_2',
                                'umpire', 'sv_id', 'hit_distance_sc', 'sz_top',
                                 'sz_bot', 'launch_speed', 'launch_angle', 'game_pk',
                                'pitcher.1', 'fielder_2.1', 'fielder_3', 'fielder_4',
                                'fielder_5', 'fielder_6', 'fielder_7', 'fielder_8',
                                'fielder_9', 'estimated_ba_using_speedangle',
                                'estimated_woba_using_speedangle', 'babip_value',
                                'launch_speed_angle', 'woba_value', 'woba_denom', 'iso_value', 
                                'at_bat_number', 'pitch_number', 'home_score', 'away_score',
                                'bat_score', 'fld_score', 'post_home_score', 'post_bat_score',
                                'post_fld_score', 'post_away_score', 'if_fielding_alignment',
                                'of_fielding_alignment', 'delta_home_win_exp',
                                'delta_run_exp', 'spin_rate_deprecated', 'break_angle_deprecated',
                               'break_length_deprecated', 'tfs_deprecated', 'tfs_zulu_deprecated'], inplace=True)
all_2011_stats_df.head()
"""

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,...,vz0,ax,ay,az,effective_speed,release_spin_rate,release_extension,release_pos_y,pitch_name,spin_axis
0,FF,2011-09-27,87.0,2.22,6.16,"Rhodes, Arthur",121125,L,2011,-5.688134,...,-1.647750,11.529,27.025,-15.713,NaN,NaN,NaN,54.5,4-Seam Fastball,NaN
1,FF,2011-09-27,89.6,2.09,6.15,"Rhodes, Arthur",121125,L,2011,-11.935734,...,-7.225282,15.735,27.692,-16.458,NaN,NaN,NaN,54.5,4-Seam Fastball,NaN
2,FF,2011-09-27,86.8,2.11,6.21,"Rhodes, Arthur",121125,L,2011,-9.846678,...,-3.098437,10.612,25.057,-15.554,NaN,NaN,NaN,54.5,4-Seam Fastball,NaN
3,FF,2011-09-27,87.3,2.11,6.15,"Rhodes, Arthur",121125,L,2011,-9.395379,...,-6.733056,12.094,26.656,-16.740,NaN,NaN,NaN,54.5,4-Seam Fastball,NaN
4,FF,2011-09-27,87.9,2.08,6.22,"Rhodes, Arthur",121125,L,2011,-10.489527,...,-6.848008,14.422,26.080,-16.879,NaN,NaN,NaN,54.5,4-Seam Fastball,NaN

In [86]:
"""
all_2011_stats_df.drop(columns=['spin_axis', 'effective_speed',
                               'release_spin_rate', 'release_extension'], inplace=True)
all_2011_stats_df.head()
"""

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,vy0,vz0,ax,ay,az,release_pos_y,pitch_name
0,FF,2011-09-27,87.0,2.22,6.16,"Rhodes, Arthur",121125,L,2011,-5.688134,-127.594702,-1.647750,11.529,27.025,-15.713,54.5,4-Seam Fastball
1,FF,2011-09-27,89.6,2.09,6.15,"Rhodes, Arthur",121125,L,2011,-11.935734,-130.702917,-7.225282,15.735,27.692,-16.458,54.5,4-Seam Fastball
2,FF,2011-09-27,86.8,2.11,6.21,"Rhodes, Arthur",121125,L,2011,-9.846678,-126.886772,-3.098437,10.612,25.057,-15.554,54.5,4-Seam Fastball
3,FF,2011-09-27,87.3,2.11,6.15,"Rhodes, Arthur",121125,L,2011,-9.395379,-127.516176,-6.733056,12.094,26.656,-16.740,54.5,4-Seam Fastball
4,FF,2011-09-27,87.9,2.08,6.22,"Rhodes, Arthur",121125,L,2011,-10.489527,-128.331786,-6.848008,14.422,26.080,-16.879,54.5,4-Seam Fastball

In [87]:
#all_2011_stats_df = all_2011_stats_df.dropna(axis=0)

In [88]:
#all_2011_stats_df.reset_index(inplace=True)

In [89]:
#all_2011_stats_df.drop('index', axis=1)

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,vy0,vz0,ax,ay,az,release_pos_y,pitch_name
0,FF,2011-09-27,87.0,2.22,6.16,"Rhodes, Arthur",121125,L,2011,-5.688134,-127.594702,-1.647750,11.529,27.025,-15.713,54.5,4-Seam Fastball
1,FF,2011-09-27,89.6,2.09,6.15,"Rhodes, Arthur",121125,L,2011,-11.935734,-130.702917,-7.225282,15.735,27.692,-16.458,54.5,4-Seam Fastball
2,FF,2011-09-27,86.8,2.11,6.21,"Rhodes, Arthur",121125,L,2011,-9.846678,-126.886772,-3.098437,10.612,25.057,-15.554,54.5,4-Seam Fastball
3,FF,2011-09-27,87.3,2.11,6.15,"Rhodes, Arthur",121125,L,2011,-9.395379,-127.516176,-6.733056,12.094,26.656,-16.740,54.5,4-Seam Fastball
4,FF,2011-09-27,87.9,2.08,6.22,"Rhodes, Arthur",121125,L,2011,-10.489527,-128.331786,-6.848008,14.422,26.080,-16.879,54.5,4-Seam Fastball
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
463711,FF,2011-03-31,96.2,-2.03,6.66,"Verlander, Justin",434378,R,2011,8.941077,-140.745856,-9.097226,-17.066,38.918,-5.193,54.5,4-Seam Fastball
463712,FF,2011-03-31,94.9,-2.09,6.65,"Verlander, Justin",434378,R,2011,9.117600,-138.923387,-9.648657,-17.954,44.298,-6.245,54.5,4-Seam Fastball
463713,FF,2011-03-31,95.1,-2.03,6.69,"Verlander, Justin",434378,R,2011,13.991058,-138.643149,-10.730799,-20.735,38.404,-9.514,54.5,4-Seam Fastball
463714,FF,2011-03-31,94.8,-2.18,6.69,"Verlander, Justin",434378,R,2011,12.191019,-138.607176,-7.217559,-21.764,41.080,-7.738,54.5,4-Seam Fastball
463715,FF,2011-03-31,93.3,-2.33,6.79,"Verlander, Justin",434378,R,2011,9.219349,-136.331521,-10.137328,-17.815,32.275,-6.961,54.5,4-Seam Fastball

In [90]:
"""
# Group by 'game_date' and 'pitcher' to calculate the total pitches
total_pitches = all_2011_stats_df.groupby(['game_date', 'pitcher', 'player_name']).size().reset_index(name='total_pitches')

# Group by 'game_date', 'pitcher', and 'pitch_type' to calculate the sum total of each pitch_type
total_pitches_by_type = all_2011_stats_df.groupby(['game_date', 'pitcher', 'player_name', 'pitch_type']).size().reset_index(name='count_by_pitch_type')

# Calculate averages of the specified metrics for each pitch type, grouped by game_date and pitcher
avg_metrics = all_2011_stats_df.groupby(['game_date', 'pitcher', 'player_name', 'pitch_type']).agg({
    'release_speed': 'mean',
    'release_pos_x': 'mean',
    'release_pos_z': 'mean',
    'vx0': 'mean',
    'vy0': 'mean',
    'vz0': 'mean',
    'ax': 'mean',
    'ay': 'mean',
    'az': 'mean',
    'release_pos_y': 'mean',
}).reset_index()

grouped_2011_df = total_pitches.merge(total_pitches_by_type, on=['game_date', 'pitcher', 'player_name'], how='left')
grouped_2011_df = grouped_2011_df.merge(avg_metrics, on=['game_date', 'pitcher', 'player_name', 'pitch_type'], how='left')

grouped_2011_df
"""

,game_date,pitcher,player_name,total_pitches,pitch_type,count_by_pitch_type,release_speed,release_pos_x,release_pos_z,vx0,vy0,vz0,ax,ay,az,release_pos_y
0,2011-03-31,110683,"Batista, Miguel",24,CH,3,86.066667,-1.273333,6.090000,2.571380,-125.993665,-4.896420,-4.355000,25.299000,-24.310667,54.5
1,2011-03-31,110683,"Batista, Miguel",24,FC,1,89.500000,-1.510000,5.810000,2.922801,-131.395686,-1.597612,2.042000,28.876000,-20.897000,54.5
2,2011-03-31,110683,"Batista, Miguel",24,FF,3,93.000000,-1.236667,5.873333,3.487754,-136.535839,-2.813663,-6.485000,32.659667,-15.000333,54.5
3,2011-03-31,110683,"Batista, Miguel",24,SI,16,92.550000,-1.341250,5.826875,5.827468,-135.609434,-5.501494,-19.408938,31.531312,-20.081563,54.5
4,2011-03-31,110683,"Batista, Miguel",24,SL,1,85.900000,-1.480000,6.030000,4.839078,-125.736343,-6.835864,6.624000,25.150000,-23.084000,54.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28227,2011-09-28,572070,"Richards, Garrett",71,CH,7,86.457143,-2.702857,6.117143,6.682821,-126.594985,-4.371526,-11.541429,27.003286,-21.375571,54.5
28228,2011-09-28,572070,"Richards, Garrett",71,FC,8,94.312500,-2.546250,6.172500,5.085571,-138.073422,-1.848205,1.707375,29.037250,-20.733625,54.5
28229,2011-09-28,572070,"Richards, Garrett",71,FF,21,94.838095,-2.517619,6.167143,7.870597,-138.691992,-5.262649,-3.067905,29.946476,-18.261905,54.5
28230,2011-09-28,572070,"Richards, Garrett",71,SI,15,94.360000,-2.555333,6.138667,7.439816,-138.118700,-4.298928,-12.053067,31.114667,-23.406000,54.5
28231,2011-09-28,572070,"Richards, Garrett",71,SL,20,85.620000,-2.654500,6.106000,5.669194,-125.360559,-1.248440,3.422900,24.455700,-35.978850,54.5

In [91]:
"""
grouped_2011_df['game_date'] = pd.to_datetime(grouped_2011_df['game_date'])
grouped_2011_df['season'] = grouped_2011_df['game_date'].dt.year

# Step 1: Season Total Pitches
season_total_pitches = grouped_2011_df.groupby(['pitcher', 'player_name', 'season'])['total_pitches'].sum().reset_index(name='season_total_pitches')

# Step 2: Season Total by Pitch Type
season_total_by_pitch_type = grouped_2011_df.groupby(['pitcher', 'player_name', 'season', 'pitch_type'])['count_by_pitch_type'].sum().reset_index(name='season_total_count_by_pitch_type')

# Weighted Averages Calculation Setup
weighted_avg_columns = ['release_speed', 'release_pos_x', 'release_pos_z', 'vx0', 'vy0', 'vz0', 'ax', 'ay', 'az', 'release_pos_y']
for col in weighted_avg_columns:
    grouped_2011_df[f'{col}_product'] = grouped_2011_df[col] * grouped_2011_df['count_by_pitch_type']

weighted_avg_aggregations = {f'{col}_product': 'sum' for col in weighted_avg_columns}
weighted_avg_aggregations['count_by_pitch_type'] = 'sum'

# Aggregate for weighted averages
weighted_avg_df = grouped_2011_df.groupby(['pitcher', 'player_name', 'season', 'pitch_type']).agg(weighted_avg_aggregations).reset_index()

# Calculate weighted averages
for col in weighted_avg_columns:
    weighted_avg_df[f'{col}_weighted_avg'] = weighted_avg_df[f'{col}_product'] / weighted_avg_df['count_by_pitch_type']

# Cleanup
weighted_avg_df.drop(columns=[f'{col}_product' for col in weighted_avg_columns], inplace=True)

# Merge season totals and weighted averages
final_2011_df = pd.merge(season_total_pitches, season_total_by_pitch_type, on=['pitcher', 'player_name', 'season'])
final_2011_df = pd.merge(final_2011_df, weighted_avg_df, on=['pitcher', 'player_name', 'season', 'pitch_type'])

final_2011_df.head()
"""

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,110683,"Batista, Miguel",2011,3944,CH,32,32,83.093750,-1.453125,5.795625,3.385733,-121.694662,-2.036573,-7.091812,22.816406,-26.164969,54.5
1,110683,"Batista, Miguel",2011,3944,CU,7,7,76.885714,-1.605714,5.911429,2.269082,-112.607261,-2.271918,6.512857,18.124429,-32.510286,54.5
2,110683,"Batista, Miguel",2011,3944,FC,1,1,89.500000,-1.510000,5.810000,2.922801,-131.395686,-1.597612,2.042000,28.876000,-20.897000,54.5
3,110683,"Batista, Miguel",2011,3944,FF,233,233,92.585408,-1.467811,5.773777,4.982364,-135.628448,-4.244348,-4.100910,29.086549,-16.734481,54.5
4,110683,"Batista, Miguel",2011,3944,IN,18,18,52.594444,-1.621111,6.832222,-2.265764,-76.761205,7.108895,0.803500,9.425722,-29.463833,54.5

In [92]:
"""
final_2011_df['player_name'] = final_2011_df['player_name'].str.lower().str.strip().str.replace(r'\*$', '', regex=True)
final_2011_df
"""

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,110683,"batista, miguel",2011,3944,CH,32,32,83.093750,-1.453125,5.795625,3.385733,-121.694662,-2.036573,-7.091812,22.816406,-26.164969,54.5
1,110683,"batista, miguel",2011,3944,CU,7,7,76.885714,-1.605714,5.911429,2.269082,-112.607261,-2.271918,6.512857,18.124429,-32.510286,54.5
2,110683,"batista, miguel",2011,3944,FC,1,1,89.500000,-1.510000,5.810000,2.922801,-131.395686,-1.597612,2.042000,28.876000,-20.897000,54.5
3,110683,"batista, miguel",2011,3944,FF,233,233,92.585408,-1.467811,5.773777,4.982364,-135.628448,-4.244348,-4.100910,29.086549,-16.734481,54.5
4,110683,"batista, miguel",2011,3944,IN,18,18,52.594444,-1.621111,6.832222,-2.265764,-76.761205,7.108895,0.803500,9.425722,-29.463833,54.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1593,572070,"richards, garrett",2011,1268,FC,17,17,95.135294,-2.451765,6.066471,5.668013,-139.254525,-2.720391,2.342647,29.178059,-20.838824,54.5
1594,572070,"richards, garrett",2011,1268,FF,63,63,95.393651,-2.408730,6.051270,7.286500,-139.529940,-4.856536,-3.356556,29.854873,-18.058079,54.5
1595,572070,"richards, garrett",2011,1268,PO,1,1,91.900000,-2.220000,6.100000,10.631552,-134.417282,-1.445604,-7.636000,28.552000,-19.150000,54.5
1596,572070,"richards, garrett",2011,1268,SI,73,73,94.993151,-2.541096,5.966575,7.715733,-138.962108,-4.629207,-11.922959,29.854301,-22.851205,54.5
1597,572070,"richards, garrett",2011,1268,SL,85,85,86.341176,-2.553882,5.999647,5.213688,-126.443739,-1.284561,4.125671,24.344165,-35.387094,54.5

In [93]:
#print(final_2011_df['player_name'].unique())

['batista, miguel' 'carpenter, chris' 'colon, bartolo' 'hawkins, latroy'
 'hernandez, livan' 'isringhausen, jason' 'lowe, derek' 'millwood, kevin'
 'oliver, darren' 'reyes, dennys' 'rhodes, arthur' 'tomko, brett'
 'wakefield, tim' 'wright, jamey' 'dempster, ryan' 'wood, kerry'
 'vazquez, javier' 'pavano, carl' 'chen, bruce' 'halladay, roy'
 'ortiz, ramon' 'wolf, randy' 'figueroa, nelson' 'nathan, joe'
 'davis, doug' 'marquis, jason' 'burnett, a.j.' 'lilly, ted'
 'westbrook, jake' 'lopez, rodrigo' 'penny, brad' 'franklin, ryan'
 'zito, barry' 'hudson, tim' 'padilla, vicente' 'durbin, chad'
 'downs, scott' 'arroyo, bronson' 'benoit, joaquÃ­n' 'beckett, josh'
 'belisle, matt' 'garland, jon' 'buehrle, mark' 'sabathia, cc'
 'vogelsong, ryan' 'dickey, r.a.' 'pineiro, joel' 'affeldt, jeremy'
 'lohse, kyle' 'cook, aaron' 'oswalt, roy' 'ramirez, horacio'
 'moseley, dustin' 'zambrano, carlos' 'lackey, john' 'de la rosa, jorge'
 'bedard, erik' 'lewis, colby' 'myers, brett' 'peavy, jake'
 'harang, aaron' 'hendrickson, mark' 'tallet, brian' 'guthrie, jeremy'
 'wang, chien-ming' 'williams, jerome' 'kuo, hung-chih' 'capuano, chris'
 'carrasco, d.j.' 'ledezma, wilfredo' 'contreras, jose' 'greinke, zack'
 'harden, rich' 'floyd, gavin' 'willis, dontrelle' 'haren, dan'
 'jackson, edwin' 'santana, ervin' 'narveson, chris' 'correia, kevin'
 'mitre, sergio' 'gaudin, chad' 'simon, alfredo' 'blanton, joe'
 'mcgowan, dustin' 'germano, justin' 'maholm, paul' 'cain, matt'
 'hamels, cole' 'kazmir, scott' 'stauffer, tim' 'young, chris'
 'danks, john' 'hernandez, roberto' 'francis, jeff' 'hernÃ¡ndez, fÃ©lix'
 'bush, dave' 'loe, kameron' 'verlander, justin' 'liriano, francisco'
 'tejeda, robinson' 'saunders, joe' 'jimÃ©nez, ubaldo' 'hammel, jason'
 'burres, brian' 'rodriguez, wandy' 'mendoza, luis' 'sÃ¡nchez, anÃ­bal'
 'davies, kyle' 'duke, zach' 'mccarthy, brandon' 'niemann, jeff'
 'karstens, jeff' 'laffey, aaron' 'feldman, scott' 'nolasco, ricky'
 'marshall, sean' 'stults, eric' 'chavez, jesse' 'eveland, dana'
 'litsch, jesse' 'detwiler, ross' 'kluber, corey' 'cecil, brett'
 'blackburn, nick' 'hill, rich' 'bergesen, brad' 'shields, james'
 'wells, randy' 'garcÃ­a, jaime' 'harrell, lucas' 'volquez, edinson'
 'vargas, jason' 'weaver, jered' 'wilson, c.j.' 'medlen, kris'
 'fister, doug' 'matusz, brian' 'galarraga, armando' 'billingsley, chad'
 'davis, wade' 'gallardo, yovani' 'marcum, shaun' 'owings, micah'
 'lester, jon' 'kendrick, kyle' 'gorzelanny, tom' 'kennedy, ian'
 'miller, andrew' 'leblanc, wade' 'scherzer, max' 'huff, david'
 'lincecum, tim' 'buchholz, clay' 'morrow, brandon' 'richard, clayton'
 'arrieta, jake' 'villanueva, carlos' 'hensley, clay' 'ohlendorf, ross'
 'price, david' 'sÃ¡nchez, jonathan' 'noesÃ­, hector' 'cueto, johnny'
 'bailey, homer' 'harrison, matt' 'jurrjens, jair' 'reyes, jo-jo'
 "o'sullivan, sean" 'happ, j.a.' 'luebke, cory' 'sonnanstine, andy'
 'lynn, lance' 'volstad, chris' 'tomlin, josh' 'lannan, john'
 'slowey, kevin' 'humber, philip' 'hochevar, luke' 'pelfrey, mike'
 'romero, ricky' 'braden, dallas' 'gonzÃ¡lez, gio' 'hughes, phil'
 'swarzak, anthony' 'hanson, tommy' 'estrada, marco' 'paulino, felipe'
 'morales, franklin' 'doubront, felix' 'nova, ivÃ¡n' 'ogando, alexi'
 'chacÃ­n, jhoulys' 'rogers, esmil' 'carrasco, carlos' 'anderson, brett'
 'worley, vance' 'ross, tyson' 'drabek, kyle' 'wood, travis'
 'masterson, justin' 'hellickson, jeremy' 'niese, jonathon'
 'kershaw, clayton' 'cashner, andrew' 'duensing, brian' 'hunter, tommy'
 'miley, wade' 'stammen, craig' 'garza, matt' 'kuroda, hiroki'
 'matsuzaka, daisuke' 'pineda, michael' 'tillman, chris' 'minor, mike'
 'latos, mat' 'norris, bud' 'locke, jeff' 'mcallister, zach' 'cobb, alex'
 'samardzija, jeff' 'leake, mike' 'cahill, trevor' 'santiago, hÃ©ctor'
 'holland, derek' 'peacock, brad' 'nicasio, juan' 'alvarez iii, henderson'
 'delgado, randall' 'bumgarner, madison' 'collmenter, josh' 'duffy, danny'
 'gee, dillon' 'moore, matt' 'parker, jarrod' 'pomeranz, drew'
 'porcello, rick' 'sale, chris' 'zimmermann, jordan' 'de la rosa, rubby'
 'teheran, julio' 'diamond, scott' 'chatwood, tyler' 'eovaldi, nathan'
 'hudson, daniel' 'lyles, jordan' 'milone, tommy' 'strasburg, stephen'
 'turner, jacob' 'beachy, brandon' 'fiers, mike' 'richards, garrett']

In [94]:
"""
def remove_accents(input_str):
    nfkd_form = unicodedata.normalize('NFKD', input_str)
    return "".join([c for c in nfkd_form if not unicodedata.combining(c)])

def clean_name(name):
    name = name.lower()
    name = remove_accents(name)
    name = re.sub(r'[-.]', '', name)
    name = re.sub(r'\s+', ' ', name).strip()
    return name

final_2011_df['player_name'] = final_2011_df['player_name'].apply(clean_name)
"""

In [95]:
"""
# Convert 'player_name' from "last name, first name" to "first name last name"
final_2011_df['Name'] = final_2011_df['player_name'].apply(lambda x: ' '.join(x.split(', ')[::-1]))
"""

In [96]:
"""
# Now, you can perform the merge using 'Name' and 'season' as the keys for both DataFrames
better_2011_df = pd.merge(final_2011_df, 
                          cleaning_filtered_df[['Name', 'season', 'Age']],
                          on=['Name', 'season'],
                          how='left')
"""

In [114]:
#better_2011_df

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg,Name,Age
0,110683,"batista, miguel",2011,3944,CH,32,32,83.093750,-1.453125,5.795625,3.385733,-121.694662,-2.036573,-7.091812,22.816406,-26.164969,54.5,miguel batista,40.0
1,110683,"batista, miguel",2011,3944,CU,7,7,76.885714,-1.605714,5.911429,2.269082,-112.607261,-2.271918,6.512857,18.124429,-32.510286,54.5,miguel batista,40.0
2,110683,"batista, miguel",2011,3944,FC,1,1,89.500000,-1.510000,5.810000,2.922801,-131.395686,-1.597612,2.042000,28.876000,-20.897000,54.5,miguel batista,40.0
3,110683,"batista, miguel",2011,3944,FF,233,233,92.585408,-1.467811,5.773777,4.982364,-135.628448,-4.244348,-4.100910,29.086549,-16.734481,54.5,miguel batista,40.0
4,110683,"batista, miguel",2011,3944,IN,18,18,52.594444,-1.621111,6.832222,-2.265764,-76.761205,7.108895,0.803500,9.425722,-29.463833,54.5,miguel batista,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1612,572070,"richards, garrett",2011,1268,FC,17,17,95.135294,-2.451765,6.066471,5.668013,-139.254525,-2.720391,2.342647,29.178059,-20.838824,54.5,garrett richards,23.0
1613,572070,"richards, garrett",2011,1268,FF,63,63,95.393651,-2.408730,6.051270,7.286500,-139.529940,-4.856536,-3.356556,29.854873,-18.058079,54.5,garrett richards,23.0
1614,572070,"richards, garrett",2011,1268,PO,1,1,91.900000,-2.220000,6.100000,10.631552,-134.417282,-1.445604,-7.636000,28.552000,-19.150000,54.5,garrett richards,23.0
1615,572070,"richards, garrett",2011,1268,SI,73,73,94.993151,-2.541096,5.966575,7.715733,-138.962108,-4.629207,-11.922959,29.854301,-22.851205,54.5,garrett richards,23.0
1616,572070,"richards, garrett",2011,1268,SL,85,85,86.341176,-2.553882,5.999647,5.213688,-126.443739,-1.284561,4.125671,24.344165,-35.387094,54.5,garrett richards,23.0

In [115]:
#better_2011_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1617 entries, 0 to 1616
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   pitcher                           1617 non-null   int64
 1   player_name                       1617 non-null   object
 2   season                            1617 non-null   int32
 3   season_total_pitches              1617 non-null   int64
 4   pitch_type                        1617 non-null   object
 5   season_total_count_by_pitch_type  1617 non-null   int64
 6   count_by_pitch_type               1617 non-null   int64
 7   release_speed_weighted_avg        1617 non-null   float64
 8   release_pos_x_weighted_avg        1617 non-null   float64
 9   release_pos_z_weighted_avg        1617 non-null   float64
 10  vx0_weighted_avg                  1617 non-null   float64
 11  vy0_weighted_avg                  1617 non-null   float64
 12  vz0_weighted_avg                  1617 non-null   float64
 13  ax_weighted_avg                   1617 non-null   float64
 14  ay_weighted_avg                   1617 non-null   float64
 15  az_weighted_avg                   1617 non-null   float64
 16  release_pos_y_weighted_avg        1617 non-null   float64
 17  Name                              1617 non-null   object
 18  Age                               1384 non-null   float64
dtypes: float64(11), int32(1), int64(4), object(3)
memory usage: 233.8+ KB

In [99]:
#better_2011_df.to_csv('data/better_2011_df.csv')

2012

In [100]:
#all_2012_stats_df = pd.read_csv('~/Documents/Flatiron/Project_5_/data/all_2012_stats_df.csv', index_col=0)

In [101]:
"""
all_2012_stats_df.drop(columns=['batter', 'events', 'description', 'zone',
                                'des', 'game_type', 'stand', 'home_team',
                                'away_team', 'type', 'hit_location', 'bb_type',
                                'balls', 'strikes', 'pfx_x', 'spin_dir', 
                                'pfx_z', 'plate_x', 'plate_z', 'on_3b',
                                'on_2b', 'on_1b', 'outs_when_up', 'inning',
                                'inning_topbot', 'hc_x', 'hc_y', 'fielder_2',
                                'umpire', 'sv_id', 'hit_distance_sc', 'sz_top',
                                 'sz_bot', 'launch_speed', 'launch_angle', 'game_pk',
                                'pitcher.1', 'fielder_2.1', 'fielder_3', 'fielder_4',
                                'fielder_5', 'fielder_6', 'fielder_7', 'fielder_8',
                                'fielder_9', 'estimated_ba_using_speedangle',
                                'estimated_woba_using_speedangle', 'babip_value',
                                'launch_speed_angle', 'woba_value', 'woba_denom', 'iso_value', 
                                'at_bat_number', 'pitch_number', 'home_score', 'away_score',
                                'bat_score', 'fld_score', 'post_home_score', 'post_bat_score',
                                'post_fld_score', 'post_away_score', 'if_fielding_alignment',
                                'of_fielding_alignment', 'delta_home_win_exp',
                                'delta_run_exp', 'spin_rate_deprecated', 'break_angle_deprecated',
                               'break_length_deprecated', 'tfs_deprecated', 'tfs_zulu_deprecated'], inplace=True)
all_2012_stats_df.head()
"""

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,...,vz0,ax,ay,az,effective_speed,release_spin_rate,release_extension,release_pos_y,pitch_name,spin_axis
0,FF,2012-09-30,92.5,-2.02,6.22,"Hawkins, LaTroy",115629,R,2012,6.289808,...,-4.812941,-12.660,26.855,-18.100,NaN,NaN,NaN,54.5,4-Seam Fastball,NaN
1,SL,2012-09-30,84.2,-2.23,6.31,"Hawkins, LaTroy",115629,R,2012,5.559747,...,0.532282,1.945,19.713,-30.444,NaN,NaN,NaN,54.5,Slider,NaN
2,CU,2012-09-30,76.2,-1.94,6.59,"Hawkins, LaTroy",115629,R,2012,4.539201,...,-0.422794,3.262,19.851,-40.570,NaN,NaN,NaN,54.5,Curveball,NaN
3,FF,2012-09-30,91.8,-1.97,6.56,"Hawkins, LaTroy",115629,R,2012,8.856808,...,-4.061543,-14.234,23.119,-14.283,NaN,NaN,NaN,54.5,4-Seam Fastball,NaN
4,CU,2012-09-30,74.7,-1.83,6.68,"Hawkins, LaTroy",115629,R,2012,2.280810,...,4.102313,5.411,17.962,-41.901,NaN,NaN,NaN,54.5,Curveball,NaN

In [102]:
"""
all_2012_stats_df.drop(columns=['spin_axis', 'effective_speed',
                               'release_spin_rate', 'release_extension'], inplace=True)
all_2012_stats_df.head()
"""

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,vy0,vz0,ax,ay,az,release_pos_y,pitch_name
0,FF,2012-09-30,92.5,-2.02,6.22,"Hawkins, LaTroy",115629,R,2012,6.289808,-135.508760,-4.812941,-12.660,26.855,-18.100,54.5,4-Seam Fastball
1,SL,2012-09-30,84.2,-2.23,6.31,"Hawkins, LaTroy",115629,R,2012,5.559747,-123.198164,0.532282,1.945,19.713,-30.444,54.5,Slider
2,CU,2012-09-30,76.2,-1.94,6.59,"Hawkins, LaTroy",115629,R,2012,4.539201,-111.775068,-0.422794,3.262,19.851,-40.570,54.5,Curveball
3,FF,2012-09-30,91.8,-1.97,6.56,"Hawkins, LaTroy",115629,R,2012,8.856808,-134.164685,-4.061543,-14.234,23.119,-14.283,54.5,4-Seam Fastball
4,CU,2012-09-30,74.7,-1.83,6.68,"Hawkins, LaTroy",115629,R,2012,2.280810,-109.467888,4.102313,5.411,17.962,-41.901,54.5,Curveball

In [104]:
#all_2012_stats_df = all_2012_stats_df.dropna(axis=0)

In [105]:
#all_2012_stats_df.reset_index(inplace=True)

In [106]:
#all_2012_stats_df.drop('index', axis=1)

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,vy0,vz0,ax,ay,az,release_pos_y,pitch_name
0,FF,2012-09-30,92.5,-2.02,6.22,"Hawkins, LaTroy",115629,R,2012,6.289808,-135.508760,-4.812941,-12.660,26.855,-18.100,54.5,4-Seam Fastball
1,SL,2012-09-30,84.2,-2.23,6.31,"Hawkins, LaTroy",115629,R,2012,5.559747,-123.198164,0.532282,1.945,19.713,-30.444,54.5,Slider
2,CU,2012-09-30,76.2,-1.94,6.59,"Hawkins, LaTroy",115629,R,2012,4.539201,-111.775068,-0.422794,3.262,19.851,-40.570,54.5,Curveball
3,FF,2012-09-30,91.8,-1.97,6.56,"Hawkins, LaTroy",115629,R,2012,8.856808,-134.164685,-4.061543,-14.234,23.119,-14.283,54.5,4-Seam Fastball
4,CU,2012-09-30,74.7,-1.83,6.68,"Hawkins, LaTroy",115629,R,2012,2.280810,-109.467888,4.102313,5.411,17.962,-41.901,54.5,Curveball
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
463493,FC,2012-04-07,88.0,-1.35,6.47,"Wainwright, Adam",425794,R,2012,3.566735,-128.746992,-6.441785,1.804,24.551,-26.753,54.5,Cutter
463494,SI,2012-04-07,90.4,-1.58,6.17,"Wainwright, Adam",425794,R,2012,6.471949,-132.321396,-7.262328,-15.527,27.875,-21.408,54.5,Sinker
463495,CU,2012-04-07,73.7,-1.26,6.46,"Wainwright, Adam",425794,R,2012,1.945332,-108.279831,0.644129,12.926,23.804,-41.751,54.5,Curveball
463496,SI,2012-04-07,89.5,-1.54,6.32,"Wainwright, Adam",425794,R,2012,7.685348,-130.728003,-7.084711,-11.999,23.949,-18.542,54.5,Sinker
463497,SI,2012-04-07,91.1,-1.37,6.37,"Wainwright, Adam",425794,R,2012,2.623797,-133.708694,-3.530007,-17.041,31.303,-25.008,54.5,Sinker

In [107]:
"""
# Group by 'game_date' and 'pitcher' to calculate the total pitches
total_pitches = all_2012_stats_df.groupby(['game_date', 'pitcher', 'player_name']).size().reset_index(name='total_pitches')

# Group by 'game_date', 'pitcher', and 'pitch_type' to calculate the sum total of each pitch_type
total_pitches_by_type = all_2012_stats_df.groupby(['game_date', 'pitcher', 'player_name', 'pitch_type']).size().reset_index(name='count_by_pitch_type')

# Calculate averages of the specified metrics for each pitch type, grouped by game_date and pitcher
avg_metrics = all_2012_stats_df.groupby(['game_date', 'pitcher', 'player_name', 'pitch_type']).agg({
    'release_speed': 'mean',
    'release_pos_x': 'mean',
    'release_pos_z': 'mean',
    'vx0': 'mean',
    'vy0': 'mean',
    'vz0': 'mean',
    'ax': 'mean',
    'ay': 'mean',
    'az': 'mean',
    'release_pos_y': 'mean',
}).reset_index()

grouped_2012_df = total_pitches.merge(total_pitches_by_type, on=['game_date', 'pitcher', 'player_name'], how='left')
grouped_2012_df = grouped_2012_df.merge(avg_metrics, on=['game_date', 'pitcher', 'player_name', 'pitch_type'], how='left')

grouped_2012_df
"""

,game_date,pitcher,player_name,total_pitches,pitch_type,count_by_pitch_type,release_speed,release_pos_x,release_pos_z,vx0,vy0,vz0,ax,ay,az,release_pos_y
0,2012-03-28,460024,"Hochevar, Luke",80,CH,8,85.462500,-2.333750,6.272500,8.845641,-124.852815,-4.643140,-11.712875,22.087875,-25.259625,54.5
1,2012-03-28,460024,"Hochevar, Luke",80,CU,5,75.940000,-2.194000,6.476000,1.842147,-111.452514,3.466523,6.390000,21.133600,-42.476400,54.5
2,2012-03-28,460024,"Hochevar, Luke",80,FC,18,90.055556,-2.561667,6.163333,8.214348,-131.625239,-5.130524,0.511278,24.836500,-22.538333,54.5
3,2012-03-28,460024,"Hochevar, Luke",80,FF,18,93.366667,-2.441667,6.157222,8.743896,-136.557100,-4.029457,-12.135056,28.821722,-16.767278,54.5
4,2012-03-28,460024,"Hochevar, Luke",80,SI,22,93.759091,-2.492273,6.055455,10.245581,-136.954286,-5.226622,-17.713364,27.452773,-21.768364,54.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29680,2012-10-03,571946,"Miller, Shelby",72,CH,8,87.175000,-2.082500,5.383750,7.591697,-127.635963,-3.336358,-16.324625,26.642625,-22.452875,54.5
29681,2012-10-03,571946,"Miller, Shelby",72,CU,14,81.500000,-1.896429,5.442143,2.980629,-119.466927,1.641247,3.298643,23.100429,-36.457643,54.5
29682,2012-10-03,571946,"Miller, Shelby",72,FF,50,93.700000,-1.854800,5.462800,6.124624,-137.266176,-4.264278,-12.771760,31.523000,-14.926940,54.5
29683,2012-10-03,592767,"Smyly, Drew",19,KC,6,80.650000,1.553333,6.786667,-5.224581,-118.045275,-4.183731,3.514333,23.418500,-29.437500,54.5
29684,2012-10-03,592767,"Smyly, Drew",19,SI,13,92.423077,1.163077,6.970769,-4.715049,-135.038931,-10.851653,4.649692,28.217769,-9.579000,54.5

In [108]:
"""
grouped_2012_df['game_date'] = pd.to_datetime(grouped_2012_df['game_date'])
grouped_2012_df['season'] = grouped_2012_df['game_date'].dt.year

# Step 1: Season Total Pitches
season_total_pitches = grouped_2012_df.groupby(['pitcher', 'player_name', 'season'])['total_pitches'].sum().reset_index(name='season_total_pitches')

# Step 2: Season Total by Pitch Type
season_total_by_pitch_type = grouped_2012_df.groupby(['pitcher', 'player_name', 'season', 'pitch_type'])['count_by_pitch_type'].sum().reset_index(name='season_total_count_by_pitch_type')

# Weighted Averages Calculation Setup
weighted_avg_columns = ['release_speed', 'release_pos_x', 'release_pos_z', 'vx0', 'vy0', 'vz0', 'ax', 'ay', 'az', 'release_pos_y']
for col in weighted_avg_columns:
    grouped_2012_df[f'{col}_product'] = grouped_2012_df[col] * grouped_2012_df['count_by_pitch_type']

weighted_avg_aggregations = {f'{col}_product': 'sum' for col in weighted_avg_columns}
weighted_avg_aggregations['count_by_pitch_type'] = 'sum'

# Aggregate for weighted averages
weighted_avg_df = grouped_2012_df.groupby(['pitcher', 'player_name', 'season', 'pitch_type']).agg(weighted_avg_aggregations).reset_index()

# Calculate weighted averages
for col in weighted_avg_columns:
    weighted_avg_df[f'{col}_weighted_avg'] = weighted_avg_df[f'{col}_product'] / weighted_avg_df['count_by_pitch_type']

# Cleanup
weighted_avg_df.drop(columns=[f'{col}_product' for col in weighted_avg_columns], inplace=True)

# Merge season totals and weighted averages
final_2012_df = pd.merge(season_total_pitches, season_total_by_pitch_type, on=['pitcher', 'player_name', 'season'])
final_2012_df = pd.merge(final_2012_df, weighted_avg_df, on=['pitcher', 'player_name', 'season', 'pitch_type'])

final_2012_df.head()
"""

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,110683,"Batista, Miguel",2012,3991,CH,64,64,83.001563,-1.187344,6.012187,2.629902,-121.548068,-3.095360,-6.305750,21.989563,-25.179344,54.5
1,110683,"Batista, Miguel",2012,3991,CU,11,11,76.427273,-1.366364,6.016364,1.947998,-112.083840,-0.468344,6.263182,19.486636,-34.705455,54.5
2,110683,"Batista, Miguel",2012,3991,FC,2,2,91.400000,-1.075000,6.095000,2.156367,-133.942572,-3.966079,0.611500,26.686000,-15.658000,54.5
3,110683,"Batista, Miguel",2012,3991,FF,208,208,91.975481,-1.307885,5.852356,4.168499,-134.766492,-3.940062,-3.646505,28.322875,-16.700317,54.5
4,110683,"Batista, Miguel",2012,3991,IN,4,4,50.375000,-1.755000,6.992500,-4.418470,-73.528548,7.101314,1.388500,8.031000,-30.029000,54.5

In [109]:
"""
final_2012_df['player_name'] = final_2012_df['player_name'].str.lower().str.strip().str.replace(r'\*$', '', regex=True)
final_2012_df
"""

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,110683,"batista, miguel",2012,3991,CH,64,64,83.001563,-1.187344,6.012187,2.629902,-121.548068,-3.095360,-6.305750,21.989563,-25.179344,54.5
1,110683,"batista, miguel",2012,3991,CU,11,11,76.427273,-1.366364,6.016364,1.947998,-112.083840,-0.468344,6.263182,19.486636,-34.705455,54.5
2,110683,"batista, miguel",2012,3991,FC,2,2,91.400000,-1.075000,6.095000,2.156367,-133.942572,-3.966079,0.611500,26.686000,-15.658000,54.5
3,110683,"batista, miguel",2012,3991,FF,208,208,91.975481,-1.307885,5.852356,4.168499,-134.766492,-3.940062,-3.646505,28.322875,-16.700317,54.5
4,110683,"batista, miguel",2012,3991,IN,4,4,50.375000,-1.755000,6.992500,-4.418470,-73.528548,7.101314,1.388500,8.031000,-30.029000,54.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1598,612672,"chen, wei-yin",2012,15594,CU,189,189,71.735979,2.363757,6.000053,-3.223712,-105.180818,2.870589,-3.903635,18.876857,-38.020016,54.5
1599,612672,"chen, wei-yin",2012,15594,FA,1,1,88.500000,2.790000,6.060000,-9.094416,-129.528733,-3.544970,15.382000,28.037000,-14.482000,54.5
1600,612672,"chen, wei-yin",2012,15594,FF,1794,1794,91.547046,2.648467,6.010831,-8.751699,-133.968286,-5.370945,9.808896,29.954142,-12.828067,54.5
1601,612672,"chen, wei-yin",2012,15594,SI,251,251,91.211155,2.705936,5.966375,-9.406119,-133.452497,-5.158112,18.342705,30.019936,-15.947538,54.5
1602,612672,"chen, wei-yin",2012,15594,SL,469,469,80.852239,2.641535,5.945096,-5.795460,-118.376634,-0.358442,-1.375765,22.146335,-32.443957,54.5

In [110]:
#print(final_2012_df['player_name'].unique())

['batista, miguel' 'carpenter, chris' 'colon, bartolo' 'hawkins, latroy'
 'hernandez, livan' 'isringhausen, jason' 'lowe, derek' 'millwood, kevin'
 'moyer, jamie' 'oliver, darren' 'pettitte, andy' 'suppan, jeff'
 'wright, jamey' 'dempster, ryan' 'wood, kerry' 'pavano, carl'
 'chen, bruce' 'halladay, roy' 'wolf, randy' 'nathan, joe'
 'marquis, jason' 'wells, kip' 'burnett, a.j.' 'lilly, ted'
 'westbrook, jake' 'lopez, rodrigo' 'glover, gary' 'penny, brad'
 'zito, barry' 'hudson, tim' 'padilla, vicente' 'durbin, chad'
 'downs, scott' 'santana, johan' 'arroyo, bronson' 'benoit, joaquÃ­n'
 'beckett, josh' 'belisle, matt' 'buehrle, mark' 'sabathia, cc'
 'sheets, ben' 'vogelsong, ryan' 'dickey, r.a.' 'affeldt, jeremy'
 'lohse, kyle' 'cook, aaron' 'oswalt, roy' 'moseley, dustin'
 'zambrano, carlos' 'de la rosa, jorge' 'bedard, erik' 'lewis, colby'
 'myers, brett' 'peavy, jake' 'harang, aaron' 'pÃ©rez, oliver'
 'guthrie, jeremy' 'wang, chien-ming' 'williams, jerome' 'capuano, chris'
 'carrasco, d.j.' 'contreras, jose' 'wainwright, adam' 'greinke, zack'
 'floyd, gavin' 'haren, dan' 'hill, shawn' 'jackson, edwin'
 'santana, ervin' 'narveson, chris' 'correia, kevin' 'gaudin, chad'
 'simon, alfredo' 'blanton, joe' 'germano, justin' 'maholm, paul'
 'cain, matt' 'hamels, cole' 'stauffer, tim' 'young, chris' 'danks, john'
 'hernandez, roberto' 'francis, jeff' 'hernÃ¡ndez, fÃ©lix' 'petit, yusmeiro'
 'loe, kameron' 'verlander, justin' 'liriano, francisco' 'saunders, joe'
 'jimÃ©nez, ubaldo' 'hammel, jason' 'rodriguez, wandy' 'mendoza, luis'
 'sÃ¡nchez, anÃ­bal' 'duke, zach' 'mccarthy, brandon' 'niemann, jeff'
 'karstens, jeff' 'laffey, aaron' 'feldman, scott' 'nolasco, ricky'
 'marshall, sean' 'stults, eric' 'chavez, jesse' 'eveland, dana'
 'detwiler, ross' 'kluber, corey' 'cecil, brett' 'blackburn, nick'
 'parra, manny' 'hill, rich' 'bergesen, brad' 'shields, james'
 'wells, randy' 'garcÃ­a, jaime' 'harrell, lucas' 'volquez, edinson'
 'vargas, jason' 'weaver, jered' 'wilson, c.j.' 'medlen, kris'
 'fister, doug' 'matusz, brian' 'galarraga, armando' 'billingsley, chad'
 'davis, wade' 'gallardo, yovani' 'marcum, shaun' 'owings, micah'
 'lester, jon' 'kendrick, kyle' 'gorzelanny, tom' 'kennedy, ian'
 'miller, andrew' 'leblanc, wade' 'scherzer, max' 'huff, david'
 'lincecum, tim' 'buchholz, clay' 'morrow, brandon' 'richard, clayton'
 'arrieta, jake' 'villanueva, carlos' 'hensley, clay' 'ohlendorf, ross'
 'price, david' 'sÃ¡nchez, jonathan' 'noesÃ­, hector' 'griffin, a.j.'
 'cueto, johnny' 'bailey, homer' 'harrison, matt' 'jurrjens, jair'
 "o'sullivan, sean" 'happ, j.a.' 'luebke, cory' 'hefner, jeremy'
 'lynn, lance' 'volstad, chris' 'tomlin, josh' 'lannan, john'
 'humber, philip' 'hochevar, luke' 'pelfrey, mike' 'romero, ricky'
 'gonzÃ¡lez, gio' 'hughes, phil' 'swarzak, anthony' 'hanson, tommy'
 'estrada, marco' 'paulino, felipe' 'morales, franklin' 'doubront, felix'
 'nova, ivÃ¡n' 'ogando, alexi' 'chacÃ­n, jhoulys' 'rogers, esmil'
 'anderson, brett' 'worley, vance' 'ross, tyson' 'drabek, kyle'
 'wood, travis' 'masterson, justin' 'phelps, david' 'hellickson, jeremy'
 'niese, jonathon' 'kershaw, clayton' 'cashner, andrew' 'duensing, brian'
 'hunter, tommy' 'miley, wade' 'stammen, craig' 'garza, matt'
 'kuroda, hiroki' 'matsuzaka, daisuke' 'quintana, jose' 'tillman, chris'
 'minor, mike' 'latos, mat' 'norris, bud' 'archer, chris' 'locke, jeff'
 'mcallister, zach' 'cobb, alex' 'samardzija, jeff' 'leake, mike'
 'cahill, trevor' 'santiago, hÃ©ctor' 'holland, derek' 'peralta, wily'
 'nicasio, juan' 'darvish, yu' 'alvarez iii, henderson' 'delgado, randall'
 'bumgarner, madison' 'collmenter, josh' 'duffy, danny' 'gee, dillon'
 'harvey, matt' 'moore, matt' 'oberholtzer, brett' 'parker, jarrod'
 'pomeranz, drew' 'porcello, rick' 'sale, chris' 'zimmermann, jordan'
 'de la rosa, rubby' 'pÃ©rez, martÃ­n' 'teheran, julio' 'diamond, scott'
 'chatwood, tyler' 'eovaldi, nathan' 'hudson, daniel' 'koehler, tom'
 'lyles, jordan' 'mchugh, collin' 'milone, tommy' 'odorizzi, jake'
 'strasburg, stephen' 'bauer, trevor' 'turner, jacob' 'beachy, brandon'
 'iwakuma, hisashi' 'corbin, patrick' 'fiers, mike' 'hutchison, drew'
 'mikolas, miles' 'miller, shelby' 'richards, garrett' 'skaggs, tyler'
 'keuchel, dallas' 'straily, dan' 'smyly, drew' 'bundy, dylan'
 'chen, wei-yin']

In [111]:
"""
def remove_accents(input_str):
    nfkd_form = unicodedata.normalize('NFKD', input_str)
    return "".join([c for c in nfkd_form if not unicodedata.combining(c)])

def clean_name(name):
    name = name.lower()
    name = remove_accents(name)
    name = re.sub(r'[-.]', '', name)
    name = re.sub(r'\s+', ' ', name).strip()
    return name

final_2012_df['player_name'] = final_2012_df['player_name'].apply(clean_name)
"""

In [112]:
"""
# Convert 'player_name' from "last name, first name" to "first name last name"
final_2012_df['Name'] = final_2012_df['player_name'].apply(lambda x: ' '.join(x.split(', ')[::-1]))
"""

In [113]:
"""
# Now, you can perform the merge using 'Name' and 'season' as the keys for both DataFrames
better_2012_df = pd.merge(final_2012_df, 
                          cleaning_filtered_df[['Name', 'season', 'Age']],
                          on=['Name', 'season'],
                          how='left')
"""

In [116]:
#better_2012_df

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg,Name,Age
0,110683,"batista, miguel",2012,3991,CH,64,64,83.001563,-1.187344,6.012187,2.629902,-121.548068,-3.095360,-6.305750,21.989563,-25.179344,54.5,miguel batista,41.0
1,110683,"batista, miguel",2012,3991,CH,64,64,83.001563,-1.187344,6.012187,2.629902,-121.548068,-3.095360,-6.305750,21.989563,-25.179344,54.5,miguel batista,41.0
2,110683,"batista, miguel",2012,3991,CU,11,11,76.427273,-1.366364,6.016364,1.947998,-112.083840,-0.468344,6.263182,19.486636,-34.705455,54.5,miguel batista,41.0
3,110683,"batista, miguel",2012,3991,CU,11,11,76.427273,-1.366364,6.016364,1.947998,-112.083840,-0.468344,6.263182,19.486636,-34.705455,54.5,miguel batista,41.0
4,110683,"batista, miguel",2012,3991,FC,2,2,91.400000,-1.075000,6.095000,2.156367,-133.942572,-3.966079,0.611500,26.686000,-15.658000,54.5,miguel batista,41.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1625,612672,"chen, weiyin",2012,15594,CU,189,189,71.735979,2.363757,6.000053,-3.223712,-105.180818,2.870589,-3.903635,18.876857,-38.020016,54.5,weiyin chen,26.0
1626,612672,"chen, weiyin",2012,15594,FA,1,1,88.500000,2.790000,6.060000,-9.094416,-129.528733,-3.544970,15.382000,28.037000,-14.482000,54.5,weiyin chen,26.0
1627,612672,"chen, weiyin",2012,15594,FF,1794,1794,91.547046,2.648467,6.010831,-8.751699,-133.968286,-5.370945,9.808896,29.954142,-12.828067,54.5,weiyin chen,26.0
1628,612672,"chen, weiyin",2012,15594,SI,251,251,91.211155,2.705936,5.966375,-9.406119,-133.452497,-5.158112,18.342705,30.019936,-15.947538,54.5,weiyin chen,26.0
1629,612672,"chen, weiyin",2012,15594,SL,469,469,80.852239,2.641535,5.945096,-5.795460,-118.376634,-0.358442,-1.375765,22.146335,-32.443957,54.5,weiyin chen,26.0

In [117]:
#better_2012_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1630 entries, 0 to 1629
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   pitcher                           1630 non-null   int64
 1   player_name                       1630 non-null   object
 2   season                            1630 non-null   int32
 3   season_total_pitches              1630 non-null   int64
 4   pitch_type                        1630 non-null   object
 5   season_total_count_by_pitch_type  1630 non-null   int64
 6   count_by_pitch_type               1630 non-null   int64
 7   release_speed_weighted_avg        1630 non-null   float64
 8   release_pos_x_weighted_avg        1630 non-null   float64
 9   release_pos_z_weighted_avg        1630 non-null   float64
 10  vx0_weighted_avg                  1630 non-null   float64
 11  vy0_weighted_avg                  1630 non-null   float64
 12  vz0_weighted_avg                  1630 non-null   float64
 13  ax_weighted_avg                   1630 non-null   float64
 14  ay_weighted_avg                   1630 non-null   float64
 15  az_weighted_avg                   1630 non-null   float64
 16  release_pos_y_weighted_avg        1630 non-null   float64
 17  Name                              1630 non-null   object
 18  Age                               1402 non-null   float64
dtypes: float64(11), int32(1), int64(4), object(3)
memory usage: 235.7+ KB

In [118]:
#better_2012_df.to_csv('data/better_2012_df.csv')

2013

In [119]:
#all_2013_stats_df = pd.read_csv('~/Documents/Flatiron/Project_5_/data/all_2013_stats_df.csv', index_col=0)

In [120]:
"""all_2013_stats_df.drop(columns=['batter', 'events', 'description', 'zone',
                                'des', 'game_type', 'stand', 'home_team',
                                'away_team', 'type', 'hit_location', 'bb_type',
                                'balls', 'strikes', 'pfx_x', 'spin_dir', 
                                'pfx_z', 'plate_x', 'plate_z', 'on_3b',
                                'on_2b', 'on_1b', 'outs_when_up', 'inning',
                                'inning_topbot', 'hc_x', 'hc_y', 'fielder_2',
                                'umpire', 'sv_id', 'hit_distance_sc', 'sz_top',
                                 'sz_bot', 'launch_speed', 'launch_angle', 'game_pk',
                                'pitcher.1', 'fielder_2.1', 'fielder_3', 'fielder_4',
                                'fielder_5', 'fielder_6', 'fielder_7', 'fielder_8',
                                'fielder_9', 'estimated_ba_using_speedangle',
                                'estimated_woba_using_speedangle', 'babip_value',
                                'launch_speed_angle', 'woba_value', 'woba_denom', 'iso_value', 
                                'at_bat_number', 'pitch_number', 'home_score', 'away_score',
                                'bat_score', 'fld_score', 'post_home_score', 'post_bat_score',
                                'post_fld_score', 'post_away_score', 'if_fielding_alignment',
                                'of_fielding_alignment', 'delta_home_win_exp',
                                'delta_run_exp', 'spin_rate_deprecated', 'break_angle_deprecated',
                               'break_length_deprecated', 'tfs_deprecated', 'tfs_zulu_deprecated'], inplace=True)
all_2013_stats_df.head()
"""

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,...,vz0,ax,ay,az,effective_speed,release_spin_rate,release_extension,release_pos_y,pitch_name,spin_axis
0,SL,2013-09-28,87.5,-1.88,6.24,"Hawkins, LaTroy",115629,R,2013,5.952918,...,-4.445319,-0.707,24.405,-23.768,NaN,NaN,NaN,54.5,Slider,NaN
1,FF,2013-09-28,93.7,-1.69,6.17,"Hawkins, LaTroy",115629,R,2013,7.544815,...,-4.337540,-15.136,27.712,-18.281,NaN,NaN,NaN,54.5,4-Seam Fastball,NaN
2,FF,2013-09-28,93.4,-1.61,6.23,"Hawkins, LaTroy",115629,R,2013,5.332880,...,-4.472962,-13.787,28.918,-19.399,NaN,NaN,NaN,54.5,4-Seam Fastball,NaN
3,SL,2013-09-28,88.0,-1.90,6.22,"Hawkins, LaTroy",115629,R,2013,6.775720,...,-4.784047,3.885,23.319,-27.708,NaN,NaN,NaN,54.5,Slider,NaN
4,FF,2013-09-28,93.3,-1.80,6.25,"Hawkins, LaTroy",115629,R,2013,4.820789,...,-3.392456,-14.771,29.305,-24.060,NaN,NaN,NaN,54.5,4-Seam Fastball,NaN

In [121]:
"""
all_2013_stats_df.drop(columns=['spin_axis', 'effective_speed',
                               'release_spin_rate', 'release_extension'], inplace=True)
"""

In [122]:
#all_2013_stats_df = all_2013_stats_df.dropna(axis=0)

In [123]:
#all_2013_stats_df.reset_index(inplace=True)

In [124]:
#all_2013_stats_df.drop('index', axis=1)

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,vy0,vz0,ax,ay,az,release_pos_y,pitch_name
0,SL,2013-09-28,87.5,-1.88,6.24,"Hawkins, LaTroy",115629,R,2013,5.952918,-128.111131,-4.445319,-0.707,24.405,-23.768,54.5,Slider
1,FF,2013-09-28,93.7,-1.69,6.17,"Hawkins, LaTroy",115629,R,2013,7.544815,-137.004264,-4.337540,-15.136,27.712,-18.281,54.5,4-Seam Fastball
2,FF,2013-09-28,93.4,-1.61,6.23,"Hawkins, LaTroy",115629,R,2013,5.332880,-136.868102,-4.472962,-13.787,28.918,-19.399,54.5,4-Seam Fastball
3,SL,2013-09-28,88.0,-1.90,6.22,"Hawkins, LaTroy",115629,R,2013,6.775720,-128.692994,-4.784047,3.885,23.319,-27.708,54.5,Slider
4,FF,2013-09-28,93.3,-1.80,6.25,"Hawkins, LaTroy",115629,R,2013,4.820789,-136.750752,-3.392456,-14.771,29.305,-24.060,54.5,4-Seam Fastball
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452986,KC,2013-05-30,81.9,2.38,5.43,"Wood, Alex",622072,L,2013,-3.043644,-119.935988,2.422662,-4.844,21.277,-38.083,54.5,Knuckle Curve
452987,CH,2013-05-30,84.4,2.55,5.39,"Wood, Alex",622072,L,2013,-6.948423,-123.552559,1.051383,12.900,22.700,-28.469,54.5,Changeup
452988,CH,2013-05-30,85.4,2.30,5.45,"Wood, Alex",622072,L,2013,-7.755317,-124.987127,0.994561,15.207,22.787,-29.360,54.5,Changeup
452989,SI,2013-05-30,94.4,2.14,5.63,"Wood, Alex",622072,L,2013,-14.421131,-137.524312,-3.851486,20.170,27.060,-21.126,54.5,Sinker
452990,SI,2013-05-30,94.8,2.31,5.52,"Wood, Alex",622072,L,2013,-8.169954,-138.617707,-4.430567,15.196,28.206,-18.066,54.5,Sinker

In [125]:
"""
# Group by 'game_date' and 'pitcher' to calculate the total pitches
total_pitches = all_2013_stats_df.groupby(['game_date', 'pitcher', 'player_name']).size().reset_index(name='total_pitches')

# Group by 'game_date', 'pitcher', and 'pitch_type' to calculate the sum total of each pitch_type
total_pitches_by_type = all_2013_stats_df.groupby(['game_date', 'pitcher', 'player_name', 'pitch_type']).size().reset_index(name='count_by_pitch_type')

# Calculate averages of the specified metrics for each pitch type, grouped by game_date and pitcher
avg_metrics = all_2013_stats_df.groupby(['game_date', 'pitcher', 'player_name', 'pitch_type']).agg({
    'release_speed': 'mean',
    'release_pos_x': 'mean',
    'release_pos_z': 'mean',
    'vx0': 'mean',
    'vy0': 'mean',
    'vz0': 'mean',
    'ax': 'mean',
    'ay': 'mean',
    'az': 'mean',
    'release_pos_y': 'mean',
}).reset_index()

grouped_2013_df = total_pitches.merge(total_pitches_by_type, on=['game_date', 'pitcher', 'player_name'], how='left')
grouped_2013_df = grouped_2013_df.merge(avg_metrics, on=['game_date', 'pitcher', 'player_name', 'pitch_type'], how='left')

grouped_2013_df
"""

,game_date,pitcher,player_name,total_pitches,pitch_type,count_by_pitch_type,release_speed,release_pos_x,release_pos_z,vx0,vy0,vz0,ax,ay,az,release_pos_y
0,2013-03-31,117955,"Lowe, Derek",10,SI,6,88.783333,-2.023333,5.796667,8.938266,-130.029431,-2.111955,-11.434833,28.736333,-25.555333,54.5
1,2013-03-31,117955,"Lowe, Derek",10,SL,4,81.200000,-1.995000,5.822500,4.537207,-118.943753,-0.175715,6.944750,23.040750,-32.760500,54.5
2,2013-03-31,407853,"Bedard, Erik",38,CH,1,79.000000,2.870000,5.470000,-8.990962,-115.741081,-0.322394,16.677000,23.341000,-24.123000,54.5
3,2013-03-31,407853,"Bedard, Erik",38,CU,4,77.825000,2.870000,5.705000,-6.359978,-114.237499,1.654963,-2.907500,25.411500,-42.817000,54.5
4,2013-03-31,407853,"Bedard, Erik",38,FF,25,90.160000,3.254800,5.525600,-11.356565,-131.819111,-3.579115,11.554760,29.267720,-15.018200,54.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27722,2013-09-30,527048,"PÃ©rez, MartÃ­n",74,CH,22,85.972727,1.638636,5.748636,-5.701100,-125.813894,-4.942464,10.069182,23.996182,-22.281227,54.5
27723,2013-09-30,527048,"PÃ©rez, MartÃ­n",74,CU,4,77.825000,1.610000,5.830000,-1.428483,-114.163082,2.625271,-7.979500,19.938500,-36.964500,54.5
27724,2013-09-30,527048,"PÃ©rez, MartÃ­n",74,FF,22,93.540909,1.579091,5.675909,-6.689813,-136.813366,-6.052029,7.130000,28.509591,-14.888000,54.5
27725,2013-09-30,527048,"PÃ©rez, MartÃ­n",74,SI,13,93.569231,1.569231,5.606154,-5.733801,-137.030192,-4.331661,14.663308,29.815077,-21.484923,54.5
27726,2013-09-30,527048,"PÃ©rez, MartÃ­n",74,SL,13,84.500000,1.773846,5.507692,-4.074462,-123.793197,-0.809546,-5.246923,23.425923,-31.047231,54.5

In [126]:
"""
grouped_2013_df['game_date'] = pd.to_datetime(grouped_2013_df['game_date'])
grouped_2013_df['season'] = grouped_2013_df['game_date'].dt.year

# Step 1: Season Total Pitches
season_total_pitches = grouped_2013_df.groupby(['pitcher', 'player_name', 'season'])['total_pitches'].sum().reset_index(name='season_total_pitches')

# Step 2: Season Total by Pitch Type
season_total_by_pitch_type = grouped_2013_df.groupby(['pitcher', 'player_name', 'season', 'pitch_type'])['count_by_pitch_type'].sum().reset_index(name='season_total_count_by_pitch_type')

# Weighted Averages Calculation Setup
weighted_avg_columns = ['release_speed', 'release_pos_x', 'release_pos_z', 'vx0', 'vy0', 'vz0', 'ax', 'ay', 'az', 'release_pos_y']
for col in weighted_avg_columns:
    grouped_2013_df[f'{col}_product'] = grouped_2013_df[col] * grouped_2013_df['count_by_pitch_type']

weighted_avg_aggregations = {f'{col}_product': 'sum' for col in weighted_avg_columns}
weighted_avg_aggregations['count_by_pitch_type'] = 'sum'

# Aggregate for weighted averages
weighted_avg_df = grouped_2013_df.groupby(['pitcher', 'player_name', 'season', 'pitch_type']).agg(weighted_avg_aggregations).reset_index()

# Calculate weighted averages
for col in weighted_avg_columns:
    weighted_avg_df[f'{col}_weighted_avg'] = weighted_avg_df[f'{col}_product'] / weighted_avg_df['count_by_pitch_type']

# Cleanup
weighted_avg_df.drop(columns=[f'{col}_product' for col in weighted_avg_columns], inplace=True)

# Merge season totals and weighted averages
final_2013_df = pd.merge(season_total_pitches, season_total_by_pitch_type, on=['pitcher', 'player_name', 'season'])
final_2013_df = pd.merge(final_2013_df, weighted_avg_df, on=['pitcher', 'player_name', 'season', 'pitch_type'])

final_2013_df.head()
"""

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,112526,"Colon, Bartolo",2013,10929,CH,161,161,83.098758,-1.321615,5.805901,4.884045,-121.674884,-2.525674,-11.780112,22.425329,-23.941478,54.5
1,112526,"Colon, Bartolo",2013,10929,FF,973,973,92.191059,-0.971007,5.959825,3.984247,-135.068565,-4.850025,-10.533917,29.007812,-16.368126,54.5
2,112526,"Colon, Bartolo",2013,10929,SI,1375,1375,89.408436,-1.336975,5.762320,6.206695,-130.961962,-2.691149,-16.148071,26.330848,-24.026324,54.5
3,112526,"Colon, Bartolo",2013,10929,SL,268,268,83.634328,-1.390933,5.894701,2.885524,-122.460088,-2.421329,1.384713,21.557933,-29.683907,54.5
4,115629,"Hawkins, LaTroy",2013,3189,CH,47,47,84.219149,-1.698511,6.515745,4.620595,-123.312667,-5.170814,-10.013638,25.057702,-20.386106,54.5

In [127]:
"""
final_2013_df['player_name'] = final_2013_df['player_name'].str.lower().str.strip().str.replace(r'\*$', '', regex=True)
final_2013_df
"""

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,112526,"colon, bartolo",2013,10929,CH,161,161,83.098758,-1.321615,5.805901,4.884045,-121.674884,-2.525674,-11.780112,22.425329,-23.941478,54.5
1,112526,"colon, bartolo",2013,10929,FF,973,973,92.191059,-0.971007,5.959825,3.984247,-135.068565,-4.850025,-10.533917,29.007812,-16.368126,54.5
2,112526,"colon, bartolo",2013,10929,SI,1375,1375,89.408436,-1.336975,5.762320,6.206695,-130.961962,-2.691149,-16.148071,26.330848,-24.026324,54.5
3,112526,"colon, bartolo",2013,10929,SL,268,268,83.634328,-1.390933,5.894701,2.885524,-122.460088,-2.421329,1.384713,21.557933,-29.683907,54.5
4,115629,"hawkins, latroy",2013,3189,CH,47,47,84.219149,-1.698511,6.515745,4.620595,-123.312667,-5.170814,-10.013638,25.057702,-20.386106,54.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1501,622072,"wood, alex",2013,4803,FF,43,43,93.658140,1.991860,5.668372,-9.307780,-136.959223,-4.677925,15.821419,28.661953,-17.598302,54.5
1502,622072,"wood, alex",2013,4803,IN,4,4,71.875000,2.860000,6.270000,0.115902,-105.590770,3.751308,8.565000,22.440000,-20.045000,54.5
1503,622072,"wood, alex",2013,4803,KC,187,187,79.861497,2.283583,5.539679,-4.204058,-117.073754,2.349890,-6.433305,23.539225,-40.483364,54.5
1504,622072,"wood, alex",2013,4803,PO,1,1,88.000000,2.560000,5.560000,-3.023558,-128.925121,-0.957464,13.240000,22.710000,-19.780000,54.5
1505,622072,"wood, alex",2013,4803,SI,794,794,92.232620,1.992204,5.664370,-8.548954,-134.972759,-4.278084,15.299009,28.791282,-18.120086,54.5

In [128]:
#print(final_2013_df['player_name'].unique())

['colon, bartolo' 'hawkins, latroy' 'lowe, derek' 'oliver, darren'
 'pettitte, andy' 'wright, jamey' 'dempster, ryan' 'chen, bruce'
 'halladay, roy' 'ortiz, ramon' 'nathan, joe' 'marquis, jason'
 'burnett, a.j.' 'lilly, ted' 'westbrook, jake' 'zito, barry'
 'hudson, tim' 'durbin, chad' 'downs, scott' 'arroyo, bronson'
 'benoit, joaquÃ­n' 'beckett, josh' 'belisle, matt' 'garland, jon'
 'buehrle, mark' 'sabathia, cc' 'vogelsong, ryan' 'dickey, r.a.'
 'affeldt, jeremy' 'lohse, kyle' 'oswalt, roy' 'lackey, john'
 'de la rosa, jorge' 'bedard, erik' 'myers, brett' 'peavy, jake'
 'harang, aaron' 'pÃ©rez, oliver' 'guthrie, jeremy' 'wang, chien-ming'
 'williams, jerome' 'capuano, chris' 'contreras, jose' 'wainwright, adam'
 'bonderman, jeremy' 'greinke, zack' 'floyd, gavin' 'haren, dan'
 'jackson, edwin' 'maine, john' 'santana, ervin' 'narveson, chris'
 'correia, kevin' 'gaudin, chad' 'simon, alfredo' 'blanton, joe'
 'mcgowan, dustin' 'germano, justin' 'maholm, paul' 'cain, matt'
 'hamels, cole' 'kazmir, scott' 'stauffer, tim' 'danks, john'
 'hernandez, roberto' 'francis, jeff' 'hernÃ¡ndez, fÃ©lix' 'petit, yusmeiro'
 'bush, dave' 'loe, kameron' 'verlander, justin' 'liriano, francisco'
 'saunders, joe' 'jimÃ©nez, ubaldo' 'hammel, jason' 'rodriguez, wandy'
 'mendoza, luis' 'sÃ¡nchez, anÃ­bal' 'duke, zach' 'mccarthy, brandon'
 'miner, zach' 'laffey, aaron' 'feldman, scott' 'nolasco, ricky'
 'marshall, sean' 'stults, eric' 'chavez, jesse' 'detwiler, ross'
 'kluber, corey' 'cecil, brett' 'parra, manny' 'hill, rich'
 'shields, james' 'garcÃ­a, jaime' 'harrell, lucas' 'volquez, edinson'
 'vargas, jason' 'weaver, jered' 'wilson, c.j.' 'medlen, kris'
 'fister, doug' 'matusz, brian' 'billingsley, chad' 'davis, wade'
 'gallardo, yovani' 'marcum, shaun' 'lester, jon' 'kendrick, kyle'
 'gorzelanny, tom' 'kennedy, ian' 'miller, andrew' 'wright, steven'
 'leblanc, wade' 'scherzer, max' 'huff, david' 'lincecum, tim'
 'buchholz, clay' 'morrow, brandon' 'richard, clayton' 'arrieta, jake'
 'villanueva, carlos' 'ohlendorf, ross' 'price, david' 'sÃ¡nchez, jonathan'
 'noesÃ­, hector' 'griffin, a.j.' 'cueto, johnny' 'bailey, homer'
 'harrison, matt' 'jurrjens, jair' "o'sullivan, sean" 'happ, j.a.'
 'hefner, jeremy' 'lynn, lance' 'volstad, chris' 'tomlin, josh'
 'lannan, john' 'slowey, kevin' 'humber, philip' 'hochevar, luke'
 'pelfrey, mike' 'romero, ricky' 'gonzÃ¡lez, gio' 'hughes, phil'
 'swarzak, anthony' 'hanson, tommy' 'estrada, marco' 'morales, franklin'
 'doubront, felix' 'nova, ivÃ¡n' 'ogando, alexi' 'chacÃ­n, jhoulys'
 'rogers, esmil' 'carrasco, carlos' 'anderson, brett' 'worley, vance'
 'ross, tyson' 'drabek, kyle' 'wood, travis' 'masterson, justin'
 'phelps, david' 'hellickson, jeremy' 'niese, jonathon' 'kershaw, clayton'
 'cashner, andrew' 'duensing, brian' 'hunter, tommy' 'miley, wade'
 'stammen, craig' 'garza, matt' 'kuroda, hiroki' 'matsuzaka, daisuke'
 'quintana, jose' 'tillman, chris' 'minor, mike' 'latos, mat'
 'norris, bud' 'archer, chris' 'gibson, kyle' 'locke, jeff'
 'mcallister, zach' 'cobb, alex' 'samardzija, jeff' 'leake, mike'
 'cahill, trevor' 'santiago, hÃ©ctor' 'holland, derek' 'peacock, brad'
 'peralta, wily' 'nicasio, juan' 'darvish, yu' 'alvarez iii, henderson'
 'delgado, randall' 'salazar, danny' 'bettis, chad' 'bumgarner, madison'
 'collmenter, josh' 'duffy, danny' 'gee, dillon' 'harvey, matt'
 'moore, matt' 'nelson, jimmy' 'oberholtzer, brett' 'parker, jarrod'
 'pomeranz, drew' 'porcello, rick' 'sale, chris' 'zimmermann, jordan'
 'de la rosa, rubby' 'pÃ©rez, martÃ­n' 'teheran, julio' 'shoemaker, matt'
 'diamond, scott' 'chatwood, tyler' 'cole, gerrit' 'cosart, jarred'
 'eovaldi, nathan' 'gray, sonny' 'koehler, tom' 'lyles, jordan'
 'mchugh, collin' 'milone, tommy' 'odorizzi, jake' 'roark, tanner'
 'strasburg, stephen' 'bauer, trevor' 'turner, jacob' 'beachy, brandon'
 'iwakuma, hisashi' 'ryu, hyun jin' 'wheeler, zack' 'ventura, yordano'
 'corbin, patrick' 'fiers, mike' 'mikolas, miles' 'miller, shelby'
 'paxton, james' 'richards, garrett' 'skaggs, tyler' 'erlin, robbie'
 'keuchel, dallas' 'nuÃ±o, vidal' 'straily, dan' 'gausman, kevin'
 'smyly, drew' 'walker, taijuan' 'wacha, michael' 'chen, wei-yin'
 'wood, alex']

In [129]:
"""
def remove_accents(input_str):
    nfkd_form = unicodedata.normalize('NFKD', input_str)
    return "".join([c for c in nfkd_form if not unicodedata.combining(c)])

def clean_name(name):
    name = name.lower()
    name = remove_accents(name)
    name = re.sub(r'[-.]', '', name)
    name = re.sub(r'\s+', ' ', name).strip()
    return name

final_2013_df['player_name'] = final_2013_df['player_name'].apply(clean_name)
"""

In [130]:
"""
# Convert 'player_name' from "last name, first name" to "first name last name"
final_2013_df['Name'] = final_2013_df['player_name'].apply(lambda x: ' '.join(x.split(', ')[::-1]))
"""

In [131]:
"""
# Now, you can perform the merge using 'Name' and 'season' as the keys for both DataFrames
better_2013_df = pd.merge(final_2013_df, 
                          cleaning_filtered_df[['Name', 'season', 'Age']],
                          on=['Name', 'season'],
                          how='left')
"""

In [133]:
#better_2013_df

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg,Name,Age
0,112526,"colon, bartolo",2013,10929,CH,161,161,83.098758,-1.321615,5.805901,4.884045,-121.674884,-2.525674,-11.780112,22.425329,-23.941478,54.5,bartolo colon,40.0
1,112526,"colon, bartolo",2013,10929,FF,973,973,92.191059,-0.971007,5.959825,3.984247,-135.068565,-4.850025,-10.533917,29.007812,-16.368126,54.5,bartolo colon,40.0
2,112526,"colon, bartolo",2013,10929,SI,1375,1375,89.408436,-1.336975,5.762320,6.206695,-130.961962,-2.691149,-16.148071,26.330848,-24.026324,54.5,bartolo colon,40.0
3,112526,"colon, bartolo",2013,10929,SL,268,268,83.634328,-1.390933,5.894701,2.885524,-122.460088,-2.421329,1.384713,21.557933,-29.683907,54.5,bartolo colon,40.0
4,115629,"hawkins, latroy",2013,3189,CH,47,47,84.219149,-1.698511,6.515745,4.620595,-123.312667,-5.170814,-10.013638,25.057702,-20.386106,54.5,latroy hawkins,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1535,622072,"wood, alex",2013,4803,FF,43,43,93.658140,1.991860,5.668372,-9.307780,-136.959223,-4.677925,15.821419,28.661953,-17.598302,54.5,alex wood,22.0
1536,622072,"wood, alex",2013,4803,IN,4,4,71.875000,2.860000,6.270000,0.115902,-105.590770,3.751308,8.565000,22.440000,-20.045000,54.5,alex wood,22.0
1537,622072,"wood, alex",2013,4803,KC,187,187,79.861497,2.283583,5.539679,-4.204058,-117.073754,2.349890,-6.433305,23.539225,-40.483364,54.5,alex wood,22.0
1538,622072,"wood, alex",2013,4803,PO,1,1,88.000000,2.560000,5.560000,-3.023558,-128.925121,-0.957464,13.240000,22.710000,-19.780000,54.5,alex wood,22.0
1539,622072,"wood, alex",2013,4803,SI,794,794,92.232620,1.992204,5.664370,-8.548954,-134.972759,-4.278084,15.299009,28.791282,-18.120086,54.5,alex wood,22.0

In [134]:
#better_2013_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1540 entries, 0 to 1539
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   pitcher                           1540 non-null   int64
 1   player_name                       1540 non-null   object
 2   season                            1540 non-null   int32
 3   season_total_pitches              1540 non-null   int64
 4   pitch_type                        1540 non-null   object
 5   season_total_count_by_pitch_type  1540 non-null   int64
 6   count_by_pitch_type               1540 non-null   int64
 7   release_speed_weighted_avg        1540 non-null   float64
 8   release_pos_x_weighted_avg        1540 non-null   float64
 9   release_pos_z_weighted_avg        1540 non-null   float64
 10  vx0_weighted_avg                  1540 non-null   float64
 11  vy0_weighted_avg                  1540 non-null   float64
 12  vz0_weighted_avg                  1540 non-null   float64
 13  ax_weighted_avg                   1540 non-null   float64
 14  ay_weighted_avg                   1540 non-null   float64
 15  az_weighted_avg                   1540 non-null   float64
 16  release_pos_y_weighted_avg        1540 non-null   float64
 17  Name                              1540 non-null   object
 18  Age                               1331 non-null   float64
dtypes: float64(11), int32(1), int64(4), object(3)
memory usage: 222.7+ KB

In [135]:
#better_2013_df.to_csv('data/better_2013_df.csv')

2014

In [136]:
#all_2014_stats_df = pd.read_csv('~/Documents/Flatiron/Project_5_/data/all_2014_stats_df.csv', index_col=0)

In [137]:
"""
all_2014_stats_df.drop(columns=['batter', 'events', 'description', 'zone',
                                'des', 'game_type', 'stand', 'home_team',
                                'away_team', 'type', 'hit_location', 'bb_type',
                                'balls', 'strikes', 'pfx_x', 'spin_dir', 
                                'pfx_z', 'plate_x', 'plate_z', 'on_3b',
                                'on_2b', 'on_1b', 'outs_when_up', 'inning',
                                'inning_topbot', 'hc_x', 'hc_y', 'fielder_2',
                                'umpire', 'sv_id', 'hit_distance_sc', 'sz_top',
                                 'sz_bot', 'launch_speed', 'launch_angle', 'game_pk',
                                'pitcher.1', 'fielder_2.1', 'fielder_3', 'fielder_4',
                                'fielder_5', 'fielder_6', 'fielder_7', 'fielder_8',
                                'fielder_9', 'estimated_ba_using_speedangle',
                                'estimated_woba_using_speedangle', 'babip_value',
                                'launch_speed_angle', 'woba_value', 'woba_denom', 'iso_value', 
                                'at_bat_number', 'pitch_number', 'home_score', 'away_score',
                                'bat_score', 'fld_score', 'post_home_score', 'post_bat_score',
                                'post_fld_score', 'post_away_score', 'if_fielding_alignment',
                                'of_fielding_alignment', 'delta_home_win_exp',
                                'delta_run_exp', 'spin_rate_deprecated', 'break_angle_deprecated',
                               'break_length_deprecated', 'tfs_deprecated', 'tfs_zulu_deprecated'], inplace=True)
all_2014_stats_df.head()
"""

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,...,vz0,ax,ay,az,effective_speed,release_spin_rate,release_extension,release_pos_y,pitch_name,spin_axis
0,FF,2014-09-27,93.7,-1.62,6.28,"Hawkins, LaTroy",115629,R,2014,7.404227,...,-5.842926,-14.522,33.125,-13.576,NaN,NaN,NaN,54.5,4-Seam Fastball,NaN
1,FF,2014-09-27,93.1,-1.63,6.18,"Hawkins, LaTroy",115629,R,2014,6.773917,...,-4.770105,-16.061,30.346,-18.959,NaN,NaN,NaN,54.5,4-Seam Fastball,NaN
2,CU,2014-09-27,77.2,-1.53,6.58,"Hawkins, LaTroy",115629,R,2014,5.941635,...,-3.401167,2.464,21.609,-37.445,NaN,NaN,NaN,54.5,Curveball,NaN
3,SL,2014-09-27,87.1,-1.61,6.38,"Hawkins, LaTroy",115629,R,2014,6.754227,...,-5.880221,-1.869,24.236,-20.821,NaN,NaN,NaN,54.5,Slider,NaN
4,FF,2014-09-27,92.3,-1.57,6.10,"Hawkins, LaTroy",115629,R,2014,7.210528,...,-6.330797,-15.178,29.835,-20.970,NaN,NaN,NaN,54.5,4-Seam Fastball,NaN

In [138]:
"""
all_2014_stats_df.drop(columns=['spin_axis', 'effective_speed',
                               'release_spin_rate', 'release_extension'], inplace=True)
"""

In [139]:
#all_2014_stats_df = all_2014_stats_df.dropna(axis=0)

In [140]:
#all_2014_stats_df.reset_index(inplace=True)

In [141]:
#all_2014_stats_df.drop('index', axis=1)

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,vy0,vz0,ax,ay,az,release_pos_y,pitch_name
0,FF,2014-09-27,93.7,-1.62,6.28,"Hawkins, LaTroy",115629,R,2014,7.404227,-137.193847,-5.842926,-14.522,33.125,-13.576,54.5,4-Seam Fastball
1,FF,2014-09-27,93.1,-1.63,6.18,"Hawkins, LaTroy",115629,R,2014,6.773917,-136.378016,-4.770105,-16.061,30.346,-18.959,54.5,4-Seam Fastball
2,CU,2014-09-27,77.2,-1.53,6.58,"Hawkins, LaTroy",115629,R,2014,5.941635,-113.154648,-3.401167,2.464,21.609,-37.445,54.5,Curveball
3,SL,2014-09-27,87.1,-1.61,6.38,"Hawkins, LaTroy",115629,R,2014,6.754227,-127.424787,-5.880221,-1.869,24.236,-20.821,54.5,Slider
4,FF,2014-09-27,92.3,-1.57,6.10,"Hawkins, LaTroy",115629,R,2014,7.210528,-135.074635,-6.330797,-15.178,29.835,-20.970,54.5,4-Seam Fastball
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452894,CH,2014-04-01,83.3,1.16,5.81,"Wood, Alex",622072,L,2014,-5.166140,-122.209151,1.599812,14.963,25.946,-31.861,54.5,Changeup
452895,SI,2014-04-01,91.5,0.89,5.88,"Wood, Alex",622072,L,2014,-6.069854,-134.213583,-0.361772,14.287,30.353,-19.052,54.5,Sinker
452896,CH,2014-04-01,83.4,1.12,5.83,"Wood, Alex",622072,L,2014,-3.871874,-122.273176,-1.510674,15.885,25.502,-25.479,54.5,Changeup
452897,SI,2014-04-01,92.0,1.03,5.83,"Wood, Alex",622072,L,2014,-4.834544,-134.966424,-2.728419,13.850,30.668,-21.500,54.5,Sinker
452898,SI,2014-04-01,90.7,1.03,5.83,"Wood, Alex",622072,L,2014,-4.938186,-133.018954,-3.494282,16.175,28.391,-23.436,54.5,Sinker

In [142]:
"""
# Group by 'game_date' and 'pitcher' to calculate the total pitches
total_pitches = all_2014_stats_df.groupby(['game_date', 'pitcher', 'player_name']).size().reset_index(name='total_pitches')

# Group by 'game_date', 'pitcher', and 'pitch_type' to calculate the sum total of each pitch_type
total_pitches_by_type = all_2014_stats_df.groupby(['game_date', 'pitcher', 'player_name', 'pitch_type']).size().reset_index(name='count_by_pitch_type')

# Calculate averages of the specified metrics for each pitch type, grouped by game_date and pitcher
avg_metrics = all_2014_stats_df.groupby(['game_date', 'pitcher', 'player_name', 'pitch_type']).agg({
    'release_speed': 'mean',
    'release_pos_x': 'mean',
    'release_pos_z': 'mean',
    'vx0': 'mean',
    'vy0': 'mean',
    'vz0': 'mean',
    'ax': 'mean',
    'ay': 'mean',
    'az': 'mean',
    'release_pos_y': 'mean',
}).reset_index()

grouped_2014_df = total_pitches.merge(total_pitches_by_type, on=['game_date', 'pitcher', 'player_name'], how='left')
grouped_2014_df = grouped_2014_df.merge(avg_metrics, on=['game_date', 'pitcher', 'player_name', 'pitch_type'], how='left')

grouped_2014_df.head()
"""

,game_date,pitcher,player_name,total_pitches,pitch_type,count_by_pitch_type,release_speed,release_pos_x,release_pos_z,vx0,vy0,vz0,ax,ay,az,release_pos_y
0,2014-03-22,450306,"Vargas, Jason",96,CH,30,80.300000,1.842667,6.336000,-5.428231,-117.421364,-4.909296,11.868167,20.097500,-20.812833,54.5
1,2014-03-22,450306,"Vargas, Jason",96,CU,14,74.864286,1.832143,6.412857,-3.565039,-109.682758,-0.019027,-2.501643,17.359857,-37.129857,54.5
2,2014-03-22,450306,"Vargas, Jason",96,FC,5,85.360000,1.872000,6.222000,-6.749682,-124.716654,-5.937519,4.823000,21.606200,-15.057400,54.5
3,2014-03-22,450306,"Vargas, Jason",96,FF,46,87.436957,1.929348,6.165652,-6.433253,-127.912487,-5.130557,8.367152,23.855152,-14.967130,54.5
4,2014-03-22,450306,"Vargas, Jason",96,SI,1,87.200000,2.100000,6.130000,-7.689498,-127.799401,-1.543986,13.992000,26.609000,-17.685000,54.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27564,2014-09-28,605135,"Bassitt, Chris",97,FF,1,95.700000,-2.710000,5.700000,11.121121,-139.690142,-6.672633,-11.233000,29.980000,-17.675000,54.5
27565,2014-09-28,605135,"Bassitt, Chris",97,SI,43,92.818605,-2.723488,5.598372,10.195226,-135.818953,-2.545814,-17.496000,30.447023,-22.954000,54.5
27566,2014-09-28,605135,"Bassitt, Chris",97,SL,23,84.878261,-2.866957,5.621304,6.650068,-124.266909,-0.695274,2.209261,24.399174,-29.316522,54.5
27567,2014-09-28,608665,"Graveman, Kendall",10,SI,9,93.966667,-0.992222,5.527778,5.201414,-137.721602,-2.799373,-16.659333,31.611111,-24.733778,54.5
27568,2014-09-28,608665,"Graveman, Kendall",10,SL,1,84.100000,-0.760000,5.490000,0.946358,-123.320075,-0.200798,8.728000,24.304000,-33.291000,54.5

In [143]:
"""
grouped_2014_df['game_date'] = pd.to_datetime(grouped_2014_df['game_date'])
grouped_2014_df['season'] = grouped_2014_df['game_date'].dt.year

# Step 1: Season Total Pitches
season_total_pitches = grouped_2014_df.groupby(['pitcher', 'player_name', 'season'])['total_pitches'].sum().reset_index(name='season_total_pitches')

# Step 2: Season Total by Pitch Type
season_total_by_pitch_type = grouped_2014_df.groupby(['pitcher', 'player_name', 'season', 'pitch_type'])['count_by_pitch_type'].sum().reset_index(name='season_total_count_by_pitch_type')

# Weighted Averages Calculation Setup
weighted_avg_columns = ['release_speed', 'release_pos_x', 'release_pos_z', 'vx0', 'vy0', 'vz0', 'ax', 'ay', 'az', 'release_pos_y']
for col in weighted_avg_columns:
    grouped_2014_df[f'{col}_product'] = grouped_2014_df[col] * grouped_2014_df['count_by_pitch_type']

weighted_avg_aggregations = {f'{col}_product': 'sum' for col in weighted_avg_columns}
weighted_avg_aggregations['count_by_pitch_type'] = 'sum'

# Aggregate for weighted averages
weighted_avg_df = grouped_2014_df.groupby(['pitcher', 'player_name', 'season', 'pitch_type']).agg(weighted_avg_aggregations).reset_index()

# Calculate weighted averages
for col in weighted_avg_columns:
    weighted_avg_df[f'{col}_weighted_avg'] = weighted_avg_df[f'{col}_product'] / weighted_avg_df['count_by_pitch_type']

# Cleanup
weighted_avg_df.drop(columns=[f'{col}_product' for col in weighted_avg_columns], inplace=True)

# Merge season totals and weighted averages
final_2014_df = pd.merge(season_total_pitches, season_total_by_pitch_type, on=['pitcher', 'player_name', 'season'])
final_2014_df = pd.merge(final_2014_df, weighted_avg_df, on=['pitcher', 'player_name', 'season', 'pitch_type'])

final_2014_df.head()
"""

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,112526,"Colon, Bartolo",2014,12322,CH,169,169,81.982249,-1.368047,5.746213,4.308327,-120.124693,-3.071392,-10.751509,24.318225,-24.679645,54.5
1,112526,"Colon, Bartolo",2014,12322,FF,856,856,91.296612,-0.983995,5.965993,3.258273,-133.873215,-4.778564,-7.696817,30.512959,-16.409695,54.5
2,112526,"Colon, Bartolo",2014,12322,IN,12,12,77.458333,-1.578333,6.704167,1.327522,-113.545854,1.362851,-4.324000,22.426583,-23.358083,54.5
3,112526,"Colon, Bartolo",2014,12322,SI,1604,1604,88.284663,-1.360436,5.729395,6.062267,-129.407230,-2.437539,-14.784560,28.458998,-24.712448,54.5
4,112526,"Colon, Bartolo",2014,12322,SL,368,368,82.933424,-1.492880,5.816060,2.996842,-121.513007,-1.778457,2.501505,23.276842,-30.190533,54.5

In [144]:
"""
final_2014_df['player_name'] = final_2014_df['player_name'].str.lower().str.strip().str.replace(r'\*$', '', regex=True)
final_2014_df.head()
"""

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,112526,"colon, bartolo",2014,12322,CH,169,169,81.982249,-1.368047,5.746213,4.308327,-120.124693,-3.071392,-10.751509,24.318225,-24.679645,54.5
1,112526,"colon, bartolo",2014,12322,FF,856,856,91.296612,-0.983995,5.965993,3.258273,-133.873215,-4.778564,-7.696817,30.512959,-16.409695,54.5
2,112526,"colon, bartolo",2014,12322,IN,12,12,77.458333,-1.578333,6.704167,1.327522,-113.545854,1.362851,-4.324000,22.426583,-23.358083,54.5
3,112526,"colon, bartolo",2014,12322,SI,1604,1604,88.284663,-1.360436,5.729395,6.062267,-129.407230,-2.437539,-14.784560,28.458998,-24.712448,54.5
4,112526,"colon, bartolo",2014,12322,SL,368,368,82.933424,-1.492880,5.816060,2.996842,-121.513007,-1.778457,2.501505,23.276842,-30.190533,54.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1447,628333,"despaigne, odrisamer",2014,10794,FC,170,170,90.731765,-0.940824,5.620941,2.659235,-133.028386,-2.780620,2.355788,27.781218,-21.670200,54.5
1448,628333,"despaigne, odrisamer",2014,10794,FF,160,160,90.847500,-1.019937,5.609750,3.240544,-133.183353,-2.872252,-2.689206,27.997956,-21.176269,54.5
1449,628333,"despaigne, odrisamer",2014,10794,PO,1,1,82.600000,-1.390000,5.800000,-1.338126,-121.038846,1.886275,3.649000,22.084000,-28.797000,54.5
1450,628333,"despaigne, odrisamer",2014,10794,SI,504,504,91.106746,-1.171012,5.338492,5.123018,-133.558323,-1.984598,-12.197629,29.168544,-24.645337,54.5
1451,628333,"despaigne, odrisamer",2014,10794,SL,247,247,86.591093,-1.056640,5.614899,3.401851,-126.864869,-1.999890,4.085150,24.169231,-25.659320,54.5

In [145]:
#print(final_2014_df['player_name'].unique())

['colon, bartolo' 'hawkins, latroy' 'wright, jamey' 'chen, bruce'
 'wolf, randy' 'nathan, joe' 'burnett, a.j.' 'penny, brad' 'hudson, tim'
 'downs, scott' 'arroyo, bronson' 'benoit, joaquÃ­n' 'beckett, josh'
 'belisle, matt' 'buehrle, mark' 'sabathia, cc' 'vogelsong, ryan'
 'dickey, r.a.' 'affeldt, jeremy' 'lohse, kyle' 'lackey, john'
 'de la rosa, jorge' 'bedard, erik' 'lewis, colby' 'peavy, jake'
 'harang, aaron' 'pÃ©rez, oliver' 'guthrie, jeremy' 'williams, jerome'
 'capuano, chris' 'wainwright, adam' 'greinke, zack' 'floyd, gavin'
 'haren, dan' 'jackson, edwin' 'santana, ervin' 'correia, kevin'
 'simon, alfredo' 'mcgowan, dustin' 'germano, justin' 'maholm, paul'
 'cain, matt' 'hamels, cole' 'kazmir, scott' 'stauffer, tim'
 'young, chris' 'danks, john' 'hernandez, roberto' 'francis, jeff'
 'hernÃ¡ndez, fÃ©lix' 'petit, yusmeiro' 'verlander, justin'
 'liriano, francisco' 'saunders, joe' 'jimÃ©nez, ubaldo' 'hammel, jason'
 'rodriguez, wandy' 'sÃ¡nchez, anÃ­bal' 'rowland-smith, ryan' 'duke, zach'
 'mccarthy, brandon' 'feldman, scott' 'nolasco, ricky' 'marshall, sean'
 'stults, eric' 'chavez, jesse' 'eveland, dana' 'detwiler, ross'
 'kluber, corey' 'cecil, brett' 'parra, manny' 'hill, rich'
 'shields, james' 'garcÃ­a, jaime' 'harrell, lucas' 'volquez, edinson'
 'vargas, jason' 'weaver, jered' 'wilson, c.j.' 'fister, doug'
 'matusz, brian' 'davis, wade' 'gallardo, yovani' 'lester, jon'
 'kendrick, kyle' 'gorzelanny, tom' 'kennedy, ian' 'miller, andrew'
 'wright, steven' 'leblanc, wade' 'scherzer, max' 'huff, david'
 'lincecum, tim' 'buchholz, clay' 'morrow, brandon' 'arrieta, jake'
 'villanueva, carlos' 'price, david' 'sÃ¡nchez, jonathan' 'noesÃ­, hector'
 'cueto, johnny' 'bailey, homer' 'harrison, matt' 'jurrjens, jair'
 "o'sullivan, sean" 'happ, j.a.' 'lynn, lance' 'tomlin, josh'
 'lannan, john' 'slowey, kevin' 'humber, philip' 'pelfrey, mike'
 'gonzÃ¡lez, gio' 'hughes, phil' 'swarzak, anthony' 'hanson, tommy'
 'estrada, marco' 'paulino, felipe' 'morales, franklin' 'doubront, felix'
 'nova, ivÃ¡n' 'ogando, alexi' 'chacÃ­n, jhoulys' 'rogers, esmil'
 'carrasco, carlos' 'anderson, brett' 'worley, vance' 'ross, tyson'
 'drabek, kyle' 'wood, travis' 'masterson, justin' 'phelps, david'
 'hellickson, jeremy' 'niese, jonathon' 'kershaw, clayton'
 'cashner, andrew' 'duensing, brian' 'hunter, tommy' 'miley, wade'
 'stammen, craig' 'garza, matt' 'kuroda, hiroki' 'matsuzaka, daisuke'
 'quintana, jose' 'pineda, michael' 'tillman, chris' 'minor, mike'
 'latos, mat' 'norris, bud' 'archer, chris' 'gibson, kyle' 'locke, jeff'
 'mcallister, zach' 'cobb, alex' 'samardzija, jeff' 'leake, mike'
 'cahill, trevor' 'santiago, hÃ©ctor' 'anderson, chase' 'holland, derek'
 'peacock, brad' 'peralta, wily' 'nicasio, juan' 'darvish, yu'
 'alvarez iii, henderson' 'delgado, randall' 'salazar, danny'
 'bettis, chad' 'bumgarner, madison' 'collmenter, josh' 'duffy, danny'
 'gee, dillon' 'moore, matt' 'nelson, jimmy' 'oberholtzer, brett'
 'pomeranz, drew' 'porcello, rick' 'sale, chris' 'zimmermann, jordan'
 'de la rosa, rubby' 'pÃ©rez, martÃ­n' 'teheran, julio' 'shoemaker, matt'
 'chatwood, tyler' 'cole, gerrit' 'cosart, jarred' 'desclafani, anthony'
 'eovaldi, nathan' 'gray, sonny' 'hendricks, kyle' 'hudson, daniel'
 'koehler, tom' 'lyles, jordan' 'mchugh, collin' 'milone, tommy'
 'odorizzi, jake' 'roark, tanner' 'strasburg, stephen' 'bauer, trevor'
 'turner, jacob' 'iwakuma, hisashi' 'tanaka, masahiro' 'ryu, hyun jin'
 'wheeler, zack' 'ventura, yordano' 'alvarez, r.j.' 'fiers, mike'
 'heaney, andrew' 'hutchison, drew' 'mikolas, miles' 'miller, shelby'
 'paxton, james' 'richards, garrett' 'skaggs, tyler' 'erlin, robbie'
 'keuchel, dallas' 'nuÃ±o, vidal' 'straily, dan' 'stroman, marcus'
 'foltynewicz, mike' 'gausman, kevin' 'ray, robbie' 'sanchez, aaron'
 'smyly, drew' 'walker, taijuan' 'degrom, jacob' 'gonzales, marco'
 'norris, daniel' 'bassitt, chris' 'wisler, matt' 'elÃ­as, roenis'
 'wacha, michael' 'graveman, kendall' 'chen, wei-yin' 'wood, alex'
 'despaigne, odrisamer']

In [146]:
"""
def remove_accents(input_str):
    nfkd_form = unicodedata.normalize('NFKD', input_str)
    return "".join([c for c in nfkd_form if not unicodedata.combining(c)])

def clean_name(name):
    name = name.lower()
    name = remove_accents(name)
    name = re.sub(r'[-.]', '', name)
    name = re.sub(r'\s+', ' ', name).strip()
    return name

final_2014_df['player_name'] = final_2014_df['player_name'].apply(clean_name)
"""

In [147]:
"""
# Convert 'player_name' from "last name, first name" to "first name last name"
final_2014_df['Name'] = final_2014_df['player_name'].apply(lambda x: ' '.join(x.split(', ')[::-1]))
"""

In [148]:
"""
# Now, you can perform the merge using 'Name' and 'season' as the keys for both DataFrames
better_2014_df = pd.merge(final_2014_df, 
                          cleaning_filtered_df[['Name', 'season', 'Age']],
                          on=['Name', 'season'],
                          how='left')
"""

In [151]:
#better_2014_df.head()

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg,Name,Age
0,112526,"colon, bartolo",2014,12322,CH,169,169,81.982249,-1.368047,5.746213,4.308327,-120.124693,-3.071392,-10.751509,24.318225,-24.679645,54.5,bartolo colon,41.0
1,112526,"colon, bartolo",2014,12322,FF,856,856,91.296612,-0.983995,5.965993,3.258273,-133.873215,-4.778564,-7.696817,30.512959,-16.409695,54.5,bartolo colon,41.0
2,112526,"colon, bartolo",2014,12322,IN,12,12,77.458333,-1.578333,6.704167,1.327522,-113.545854,1.362851,-4.324000,22.426583,-23.358083,54.5,bartolo colon,41.0
3,112526,"colon, bartolo",2014,12322,SI,1604,1604,88.284663,-1.360436,5.729395,6.062267,-129.407230,-2.437539,-14.784560,28.458998,-24.712448,54.5,bartolo colon,41.0
4,112526,"colon, bartolo",2014,12322,SL,368,368,82.933424,-1.492880,5.816060,2.996842,-121.513007,-1.778457,2.501505,23.276842,-30.190533,54.5,bartolo colon,41.0

In [152]:
#better_2014_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1497 entries, 0 to 1496
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   pitcher                           1497 non-null   int64
 1   player_name                       1497 non-null   object
 2   season                            1497 non-null   int32
 3   season_total_pitches              1497 non-null   int64
 4   pitch_type                        1497 non-null   object
 5   season_total_count_by_pitch_type  1497 non-null   int64
 6   count_by_pitch_type               1497 non-null   int64
 7   release_speed_weighted_avg        1497 non-null   float64
 8   release_pos_x_weighted_avg        1497 non-null   float64
 9   release_pos_z_weighted_avg        1497 non-null   float64
 10  vx0_weighted_avg                  1497 non-null   float64
 11  vy0_weighted_avg                  1497 non-null   float64
 12  vz0_weighted_avg                  1497 non-null   float64
 13  ax_weighted_avg                   1497 non-null   float64
 14  ay_weighted_avg                   1497 non-null   float64
 15  az_weighted_avg                   1497 non-null   float64
 16  release_pos_y_weighted_avg        1497 non-null   float64
 17  Name                              1497 non-null   object
 18  Age                               1297 non-null   float64
dtypes: float64(11), int32(1), int64(4), object(3)
memory usage: 216.5+ KB

In [153]:
#better_2014_df.to_csv('data/better_2014_df.csv')

2015

In [154]:
#all_2015_stats_df = pd.read_csv('~/Documents/Flatiron/Project_5_/data/all_2015_stats_df.csv', index_col=0)

In [155]:
"""
all_2015_stats_df.drop(columns=['batter', 'events', 'description', 'zone',
                                'des', 'game_type', 'stand', 'home_team',
                                'away_team', 'type', 'hit_location', 'bb_type',
                                'balls', 'strikes', 'pfx_x', 'spin_dir', 
                                'pfx_z', 'plate_x', 'plate_z', 'on_3b',
                                'on_2b', 'on_1b', 'outs_when_up', 'inning',
                                'inning_topbot', 'hc_x', 'hc_y', 'fielder_2',
                                'umpire', 'sv_id', 'hit_distance_sc', 'sz_top',
                                 'sz_bot', 'launch_speed', 'launch_angle', 'game_pk',
                                'pitcher.1', 'fielder_2.1', 'fielder_3', 'fielder_4',
                                'fielder_5', 'fielder_6', 'fielder_7', 'fielder_8',
                                'fielder_9', 'estimated_ba_using_speedangle',
                                'estimated_woba_using_speedangle', 'babip_value',
                                'launch_speed_angle', 'woba_value', 'woba_denom', 'iso_value', 
                                'at_bat_number', 'pitch_number', 'home_score', 'away_score',
                                'bat_score', 'fld_score', 'post_home_score', 'post_bat_score',
                                'post_fld_score', 'post_away_score', 'if_fielding_alignment',
                                'of_fielding_alignment', 'delta_home_win_exp',
                                'delta_run_exp', 'spin_rate_deprecated', 'break_angle_deprecated',
                               'break_length_deprecated', 'tfs_deprecated', 'tfs_zulu_deprecated'], inplace=True)
all_2015_stats_df.head()
"""

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,...,vz0,ax,ay,az,effective_speed,release_spin_rate,release_extension,release_pos_y,pitch_name,spin_axis
0,FF,2015-10-03,92.8,-1.30,6.52,"Hawkins, LaTroy",115629,R,2015,2.910646,...,-5.157683,-7.86,32.65,-13.64,92.2,2101.0,6.0,54.5,4-Seam Fastball,NaN
1,FF,2015-10-03,92.2,-1.05,6.71,"Hawkins, LaTroy",115629,R,2015,1.457997,...,-3.692584,-9.23,30.27,-11.61,91.8,2081.0,5.8,54.5,4-Seam Fastball,NaN
2,SL,2015-10-03,86.8,-1.79,6.49,"Hawkins, LaTroy",115629,R,2015,2.750832,...,-1.547203,4.77,26.28,-26.02,86.0,2271.0,5.6,54.5,Slider,NaN
3,SL,2015-09-30,86.0,-1.75,6.31,"Hawkins, LaTroy",115629,R,2015,4.593156,...,-0.169906,0.47,22.39,-26.51,NaN,NaN,NaN,54.5,Slider,NaN
4,FF,2015-09-30,94.1,-1.74,6.29,"Hawkins, LaTroy",115629,R,2015,7.644291,...,-7.824999,-13.82,25.83,-20.23,94.2,2143.0,6.0,54.5,4-Seam Fastball,NaN

In [156]:
"""
all_2015_stats_df.drop(columns=['spin_axis', 'effective_speed',
                               'release_spin_rate', 'release_extension'], inplace=True)
"""

In [157]:
#all_2015_stats_df = all_2015_stats_df.dropna(axis=0)

In [158]:
#all_2015_stats_df.reset_index(inplace=True)

In [159]:
#all_2015_stats_df.drop('index', axis=1)

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,vy0,vz0,ax,ay,az,release_pos_y,pitch_name
0,FF,2015-10-03,92.8,-1.30,6.52,"Hawkins, LaTroy",115629,R,2015,2.910646,-136.242708,-5.157683,-7.860,32.650,-13.640,54.5,4-Seam Fastball
1,FF,2015-10-03,92.2,-1.05,6.71,"Hawkins, LaTroy",115629,R,2015,1.457997,-135.360085,-3.692584,-9.230,30.270,-11.610,54.5,4-Seam Fastball
2,SL,2015-10-03,86.8,-1.79,6.49,"Hawkins, LaTroy",115629,R,2015,2.750832,-127.352018,-1.547203,4.770,26.280,-26.020,54.5,Slider
3,SL,2015-09-30,86.0,-1.75,6.31,"Hawkins, LaTroy",115629,R,2015,4.593156,-125.962437,-0.169906,0.470,22.390,-26.510,54.5,Slider
4,FF,2015-09-30,94.1,-1.74,6.29,"Hawkins, LaTroy",115629,R,2015,7.644291,-137.319084,-7.824999,-13.820,25.830,-20.230,54.5,4-Seam Fastball
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421311,SI,2015-04-07,90.3,1.94,5.71,"Wood, Alex",622072,L,2015,-8.389336,-132.283438,-4.005885,15.737,28.802,-16.902,54.5,Sinker
421312,SI,2015-04-07,90.4,2.42,5.47,"Wood, Alex",622072,L,2015,-8.822553,-132.443264,-0.603969,20.539,29.971,-23.778,54.5,Sinker
421313,SI,2015-04-07,91.3,2.33,5.45,"Wood, Alex",622072,L,2015,-8.638980,-133.890635,-0.352208,20.152,31.285,-18.635,54.5,Sinker
421314,SI,2015-04-07,89.7,2.22,5.55,"Wood, Alex",622072,L,2015,-10.096027,-131.406017,-1.991848,19.489,29.960,-17.602,54.5,Sinker
421315,SI,2015-04-07,90.4,2.42,5.63,"Wood, Alex",622072,L,2015,-8.763492,-132.440437,-2.996016,17.249,31.844,-17.791,54.5,Sinker

In [160]:
"""
# Group by 'game_date' and 'pitcher' to calculate the total pitches
total_pitches = all_2015_stats_df.groupby(['game_date', 'pitcher', 'player_name']).size().reset_index(name='total_pitches')

# Group by 'game_date', 'pitcher', and 'pitch_type' to calculate the sum total of each pitch_type
total_pitches_by_type = all_2015_stats_df.groupby(['game_date', 'pitcher', 'player_name', 'pitch_type']).size().reset_index(name='count_by_pitch_type')

# Calculate averages of the specified metrics for each pitch type, grouped by game_date and pitcher
avg_metrics = all_2015_stats_df.groupby(['game_date', 'pitcher', 'player_name', 'pitch_type']).agg({
    'release_speed': 'mean',
    'release_pos_x': 'mean',
    'release_pos_z': 'mean',
    'vx0': 'mean',
    'vy0': 'mean',
    'vz0': 'mean',
    'ax': 'mean',
    'ay': 'mean',
    'az': 'mean',
    'release_pos_y': 'mean',
}).reset_index()

grouped_2015_df = total_pitches.merge(total_pitches_by_type, on=['game_date', 'pitcher', 'player_name'], how='left')
grouped_2015_df = grouped_2015_df.merge(avg_metrics, on=['game_date', 'pitcher', 'player_name', 'pitch_type'], how='left')

grouped_2015_df.head()
"""

,game_date,pitcher,player_name,total_pitches,pitch_type,count_by_pitch_type,release_speed,release_pos_x,release_pos_z,vx0,vy0,vz0,ax,ay,az,release_pos_y
0,2015-04-05,425794,"Wainwright, Adam",101,CH,2,83.700000,-1.565000,6.355000,4.110753,-122.596737,-4.763452,-15.036500,26.077000,-21.766500,54.5
1,2015-04-05,425794,"Wainwright, Adam",101,CU,26,75.923077,-1.240769,6.465385,1.074650,-111.564295,0.232395,9.587154,24.904231,-43.822500,54.5
2,2015-04-05,425794,"Wainwright, Adam",101,FC,46,86.595652,-1.290652,6.386522,2.959222,-126.849028,-3.858584,2.711304,24.728717,-21.809522,54.5
3,2015-04-05,425794,"Wainwright, Adam",101,FF,23,89.934783,-1.211739,6.337826,3.879729,-131.770938,-5.928504,-3.950652,28.696696,-15.493348,54.5
4,2015-04-05,425794,"Wainwright, Adam",101,SI,4,89.375000,-1.552500,6.192500,3.891508,-130.961497,-5.864665,-15.370500,30.101750,-18.661250,54.5

In [161]:
"""
grouped_2015_df['game_date'] = pd.to_datetime(grouped_2015_df['game_date'])
grouped_2015_df['season'] = grouped_2015_df['game_date'].dt.year

# Step 1: Season Total Pitches
season_total_pitches = grouped_2015_df.groupby(['pitcher', 'player_name', 'season'])['total_pitches'].sum().reset_index(name='season_total_pitches')

# Step 2: Season Total by Pitch Type
season_total_by_pitch_type = grouped_2015_df.groupby(['pitcher', 'player_name', 'season', 'pitch_type'])['count_by_pitch_type'].sum().reset_index(name='season_total_count_by_pitch_type')

# Weighted Averages Calculation Setup
weighted_avg_columns = ['release_speed', 'release_pos_x', 'release_pos_z', 'vx0', 'vy0', 'vz0', 'ax', 'ay', 'az', 'release_pos_y']
for col in weighted_avg_columns:
    grouped_2015_df[f'{col}_product'] = grouped_2015_df[col] * grouped_2015_df['count_by_pitch_type']

weighted_avg_aggregations = {f'{col}_product': 'sum' for col in weighted_avg_columns}
weighted_avg_aggregations['count_by_pitch_type'] = 'sum'

# Aggregate for weighted averages
weighted_avg_df = grouped_2015_df.groupby(['pitcher', 'player_name', 'season', 'pitch_type']).agg(weighted_avg_aggregations).reset_index()

# Calculate weighted averages
for col in weighted_avg_columns:
    weighted_avg_df[f'{col}_weighted_avg'] = weighted_avg_df[f'{col}_product'] / weighted_avg_df['count_by_pitch_type']

# Cleanup
weighted_avg_df.drop(columns=[f'{col}_product' for col in weighted_avg_columns], inplace=True)

# Merge season totals and weighted averages
final_2015_df = pd.merge(season_total_pitches, season_total_by_pitch_type, on=['pitcher', 'player_name', 'season'])
final_2015_df = pd.merge(final_2015_df, weighted_avg_df, on=['pitcher', 'player_name', 'season', 'pitch_type'])

final_2015_df.head()
"""

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,112526,"Colon, Bartolo",2015,11167,CH,198,198,82.575253,-1.116010,5.771162,3.988420,-121.018971,-2.524315,-11.181924,24.366253,-24.565975,54.5
1,112526,"Colon, Bartolo",2015,11167,CU,8,8,81.500000,-1.203750,5.830000,3.027948,-119.430580,-2.577242,-6.046375,23.580375,-25.580125,54.5
2,112526,"Colon, Bartolo",2015,11167,FF,782,782,90.857928,-0.777877,5.916445,2.964820,-133.232028,-4.462022,-7.249721,29.682963,-16.367662,54.5
3,112526,"Colon, Bartolo",2015,11167,IN,20,20,76.125000,-0.925000,6.778000,5.012334,-111.364646,1.348100,-4.298600,20.510850,-22.432900,54.5
4,112526,"Colon, Bartolo",2015,11167,SI,1435,1435,87.849199,-1.124955,5.706390,5.458330,-128.786887,-2.366847,-14.909735,28.100541,-24.850339,54.5

In [162]:
"""
final_2015_df['player_name'] = final_2015_df['player_name'].str.lower().str.strip().str.replace(r'\*$', '', regex=True)
final_2015_df.head()
"""

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,112526,"colon, bartolo",2015,11167,CH,198,198,82.575253,-1.116010,5.771162,3.988420,-121.018971,-2.524315,-11.181924,24.366253,-24.565975,54.5
1,112526,"colon, bartolo",2015,11167,CU,8,8,81.500000,-1.203750,5.830000,3.027948,-119.430580,-2.577242,-6.046375,23.580375,-25.580125,54.5
2,112526,"colon, bartolo",2015,11167,FF,782,782,90.857928,-0.777877,5.916445,2.964820,-133.232028,-4.462022,-7.249721,29.682963,-16.367662,54.5
3,112526,"colon, bartolo",2015,11167,IN,20,20,76.125000,-0.925000,6.778000,5.012334,-111.364646,1.348100,-4.298600,20.510850,-22.432900,54.5
4,112526,"colon, bartolo",2015,11167,SI,1435,1435,87.849199,-1.124955,5.706390,5.458330,-128.786887,-2.366847,-14.909735,28.100541,-24.850339,54.5

In [163]:
#print(final_2015_df['player_name'].unique())

['colon, bartolo' 'hawkins, latroy' 'chen, bruce' 'wolf, randy'
 'nathan, joe' 'marquis, jason' 'burnett, a.j.' 'zito, barry'
 'hudson, tim' 'benoit, joaquÃ­n' 'belisle, matt' 'buehrle, mark'
 'sabathia, cc' 'vogelsong, ryan' 'dickey, r.a.' 'affeldt, jeremy'
 'lohse, kyle' 'lackey, john' 'de la rosa, jorge' 'lewis, colby'
 'peavy, jake' 'harang, aaron' 'pÃ©rez, oliver' 'guthrie, jeremy'
 'williams, jerome' 'capuano, chris' 'wainwright, adam' 'greinke, zack'
 'floyd, gavin' 'haren, dan' 'jackson, edwin' 'santana, ervin'
 'narveson, chris' 'correia, kevin' 'simon, alfredo' 'blanton, joe'
 'mcgowan, dustin' 'cain, matt' 'hamels, cole' 'kazmir, scott'
 'stauffer, tim' 'young, chris' 'danks, john' 'hernandez, roberto'
 'francis, jeff' 'hernÃ¡ndez, fÃ©lix' 'petit, yusmeiro' 'verlander, justin'
 'liriano, francisco' 'jimÃ©nez, ubaldo' 'hammel, jason' 'rodriguez, wandy'
 'sÃ¡nchez, anÃ­bal' 'davies, kyle' 'duke, zach' 'mccarthy, brandon'
 'laffey, aaron' 'feldman, scott' 'nolasco, ricky' 'stults, eric'
 'chavez, jesse' 'eveland, dana' 'detwiler, ross' 'kluber, corey'
 'cecil, brett' 'parra, manny' 'hill, rich' 'shields, james'
 'garcÃ­a, jaime' 'guerra, junior' 'volquez, edinson' 'vargas, jason'
 'weaver, jered' 'wilson, c.j.' 'medlen, kris' 'fister, doug'
 'matusz, brian' 'billingsley, chad' 'davis, wade' 'gallardo, yovani'
 'marcum, shaun' 'lester, jon' 'kendrick, kyle' 'gorzelanny, tom'
 'kennedy, ian' 'miller, andrew' 'wright, steven' 'scherzer, max'
 'huff, david' 'lincecum, tim' 'buchholz, clay' 'morrow, brandon'
 'richard, clayton' 'arrieta, jake' 'villanueva, carlos' 'ohlendorf, ross'
 'price, david' 'noesÃ­, hector' 'cueto, johnny' 'bailey, homer'
 'harrison, matt' 'reyes, jo-jo' "o'sullivan, sean" 'happ, j.a.'
 'lynn, lance' 'volstad, chris' 'tomlin, josh' 'hochevar, luke'
 'pelfrey, mike' 'gonzÃ¡lez, gio' 'hughes, phil' 'swarzak, anthony'
 'estrada, marco' 'morales, franklin' 'doubront, felix' 'nova, ivÃ¡n'
 'ogando, alexi' 'chacÃ­n, jhoulys' 'rogers, esmil' 'carrasco, carlos'
 'anderson, brett' 'worley, vance' 'ross, tyson' 'drabek, kyle'
 'wood, travis' 'masterson, justin' 'phelps, david' 'hellickson, jeremy'
 'niese, jonathon' 'kershaw, clayton' 'cashner, andrew' 'duensing, brian'
 'hunter, tommy' 'miley, wade' 'stammen, craig' 'garza, matt'
 'quintana, jose' 'pineda, michael' 'tillman, chris' 'latos, mat'
 'norris, bud' 'archer, chris' 'gibson, kyle' 'locke, jeff'
 'mcallister, zach' 'samardzija, jeff' 'leake, mike' 'cahill, trevor'
 'santiago, hÃ©ctor' 'anderson, chase' 'holland, derek' 'peacock, brad'
 'peralta, wily' 'nicasio, juan' 'alvarez iii, henderson'
 'delgado, randall' 'salazar, danny' 'bettis, chad' 'bumgarner, madison'
 'collmenter, josh' 'duffy, danny' 'gee, dillon' 'harvey, matt'
 'moore, matt' 'nelson, jimmy' 'oberholtzer, brett' 'pomeranz, drew'
 'porcello, rick' 'sale, chris' 'zimmermann, jordan' 'de la rosa, rubby'
 'pÃ©rez, martÃ­n' 'teheran, julio' 'shoemaker, matt' 'andriese, matt'
 'cole, gerrit' 'cosart, jarred' 'desclafani, anthony' 'eovaldi, nathan'
 'gray, sonny' 'hendricks, kyle' 'hudson, daniel' 'koehler, tom'
 'lyles, jordan' 'mchugh, collin' 'milone, tommy' 'montgomery, mike'
 'odorizzi, jake' 'roark, tanner' 'strasburg, stephen' 'bauer, trevor'
 'beachy, brandon' 'lorenzen, michael' 'iwakuma, hisashi'
 'tanaka, masahiro' 'ureÃ±a, josÃ©' 'ventura, yordano' 'alvarez, r.j.'
 'boyd, matthew' 'corbin, patrick' 'fiers, mike' 'heaney, andrew'
 'hutchison, drew' 'matz, steven' 'miller, shelby' 'paxton, james'
 'richards, garrett' 'erlin, robbie' 'keuchel, dallas' 'nuÃ±o, vidal'
 'straily, dan' 'stroman, marcus' 'foltynewicz, mike' 'gausman, kevin'
 'gray, jon' 'ray, robbie' 'sanchez, aaron' 'smyly, drew'
 'syndergaard, noah' 'velasquez, vince' 'walker, taijuan'
 'montas, frankie' 'rodriguez, eduardo' 'degrom, jacob' 'gonzales, marco'
 'eickhoff, jerad' 'norris, daniel' 'bassitt, chris' 'davies, zach'
 'houser, adrian' 'lÃ³pez, jorge' 'nola, aaron' 'ross, joe' 'wisler, matt'
 'elÃ­as, roenis' 'rodÃ³n, carlos' 'wacha, michael' 'graveman, kendall'
 'chen, wei-yin' 'mccullers jr., lance' 'wood, alex' 'severino, luis'
 'despaigne, odrisamer' 'godley, zack']

In [164]:
"""
def remove_accents(input_str):
    nfkd_form = unicodedata.normalize('NFKD', input_str)
    return "".join([c for c in nfkd_form if not unicodedata.combining(c)])

def clean_name(name):
    name = name.lower()
    name = remove_accents(name)
    name = re.sub(r'[-.]', '', name)
    name = re.sub(r'\s+', ' ', name).strip()
    return name

final_2015_df['player_name'] = final_2015_df['player_name'].apply(clean_name)
"""

In [165]:
"""
# Convert 'player_name' from "last name, first name" to "first name last name"
final_2015_df['Name'] = final_2015_df['player_name'].apply(lambda x: ' '.join(x.split(', ')[::-1]))
"""

In [166]:
"""
# Now, you can perform the merge using 'Name' and 'season' as the keys for both DataFrames
better_2015_df = pd.merge(final_2015_df, 
                          cleaning_filtered_df[['Name', 'season', 'Age']],
                          on=['Name', 'season'],
                          how='left')
"""

In [167]:
#better_2015_df.head()

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg,Name,Age
0,112526,"colon, bartolo",2015,11167,CH,198,198,82.575253,-1.116010,5.771162,3.988420,-121.018971,-2.524315,-11.181924,24.366253,-24.565975,54.5,bartolo colon,42.0
1,112526,"colon, bartolo",2015,11167,CU,8,8,81.500000,-1.203750,5.830000,3.027948,-119.430580,-2.577242,-6.046375,23.580375,-25.580125,54.5,bartolo colon,42.0
2,112526,"colon, bartolo",2015,11167,FF,782,782,90.857928,-0.777877,5.916445,2.964820,-133.232028,-4.462022,-7.249721,29.682963,-16.367662,54.5,bartolo colon,42.0
3,112526,"colon, bartolo",2015,11167,IN,20,20,76.125000,-0.925000,6.778000,5.012334,-111.364646,1.348100,-4.298600,20.510850,-22.432900,54.5,bartolo colon,42.0
4,112526,"colon, bartolo",2015,11167,SI,1435,1435,87.849199,-1.124955,5.706390,5.458330,-128.786887,-2.366847,-14.909735,28.100541,-24.850339,54.5,bartolo colon,42.0

In [168]:
#better_2015_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1475 entries, 0 to 1474
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   pitcher                           1475 non-null   int64
 1   player_name                       1475 non-null   object
 2   season                            1475 non-null   int32
 3   season_total_pitches              1475 non-null   int64
 4   pitch_type                        1475 non-null   object
 5   season_total_count_by_pitch_type  1475 non-null   int64
 6   count_by_pitch_type               1475 non-null   int64
 7   release_speed_weighted_avg        1475 non-null   float64
 8   release_pos_x_weighted_avg        1475 non-null   float64
 9   release_pos_z_weighted_avg        1475 non-null   float64
 10  vx0_weighted_avg                  1475 non-null   float64
 11  vy0_weighted_avg                  1475 non-null   float64
 12  vz0_weighted_avg                  1475 non-null   float64
 13  ax_weighted_avg                   1475 non-null   float64
 14  ay_weighted_avg                   1475 non-null   float64
 15  az_weighted_avg                   1475 non-null   float64
 16  release_pos_y_weighted_avg        1475 non-null   float64
 17  Name                              1475 non-null   object
 18  Age                               1276 non-null   float64
dtypes: float64(11), int32(1), int64(4), object(3)
memory usage: 213.3+ KB

In [169]:
#better_2015_df.to_csv('data/better_2015_df.csv')

2016

In [279]:
#all_2016_stats_df = pd.read_csv('~/Documents/Flatiron/Project_5_/data/all_2016_stats_df.csv', index_col=0)

In [280]:
"""
all_2016_stats_df.drop(columns=['batter', 'events', 'description', 'zone',
                                'des', 'game_type', 'stand', 'home_team',
                                'away_team', 'type', 'hit_location', 'bb_type',
                                'balls', 'strikes', 'pfx_x', 'spin_dir', 
                                'pfx_z', 'plate_x', 'plate_z', 'on_3b',
                                'on_2b', 'on_1b', 'outs_when_up', 'inning',
                                'inning_topbot', 'hc_x', 'hc_y', 'fielder_2',
                                'umpire', 'sv_id', 'hit_distance_sc', 'sz_top',
                                 'sz_bot', 'launch_speed', 'launch_angle', 'game_pk',
                                'pitcher.1', 'fielder_2.1', 'fielder_3', 'fielder_4',
                                'fielder_5', 'fielder_6', 'fielder_7', 'fielder_8',
                                'fielder_9', 'estimated_ba_using_speedangle',
                                'estimated_woba_using_speedangle', 'babip_value',
                                'launch_speed_angle', 'woba_value', 'woba_denom', 'iso_value', 
                                'at_bat_number', 'pitch_number', 'home_score', 'away_score',
                                'bat_score', 'fld_score', 'post_home_score', 'post_bat_score',
                                'post_fld_score', 'post_away_score', 'if_fielding_alignment',
                                'of_fielding_alignment', 'delta_home_win_exp',
                                'delta_run_exp', 'spin_rate_deprecated', 'break_angle_deprecated',
                               'break_length_deprecated', 'tfs_deprecated', 'tfs_zulu_deprecated'], inplace=True)
all_2016_stats_df.head()
"""

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,...,vz0,ax,ay,az,effective_speed,release_spin_rate,release_extension,release_pos_y,pitch_name,spin_axis
0,SI,2016-09-27,91.5,-2.44,6.38,"Nathan, Joe",150274,R,2016,8.000700,...,-7.378708,-18.031,29.546,-23.736,NaN,NaN,NaN,54.5,Sinker,NaN
1,CU,2016-09-27,80.6,-2.11,6.73,"Nathan, Joe",150274,R,2016,6.025317,...,-5.264160,1.297,21.976,-37.222,NaN,NaN,NaN,54.5,Curveball,NaN
2,FF,2016-09-27,91.5,-1.98,6.80,"Nathan, Joe",150274,R,2016,9.976650,...,-4.307363,-10.986,28.051,-14.246,NaN,NaN,NaN,54.5,4-Seam Fastball,NaN
3,FF,2016-09-27,91.4,-2.10,6.78,"Nathan, Joe",150274,R,2016,7.379398,...,-6.825156,-9.099,27.598,-13.937,NaN,NaN,NaN,54.5,4-Seam Fastball,NaN
4,CU,2016-09-27,79.3,-2.02,6.99,"Nathan, Joe",150274,R,2016,6.382383,...,-1.735432,1.609,21.647,-39.715,NaN,NaN,NaN,54.5,Curveball,NaN

In [281]:
"""
all_2016_stats_df.drop(columns=['spin_axis', 'effective_speed',
                               'release_spin_rate', 'release_extension'], inplace=True)
"""

In [282]:
#all_2016_stats_df = all_2016_stats_df.dropna(axis=0)

In [283]:
#all_2016_stats_df.reset_index(inplace=True)

In [284]:
#all_2016_stats_df.drop('index', axis=1)

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,vy0,vz0,ax,ay,az,release_pos_y,pitch_name
0,SI,2016-09-27,91.5,-2.44,6.38,"Nathan, Joe",150274,R,2016,8.000700,-133.798429,-7.378708,-18.031000,29.546000,-23.736000,54.5,Sinker
1,CU,2016-09-27,80.6,-2.11,6.73,"Nathan, Joe",150274,R,2016,6.025317,-117.894821,-5.264160,1.297000,21.976000,-37.222000,54.5,Curveball
2,FF,2016-09-27,91.5,-1.98,6.80,"Nathan, Joe",150274,R,2016,9.976650,-133.852396,-4.307363,-10.986000,28.051000,-14.246000,54.5,4-Seam Fastball
3,FF,2016-09-27,91.4,-2.10,6.78,"Nathan, Joe",150274,R,2016,7.379398,-133.666364,-6.825156,-9.099000,27.598000,-13.937000,54.5,4-Seam Fastball
4,CU,2016-09-27,79.3,-2.02,6.99,"Nathan, Joe",150274,R,2016,6.382383,-116.053425,-1.735432,1.609000,21.647000,-39.715000,54.5,Curveball
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
428307,SI,2016-04-07,92.5,1.71,5.76,"Wood, Alex",622072,L,2016,-6.219613,-135.530492,-4.310726,18.655000,28.975000,-22.036000,54.5,Sinker
428308,KC,2016-04-07,84.7,1.81,5.62,"Wood, Alex",622072,L,2016,-9.595480,-123.888874,-1.008258,-2.593000,24.083000,-39.250000,54.5,Knuckle Curve
428309,SI,2016-04-07,91.5,1.69,5.82,"Wood, Alex",622072,L,2016,-5.386997,-134.187891,0.142351,15.479000,29.202000,-18.312000,54.5,Sinker
428310,SI,2016-04-07,92.5,1.70,5.69,"Wood, Alex",622072,L,2016,-5.634911,-134.603902,-5.505187,15.570156,29.420771,-16.921047,54.5,Sinker
428311,SI,2016-04-07,92.0,1.81,5.82,"Wood, Alex",622072,L,2016,-6.087716,-134.776701,-5.169572,17.060000,29.652000,-18.991000,54.5,Sinker

In [285]:
"""
# Group by 'game_date' and 'pitcher' to calculate the total pitches
total_pitches = all_2016_stats_df.groupby(['game_date', 'pitcher', 'player_name']).size().reset_index(name='total_pitches')

# Group by 'game_date', 'pitcher', and 'pitch_type' to calculate the sum total of each pitch_type
total_pitches_by_type = all_2016_stats_df.groupby(['game_date', 'pitcher', 'player_name', 'pitch_type']).size().reset_index(name='count_by_pitch_type')

# Calculate averages of the specified metrics for each pitch type, grouped by game_date and pitcher
avg_metrics = all_2016_stats_df.groupby(['game_date', 'pitcher', 'player_name', 'pitch_type']).agg({
    'release_speed': 'mean',
    'release_pos_x': 'mean',
    'release_pos_z': 'mean',
    'vx0': 'mean',
    'vy0': 'mean',
    'vz0': 'mean',
    'ax': 'mean',
    'ay': 'mean',
    'az': 'mean',
    'release_pos_y': 'mean',
}).reset_index()

grouped_2016_df = total_pitches.merge(total_pitches_by_type, on=['game_date', 'pitcher', 'player_name'], how='left')
grouped_2016_df = grouped_2016_df.merge(avg_metrics, on=['game_date', 'pitcher', 'player_name', 'pitch_type'], how='left')

grouped_2016_df.head()
"""

,game_date,pitcher,player_name,total_pitches,pitch_type,count_by_pitch_type,release_speed,release_pos_x,release_pos_z,vx0,vy0,vz0,ax,ay,az,release_pos_y
0,2016-04-03,112526,"Colon, Bartolo",20,CH,2,81.800000,-1.335000,5.780000,4.851660,-119.787286,-2.685377,-12.956500,23.258500,-26.028000,54.5
1,2016-04-03,112526,"Colon, Bartolo",20,FF,6,90.566667,-1.003333,5.946667,2.685924,-132.855740,-5.540228,-9.709667,32.033833,-11.999333,54.5
2,2016-04-03,112526,"Colon, Bartolo",20,SI,12,88.616667,-1.270833,5.784167,7.327535,-129.838566,-3.304930,-16.743667,28.979000,-21.688833,54.5
3,2016-04-03,425794,"Wainwright, Adam",96,CH,3,84.133333,-1.760000,6.070000,4.282132,-123.264173,-2.101610,-10.890333,23.960333,-28.792000,54.5
4,2016-04-03,425794,"Wainwright, Adam",96,CU,36,75.344444,-1.593056,6.185556,0.641844,-110.670350,3.162772,14.000556,22.937000,-46.553556,54.5

In [286]:
"""
grouped_2016_df['game_date'] = pd.to_datetime(grouped_2016_df['game_date'])
grouped_2016_df['season'] = grouped_2016_df['game_date'].dt.year

# Step 1: Season Total Pitches
season_total_pitches = grouped_2016_df.groupby(['pitcher', 'player_name', 'season'])['total_pitches'].sum().reset_index(name='season_total_pitches')

# Step 2: Season Total by Pitch Type
season_total_by_pitch_type = grouped_2016_df.groupby(['pitcher', 'player_name', 'season', 'pitch_type'])['count_by_pitch_type'].sum().reset_index(name='season_total_count_by_pitch_type')

# Weighted Averages Calculation Setup
weighted_avg_columns = ['release_speed', 'release_pos_x', 'release_pos_z', 'vx0', 'vy0', 'vz0', 'ax', 'ay', 'az', 'release_pos_y']
for col in weighted_avg_columns:
    grouped_2016_df[f'{col}_product'] = grouped_2016_df[col] * grouped_2016_df['count_by_pitch_type']

weighted_avg_aggregations = {f'{col}_product': 'sum' for col in weighted_avg_columns}
weighted_avg_aggregations['count_by_pitch_type'] = 'sum'

# Aggregate for weighted averages
weighted_avg_df = grouped_2016_df.groupby(['pitcher', 'player_name', 'season', 'pitch_type']).agg(weighted_avg_aggregations).reset_index()

# Calculate weighted averages
for col in weighted_avg_columns:
    weighted_avg_df[f'{col}_weighted_avg'] = weighted_avg_df[f'{col}_product'] / weighted_avg_df['count_by_pitch_type']

# Cleanup
weighted_avg_df.drop(columns=[f'{col}_product' for col in weighted_avg_columns], inplace=True)

# Merge season totals and weighted averages
final_2016_df = pd.merge(season_total_pitches, season_total_by_pitch_type, on=['pitcher', 'player_name', 'season'])
final_2016_df = pd.merge(final_2016_df, weighted_avg_df, on=['pitcher', 'player_name', 'season', 'pitch_type'])

final_2016_df.head()
"""

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,112526,"Colon, Bartolo",2016,11394,CH,121,121,81.427273,-1.321653,5.784711,4.439384,-119.308806,-2.678639,-11.021372,23.772314,-25.065992,54.5
1,112526,"Colon, Bartolo",2016,11394,FF,736,736,90.362908,-1.011304,5.946467,3.641244,-132.476197,-4.114442,-7.403989,28.748340,-16.719015,54.5
2,112526,"Colon, Bartolo",2016,11394,IN,8,8,75.612500,-1.372500,6.567500,3.370775,-110.710903,0.906804,-5.831750,21.797125,-23.261375,54.5
3,112526,"Colon, Bartolo",2016,11394,SI,1806,1806,87.628073,-1.333738,5.740138,6.035990,-128.420235,-2.005877,-14.788935,27.310621,-24.517369,54.5
4,112526,"Colon, Bartolo",2016,11394,SL,180,180,82.450000,-1.416556,5.784167,4.403118,-120.763317,-1.426474,1.562717,22.650611,-27.994706,54.5

In [287]:
"""
final_2016_df['player_name'] = final_2016_df['player_name'].str.lower().str.strip().str.replace(r'\*$', '', regex=True)
final_2016_df.head()
"""

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,112526,"colon, bartolo",2016,11394,CH,121,121,81.427273,-1.321653,5.784711,4.439384,-119.308806,-2.678639,-11.021372,23.772314,-25.065992,54.5
1,112526,"colon, bartolo",2016,11394,FF,736,736,90.362908,-1.011304,5.946467,3.641244,-132.476197,-4.114442,-7.403989,28.748340,-16.719015,54.5
2,112526,"colon, bartolo",2016,11394,IN,8,8,75.612500,-1.372500,6.567500,3.370775,-110.710903,0.906804,-5.831750,21.797125,-23.261375,54.5
3,112526,"colon, bartolo",2016,11394,SI,1806,1806,87.628073,-1.333738,5.740138,6.035990,-128.420235,-2.005877,-14.788935,27.310621,-24.517369,54.5
4,112526,"colon, bartolo",2016,11394,SL,180,180,82.450000,-1.416556,5.784167,4.403118,-120.763317,-1.426474,1.562717,22.650611,-27.994706,54.5

In [288]:
#print(final_2016_df['player_name'].unique())

['colon, bartolo' 'nathan, joe' 'benoit, joaquÃ­n' 'belisle, matt'
 'sabathia, cc' 'vogelsong, ryan' 'dickey, r.a.' 'lohse, kyle'
 'lackey, john' 'de la rosa, jorge' 'lewis, colby' 'peavy, jake'
 'pÃ©rez, oliver' 'wang, chien-ming' 'williams, jerome' 'capuano, chris'
 'wainwright, adam' 'greinke, zack' 'floyd, gavin' 'jackson, edwin'
 'santana, ervin' 'narveson, chris' 'simon, alfredo' 'blanton, joe'
 'mcgowan, dustin' 'cain, matt' 'hamels, cole' 'kazmir, scott'
 'young, chris' 'danks, john' 'hernandez, roberto' 'hernÃ¡ndez, fÃ©lix'
 'petit, yusmeiro' 'verlander, justin' 'liriano, francisco'
 'jimÃ©nez, ubaldo' 'hammel, jason' 'sÃ¡nchez, anÃ­bal' 'duke, zach'
 'mccarthy, brandon' 'feldman, scott' 'nolasco, ricky' 'chavez, jesse'
 'eveland, dana' 'detwiler, ross' 'kluber, corey' 'cecil, brett'
 'hill, rich' 'shields, james' 'garcÃ­a, jaime' 'guerra, junior'
 'harrell, lucas' 'volquez, edinson' 'vargas, jason' 'weaver, jered'
 'medlen, kris' 'fister, doug' 'matusz, brian' 'davis, wade'
 'gallardo, yovani' 'lester, jon' 'gorzelanny, tom' 'kennedy, ian'
 'miller, andrew' 'wright, steven' 'leblanc, wade' 'scherzer, max'
 'huff, david' 'lincecum, tim' 'buchholz, clay' 'morrow, brandon'
 'richard, clayton' 'arrieta, jake' 'villanueva, carlos' 'ohlendorf, ross'
 'price, david' 'griffin, a.j.' 'cueto, johnny' 'bailey, homer'
 'reyes, jo-jo' "o'sullivan, sean" 'happ, j.a.' 'luebke, cory'
 'tomlin, josh' 'hochevar, luke' 'pelfrey, mike' 'gonzÃ¡lez, gio'
 'hughes, phil' 'swarzak, anthony' 'estrada, marco' 'morales, franklin'
 'nova, ivÃ¡n' 'ogando, alexi' 'chacÃ­n, jhoulys' 'carrasco, carlos'
 'anderson, brett' 'worley, vance' 'ross, tyson' 'drabek, kyle'
 'wood, travis' 'phelps, david' 'hellickson, jeremy' 'niese, jonathon'
 'kershaw, clayton' 'cashner, andrew' 'duensing, brian' 'hunter, tommy'
 'miley, wade' 'garza, matt' 'quintana, jose' 'pineda, michael'
 'tillman, chris' 'latos, mat' 'norris, bud' 'archer, chris'
 'gibson, kyle' 'locke, jeff' 'mcallister, zach' 'cobb, alex'
 'samardzija, jeff' 'leake, mike' 'cahill, trevor' 'santiago, hÃ©ctor'
 'anderson, chase' 'holland, derek' 'peacock, brad' 'peralta, wily'
 'nicasio, juan' 'darvish, yu' 'delgado, randall' 'salazar, danny'
 'bettis, chad' 'bumgarner, madison' 'collmenter, josh' 'duffy, danny'
 'gee, dillon' 'harvey, matt' 'moore, matt' 'nelson, jimmy'
 'oberholtzer, brett' 'pomeranz, drew' 'porcello, rick' 'sale, chris'
 'zimmermann, jordan' 'de la rosa, rubby' 'pÃ©rez, martÃ­n' 'teheran, julio'
 'shoemaker, matt' 'diamond, scott' 'anderson, tyler' 'andriese, matt'
 'chatwood, tyler' 'cole, gerrit' 'cosart, jarred' 'desclafani, anthony'
 'eovaldi, nathan' 'gray, sonny' 'hendricks, kyle' 'hudson, daniel'
 'koehler, tom' 'lyles, jordan' 'mchugh, collin' 'milone, tommy'
 'montgomery, mike' 'odorizzi, jake' 'roark, tanner' 'strasburg, stephen'
 'bauer, trevor' 'turner, jacob' 'lorenzen, michael' 'iwakuma, hisashi'
 'tanaka, masahiro' 'ryu, hyun jin' 'stripling, ross' 'ureÃ±a, josÃ©'
 'ventura, yordano' 'boyd, matthew' 'corbin, patrick' 'fiers, mike'
 'heaney, andrew' 'hutchison, drew' 'matz, steven' 'miller, shelby'
 'paxton, james' 'richards, garrett' 'skaggs, tyler' 'erlin, robbie'
 'keuchel, dallas' 'nuÃ±o, vidal' 'straily, dan' 'stroman, marcus'
 'foltynewicz, mike' 'gausman, kevin' 'gray, jon' 'ray, robbie'
 'sanchez, aaron' 'smyly, drew' 'syndergaard, noah' 'taillon, jameson'
 'velasquez, vince' 'walker, taijuan' 'williams, trevor'
 'rodriguez, eduardo' 'degrom, jacob' 'eickhoff, jerad' 'norris, daniel'
 'weaver, luke' 'bassitt, chris' 'bundy, dylan' 'clevinger, mike'
 'davies, zach' 'fulmer, michael' 'musgrove, joe' 'nola, aaron'
 'ross, joe' 'snell, blake' 'wisler, matt' 'perdomo, luis' 'elÃ­as, roenis'
 'rodÃ³n, carlos' 'glasnow, tyler' 'lugo, seth' 'giolito, lucas'
 'wacha, michael' 'mÃ¡rquez, germÃ¡n' 'graveman, kendall' 'stratton, chris'
 'suter, brent' 'chen, wei-yin' 'eflin, zach' 'mccullers jr., lance'
 'berrÃ­os, josÃ©' 'blach, ty' 'wood, alex' 'severino, luis'
 'lÃ³pez, reynaldo' 'maeda, kenta' 'despaigne, odrisamer' 'urÃ­as, julio'
 'manaea, sean' 'kuhl, chad' 'brault, steven' 'godley, zack'
 'hoffman, jeff']

In [289]:
"""
def remove_accents(input_str):
    nfkd_form = unicodedata.normalize('NFKD', input_str)
    return "".join([c for c in nfkd_form if not unicodedata.combining(c)])

def clean_name(name):
    name = name.lower()
    name = remove_accents(name)
    name = re.sub(r'[-.]', '', name)
    name = re.sub(r'\s+', ' ', name).strip()
    return name

final_2016_df['player_name'] = final_2016_df['player_name'].apply(clean_name)
"""

In [290]:
"""
# Convert 'player_name' from "last name, first name" to "first name last name"
final_2016_df['Name'] = final_2016_df['player_name'].apply(lambda x: ' '.join(x.split(', ')[::-1]))
"""

In [291]:
"""
# Now, you can perform the merge using 'Name' and 'season' as the keys for both DataFrames
better_2016_df = pd.merge(final_2016_df, 
                          cleaning_filtered_df[['Name', 'season', 'Age']],
                          on=['Name', 'season'],
                          how='left')
"""

In [292]:
#better_2016_df.to_csv('data/better_2016_df.csv')

In [184]:
#better_2016_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1475 entries, 0 to 1474
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   pitcher                           1475 non-null   int64
 1   player_name                       1475 non-null   object
 2   season                            1475 non-null   int32
 3   season_total_pitches              1475 non-null   int64
 4   pitch_type                        1475 non-null   object
 5   season_total_count_by_pitch_type  1475 non-null   int64
 6   count_by_pitch_type               1475 non-null   int64
 7   release_speed_weighted_avg        1475 non-null   float64
 8   release_pos_x_weighted_avg        1475 non-null   float64
 9   release_pos_z_weighted_avg        1475 non-null   float64
 10  vx0_weighted_avg                  1475 non-null   float64
 11  vy0_weighted_avg                  1475 non-null   float64
 12  vz0_weighted_avg                  1475 non-null   float64
 13  ax_weighted_avg                   1475 non-null   float64
 14  ay_weighted_avg                   1475 non-null   float64
 15  az_weighted_avg                   1475 non-null   float64
 16  release_pos_y_weighted_avg        1475 non-null   float64
 17  Name                              1475 non-null   object
 18  Age                               1276 non-null   float64
dtypes: float64(11), int32(1), int64(4), object(3)
memory usage: 213.3+ KB

In [185]:
#better_2016_df.head()

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg,Name,Age
0,112526,"colon, bartolo",2015,11167,CH,198,198,82.575253,-1.116010,5.771162,3.988420,-121.018971,-2.524315,-11.181924,24.366253,-24.565975,54.5,bartolo colon,42.0
1,112526,"colon, bartolo",2015,11167,CU,8,8,81.500000,-1.203750,5.830000,3.027948,-119.430580,-2.577242,-6.046375,23.580375,-25.580125,54.5,bartolo colon,42.0
2,112526,"colon, bartolo",2015,11167,FF,782,782,90.857928,-0.777877,5.916445,2.964820,-133.232028,-4.462022,-7.249721,29.682963,-16.367662,54.5,bartolo colon,42.0
3,112526,"colon, bartolo",2015,11167,IN,20,20,76.125000,-0.925000,6.778000,5.012334,-111.364646,1.348100,-4.298600,20.510850,-22.432900,54.5,bartolo colon,42.0
4,112526,"colon, bartolo",2015,11167,SI,1435,1435,87.849199,-1.124955,5.706390,5.458330,-128.786887,-2.366847,-14.909735,28.100541,-24.850339,54.5,bartolo colon,42.0

2017

In [186]:
#all_2017_stats_df = pd.read_csv('~/Documents/Flatiron/Project_5_/data/all_2017_stats_df.csv', index_col=0)

In [187]:
"""all_2017_stats_df.drop(columns=['batter', 'events', 'description', 'zone',
                                'des', 'game_type', 'stand', 'home_team',
                                'away_team', 'type', 'hit_location', 'bb_type',
                                'balls', 'strikes', 'pfx_x', 'spin_dir', 
                                'pfx_z', 'plate_x', 'plate_z', 'on_3b',
                                'on_2b', 'on_1b', 'outs_when_up', 'inning',
                                'inning_topbot', 'hc_x', 'hc_y', 'fielder_2',
                                'umpire', 'sv_id', 'hit_distance_sc', 'sz_top',
                                 'sz_bot', 'launch_speed', 'launch_angle', 'game_pk',
                                'pitcher.1', 'fielder_2.1', 'fielder_3', 'fielder_4',
                                'fielder_5', 'fielder_6', 'fielder_7', 'fielder_8',
                                'fielder_9', 'estimated_ba_using_speedangle',
                                'estimated_woba_using_speedangle', 'babip_value',
                                'launch_speed_angle', 'woba_value', 'woba_denom', 'iso_value', 
                                'at_bat_number', 'pitch_number', 'home_score', 'away_score',
                                'bat_score', 'fld_score', 'post_home_score', 'post_bat_score',
                                'post_fld_score', 'post_away_score', 'if_fielding_alignment',
                                'of_fielding_alignment', 'delta_home_win_exp',
                                'delta_run_exp', 'spin_rate_deprecated', 'break_angle_deprecated',
                               'break_length_deprecated', 'tfs_deprecated', 'tfs_zulu_deprecated'], inplace=True)
all_2017_stats_df.head()
"""

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,...,vz0,ax,ay,az,effective_speed,release_spin_rate,release_extension,release_pos_y,pitch_name,spin_axis
0,FF,2017-09-07,94.8,-2.68,6.27,"Benoit, JoaquÃ­n",276542,R,2017,9.392586,...,-5.613659,-14.702656,31.677900,-13.541176,93.6,2192.0,6.0,54.53,4-Seam Fastball,218.0
1,CH,2017-09-07,85.1,-2.84,6.10,"Benoit, JoaquÃ­n",276542,R,2017,6.034954,...,-2.543159,-15.854333,21.528776,-25.575178,85.0,1340.0,6.0,54.50,Changeup,251.0
2,FF,2017-09-07,94.7,-2.77,6.31,"Benoit, JoaquÃ­n",276542,R,2017,8.614072,...,-4.996384,-17.240459,30.795659,-12.763479,94.0,2136.0,6.1,54.40,4-Seam Fastball,222.0
3,CH,2017-09-07,85.1,-2.88,5.96,"Benoit, JoaquÃ­n",276542,R,2017,7.807054,...,-7.871553,-17.665318,23.292138,-23.765604,84.8,1571.0,6.2,54.30,Changeup,250.0
4,SI,2017-09-07,94.6,-2.73,6.25,"Benoit, JoaquÃ­n",276542,R,2017,5.766298,...,-4.858858,-17.101673,30.527648,-16.579887,93.6,2149.0,5.9,54.63,Sinker,230.0

In [188]:
"""
all_2017_stats_df.drop(columns=['spin_axis', 'effective_speed',
                               'release_spin_rate', 'release_extension'], inplace=True)
"""

In [189]:
#all_2017_stats_df = all_2017_stats_df.dropna(axis=0)

In [190]:
#all_2017_stats_df.reset_index(inplace=True)

In [191]:
#all_2017_stats_df.drop('index', axis=1)

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,vy0,vz0,ax,ay,az,release_pos_y,pitch_name
0,FF,2017-09-07,94.8,-2.68,6.27,"Benoit, JoaquÃ­n",276542,R,2017,9.392586,-137.233135,-5.613659,-14.702656,31.677900,-13.541176,54.53,4-Seam Fastball
1,CH,2017-09-07,85.1,-2.84,6.10,"Benoit, JoaquÃ­n",276542,R,2017,6.034954,-123.660884,-2.543159,-15.854333,21.528776,-25.575178,54.50,Changeup
2,FF,2017-09-07,94.7,-2.77,6.31,"Benoit, JoaquÃ­n",276542,R,2017,8.614072,-137.289711,-4.996384,-17.240459,30.795659,-12.763479,54.40,4-Seam Fastball
3,CH,2017-09-07,85.1,-2.88,5.96,"Benoit, JoaquÃ­n",276542,R,2017,7.807054,-123.288927,-7.871553,-17.665318,23.292138,-23.765604,54.30,Changeup
4,SI,2017-09-07,94.6,-2.73,6.25,"Benoit, JoaquÃ­n",276542,R,2017,5.766298,-137.181622,-4.858858,-17.101673,30.527648,-16.579887,54.63,Sinker
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413972,FF,2017-08-04,94.8,-1.18,6.08,"Woodruff, Brandon",605540,R,2017,7.155374,-137.714510,-3.221901,-11.943332,29.254469,-20.193995,53.87,4-Seam Fastball
413973,CH,2017-08-04,84.9,-1.30,6.01,"Woodruff, Brandon",605540,R,2017,2.862333,-123.464819,-4.458082,-16.599539,24.656263,-29.315716,53.87,Changeup
413974,FF,2017-08-04,95.7,-1.36,6.19,"Woodruff, Brandon",605540,R,2017,6.004405,-138.864272,-4.077824,-16.298054,30.945885,-12.216903,54.48,4-Seam Fastball
413975,FF,2017-08-04,94.7,-1.45,6.13,"Woodruff, Brandon",605540,R,2017,4.356387,-137.551434,-4.894708,-14.615018,30.857577,-18.237897,54.10,4-Seam Fastball
413976,FF,2017-08-04,93.4,-1.29,6.24,"Woodruff, Brandon",605540,R,2017,3.568693,-135.506390,-6.475282,-15.903644,30.277817,-14.956756,54.36,4-Seam Fastball

In [192]:
"""# Group by 'game_date' and 'pitcher' to calculate the total pitches
total_pitches = all_2017_stats_df.groupby(['game_date', 'pitcher', 'player_name']).size().reset_index(name='total_pitches')

# Group by 'game_date', 'pitcher', and 'pitch_type' to calculate the sum total of each pitch_type
total_pitches_by_type = all_2017_stats_df.groupby(['game_date', 'pitcher', 'player_name', 'pitch_type']).size().reset_index(name='count_by_pitch_type')

# Calculate averages of the specified metrics for each pitch type, grouped by game_date and pitcher
avg_metrics = all_2017_stats_df.groupby(['game_date', 'pitcher', 'player_name', 'pitch_type']).agg({
    'release_speed': 'mean',
    'release_pos_x': 'mean',
    'release_pos_z': 'mean',
    'vx0': 'mean',
    'vy0': 'mean',
    'vz0': 'mean',
    'ax': 'mean',
    'ay': 'mean',
    'az': 'mean',
    'release_pos_y': 'mean',
}).reset_index()

grouped_2017_df = total_pitches.merge(total_pitches_by_type, on=['game_date', 'pitcher', 'player_name'], how='left')
grouped_2017_df = grouped_2017_df.merge(avg_metrics, on=['game_date', 'pitcher', 'player_name', 'pitch_type'], how='left')

grouped_2017_df.head()
"""

,game_date,pitcher,player_name,total_pitches,pitch_type,count_by_pitch_type,release_speed,release_pos_x,release_pos_z,vx0,vy0,vz0,ax,ay,az,release_pos_y
0,2017-04-02,407822,"De La Rosa, Jorge",7,FF,4,93.825000,2.260000,5.990000,-6.607681,-135.921584,-5.623689,3.196978,30.598219,-15.917123,54.920000
1,2017-04-02,407822,"De La Rosa, Jorge",7,FS,3,84.533333,2.340000,6.150000,-8.156373,-122.196138,-7.859948,3.235173,25.261696,-26.173908,55.030000
2,2017-04-02,425844,"Greinke, Zack",91,CH,17,87.247059,-1.681176,6.166471,6.550356,-126.579763,-6.270184,-18.556959,24.337743,-23.479711,54.594706
3,2017-04-02,425844,"Greinke, Zack",91,CU,9,75.100000,-1.262222,6.281111,2.570011,-108.963546,-1.389566,1.443842,20.525397,-38.338699,55.192222
4,2017-04-02,425844,"Greinke, Zack",91,FF,7,90.942857,-1.285714,6.252857,6.058655,-131.799314,-7.466639,-7.565104,27.793235,-12.249997,54.464286

In [193]:
"""
grouped_2017_df['game_date'] = pd.to_datetime(grouped_2017_df['game_date'])
grouped_2017_df['season'] = grouped_2017_df['game_date'].dt.year

# Step 1: Season Total Pitches
season_total_pitches = grouped_2017_df.groupby(['pitcher', 'player_name', 'season'])['total_pitches'].sum().reset_index(name='season_total_pitches')

# Step 2: Season Total by Pitch Type
season_total_by_pitch_type = grouped_2017_df.groupby(['pitcher', 'player_name', 'season', 'pitch_type'])['count_by_pitch_type'].sum().reset_index(name='season_total_count_by_pitch_type')

# Weighted Averages Calculation Setup
weighted_avg_columns = ['release_speed', 'release_pos_x', 'release_pos_z', 'vx0', 'vy0', 'vz0', 'ax', 'ay', 'az', 'release_pos_y']
for col in weighted_avg_columns:
    grouped_2017_df[f'{col}_product'] = grouped_2017_df[col] * grouped_2017_df['count_by_pitch_type']

weighted_avg_aggregations = {f'{col}_product': 'sum' for col in weighted_avg_columns}
weighted_avg_aggregations['count_by_pitch_type'] = 'sum'

# Aggregate for weighted averages
weighted_avg_df = grouped_2017_df.groupby(['pitcher', 'player_name', 'season', 'pitch_type']).agg(weighted_avg_aggregations).reset_index()

# Calculate weighted averages
for col in weighted_avg_columns:
    weighted_avg_df[f'{col}_weighted_avg'] = weighted_avg_df[f'{col}_product'] / weighted_avg_df['count_by_pitch_type']

# Cleanup
weighted_avg_df.drop(columns=[f'{col}_product' for col in weighted_avg_columns], inplace=True)

# Merge season totals and weighted averages
final_2017_df = pd.merge(season_total_pitches, season_total_by_pitch_type, on=['pitcher', 'player_name', 'season'])
final_2017_df = pd.merge(final_2017_df, weighted_avg_df, on=['pitcher', 'player_name', 'season', 'pitch_type'])

final_2017_df.head()
"""

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,112526,"Colon, Bartolo",2017,9440,CH,222,222,81.251351,-1.536577,5.527883,4.725224,-117.850169,-3.227057,-11.585814,22.078801,-24.595902,55.158378
1,112526,"Colon, Bartolo",2017,9440,FC,7,7,86.614286,-1.597143,5.680000,4.901744,-125.504292,-4.632348,-1.278403,25.673230,-16.198153,55.227143
2,112526,"Colon, Bartolo",2017,9440,FF,450,450,90.281778,-1.186000,5.773956,4.087600,-130.885083,-4.594772,-8.723897,27.398956,-14.663100,55.261489
3,112526,"Colon, Bartolo",2017,9440,SI,1435,1435,87.062787,-1.526676,5.512509,6.434277,-126.194251,-2.747981,-15.602021,25.226547,-22.762351,55.232753
4,112526,"Colon, Bartolo",2017,9440,SL,166,166,81.513253,-1.619398,5.546807,5.398850,-118.244001,-2.236791,1.103959,20.815275,-27.593265,55.539880

In [194]:
"""final_2017_df['player_name'] = final_2017_df['player_name'].str.lower().str.strip().str.replace(r'\*$', '', regex=True)
final_2017_df.head()
"""

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,112526,"colon, bartolo",2017,9440,CH,222,222,81.251351,-1.536577,5.527883,4.725224,-117.850169,-3.227057,-11.585814,22.078801,-24.595902,55.158378
1,112526,"colon, bartolo",2017,9440,FC,7,7,86.614286,-1.597143,5.680000,4.901744,-125.504292,-4.632348,-1.278403,25.673230,-16.198153,55.227143
2,112526,"colon, bartolo",2017,9440,FF,450,450,90.281778,-1.186000,5.773956,4.087600,-130.885083,-4.594772,-8.723897,27.398956,-14.663100,55.261489
3,112526,"colon, bartolo",2017,9440,SI,1435,1435,87.062787,-1.526676,5.512509,6.434277,-126.194251,-2.747981,-15.602021,25.226547,-22.762351,55.232753
4,112526,"colon, bartolo",2017,9440,SL,166,166,81.513253,-1.619398,5.546807,5.398850,-118.244001,-2.236791,1.103959,20.815275,-27.593265,55.539880

In [195]:
#print(final_2017_df['player_name'].unique())

['colon, bartolo' 'arroyo, bronson' 'benoit, joaquÃ­n' 'belisle, matt'
 'sabathia, cc' 'dickey, r.a.' 'lackey, john' 'de la rosa, jorge'
 'pÃ©rez, oliver' 'guthrie, jeremy' 'wainwright, adam' 'greinke, zack'
 'jackson, edwin' 'santana, ervin' 'blanton, joe' 'mcgowan, dustin'
 'cain, matt' 'hamels, cole' 'young, chris' 'hernÃ¡ndez, fÃ©lix'
 'petit, yusmeiro' 'verlander, justin' 'liriano, francisco'
 'jimÃ©nez, ubaldo' 'hammel, jason' 'sÃ¡nchez, anÃ­bal' 'duke, zach'
 'mccarthy, brandon' 'feldman, scott' 'nolasco, ricky' 'chavez, jesse'
 'kluber, corey' 'cecil, brett' 'hill, rich' 'shields, james'
 'garcÃ­a, jaime' 'guerra, junior' 'harrell, lucas' 'volquez, edinson'
 'vargas, jason' 'weaver, jered' 'fister, doug' 'davis, wade'
 'gallardo, yovani' 'lester, jon' 'kendrick, kyle' 'kennedy, ian'
 'miller, andrew' 'wright, steven' 'leblanc, wade' 'scherzer, max'
 'buchholz, clay' 'morrow, brandon' 'richard, clayton' 'arrieta, jake'
 'price, david' 'griffin, a.j.' 'cueto, johnny' 'bailey, homer'
 'happ, j.a.' 'lynn, lance' 'volstad, chris' 'tomlin, josh'
 'pelfrey, mike' 'gonzÃ¡lez, gio' 'hughes, phil' 'swarzak, anthony'
 'estrada, marco' 'nova, ivÃ¡n' 'chacÃ­n, jhoulys' 'carrasco, carlos'
 'anderson, brett' 'worley, vance' 'ross, tyson' 'wood, travis'
 'phelps, david' 'hellickson, jeremy' 'kershaw, clayton' 'cashner, andrew'
 'duensing, brian' 'hunter, tommy' 'miley, wade' 'stammen, craig'
 'garza, matt' 'quintana, jose' 'pineda, michael' 'tillman, chris'
 'minor, mike' 'latos, mat' 'norris, bud' 'archer, chris' 'gibson, kyle'
 'locke, jeff' 'mcallister, zach' 'cobb, alex' 'samardzija, jeff'
 'leake, mike' 'cahill, trevor' 'santiago, hÃ©ctor' 'anderson, chase'
 'holland, derek' 'peacock, brad' 'peralta, wily' 'nicasio, juan'
 'darvish, yu' 'alvarez iii, henderson' 'delgado, randall'
 'salazar, danny' 'bettis, chad' 'bumgarner, madison' 'collmenter, josh'
 'duffy, danny' 'gee, dillon' 'harvey, matt' 'moore, matt' 'nelson, jimmy'
 'pomeranz, drew' 'porcello, rick' 'sale, chris' 'zimmermann, jordan'
 'de la rosa, rubby' 'pÃ©rez, martÃ­n' 'teheran, julio' 'shoemaker, matt'
 'anderson, tyler' 'andriese, matt' 'chatwood, tyler' 'cole, gerrit'
 'cosart, jarred' 'gray, sonny' 'hendricks, kyle' 'hudson, daniel'
 'koehler, tom' 'lyles, jordan' 'mchugh, collin' 'milone, tommy'
 'montgomery, mike' 'odorizzi, jake' 'roark, tanner' 'strasburg, stephen'
 'bauer, trevor' 'turner, jacob' 'lorenzen, michael' 'iwakuma, hisashi'
 'tanaka, masahiro' 'ryu, hyun jin' 'stripling, ross' 'wheeler, zack'
 'ureÃ±a, josÃ©' 'boyd, matthew' 'corbin, patrick' 'fiers, mike'
 'heaney, andrew' 'matz, steven' 'miller, shelby' 'paxton, james'
 'richards, garrett' 'skaggs, tyler' 'keuchel, dallas' 'nuÃ±o, vidal'
 'straily, dan' 'stroman, marcus' 'covey, dylan' 'foltynewicz, mike'
 'gausman, kevin' 'gray, jon' 'ray, robbie' 'sanchez, aaron'
 'smith, caleb' 'syndergaard, noah' 'taillon, jameson' 'velasquez, vince'
 'walker, taijuan' 'williams, trevor' 'germÃ¡n, domingo' 'montas, frankie'
 'rodriguez, eduardo' 'degrom, jacob' 'gonzales, marco' 'eickhoff, jerad'
 'junis, jakob' 'norris, daniel' 'weaver, luke' 'pivetta, nick'
 'bundy, dylan' 'clevinger, mike' 'davies, zach' 'fulmer, michael'
 'lÃ³pez, jorge' 'musgrove, joe' 'nola, aaron' 'ross, joe' 'snell, blake'
 'wisler, matt' 'woodruff, brandon' 'perdomo, luis' 'elÃ­as, roenis'
 'rodÃ³n, carlos' 'glasnow, tyler' 'fedde, erick' 'freeland, kyle'
 'lugo, seth' 'fried, max' 'giolito, lucas' 'wacha, michael'
 'mÃ¡rquez, germÃ¡n' 'graveman, kendall' 'stratton, chris' 'suter, brent'
 'chen, wei-yin' 'eflin, zach' 'buehler, walker' 'blackburn, paul'
 'mccullers jr., lance' 'berrÃ­os, josÃ©' 'blach, ty' 'wood, alex'
 'senzatela, antonio' 'severino, luis' 'flexen, chris' 'lÃ³pez, reynaldo'
 'maeda, kenta' 'despaigne, odrisamer' 'urÃ­as, julio' 'manaea, sean'
 'kuhl, chad' 'mahle, tyler' 'brault, steven' 'godley, zack'
 'alcantara, sandy' 'flaherty, jack' 'hoffman, jeff' 'montgomery, jordan'
 'newcomb, sean' 'lamet, dinelson']

In [196]:
"""
def remove_accents(input_str):
    nfkd_form = unicodedata.normalize('NFKD', input_str)
    return "".join([c for c in nfkd_form if not unicodedata.combining(c)])

def clean_name(name):
    name = name.lower()
    name = remove_accents(name)
    name = re.sub(r'[-.]', '', name)
    name = re.sub(r'\s+', ' ', name).strip()
    return name

final_2017_df['player_name'] = final_2017_df['player_name'].apply(clean_name)
"""

In [197]:
"""
# Convert 'player_name' from "last name, first name" to "first name last name"
final_2017_df['Name'] = final_2017_df['player_name'].apply(lambda x: ' '.join(x.split(', ')[::-1]))
"""

In [198]:
"""
# Now, you can perform the merge using 'Name' and 'season' as the keys for both DataFrames
better_2017_df = pd.merge(final_2017_df, 
                          cleaning_filtered_df[['Name', 'season', 'Age']],
                          on=['Name', 'season'],
                          how='left')
"""

In [199]:
#better_2017_df.head()

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg,Name,Age
0,112526,"colon, bartolo",2017,9440,CH,222,222,81.251351,-1.536577,5.527883,4.725224,-117.850169,-3.227057,-11.585814,22.078801,-24.595902,55.158378,bartolo colon,44.0
1,112526,"colon, bartolo",2017,9440,FC,7,7,86.614286,-1.597143,5.680000,4.901744,-125.504292,-4.632348,-1.278403,25.673230,-16.198153,55.227143,bartolo colon,44.0
2,112526,"colon, bartolo",2017,9440,FF,450,450,90.281778,-1.186000,5.773956,4.087600,-130.885083,-4.594772,-8.723897,27.398956,-14.663100,55.261489,bartolo colon,44.0
3,112526,"colon, bartolo",2017,9440,SI,1435,1435,87.062787,-1.526676,5.512509,6.434277,-126.194251,-2.747981,-15.602021,25.226547,-22.762351,55.232753,bartolo colon,44.0
4,112526,"colon, bartolo",2017,9440,SL,166,166,81.513253,-1.619398,5.546807,5.398850,-118.244001,-2.236791,1.103959,20.815275,-27.593265,55.539880,bartolo colon,44.0

In [200]:
#better_2017_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1204 entries, 0 to 1203
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   pitcher                           1204 non-null   int64
 1   player_name                       1204 non-null   object
 2   season                            1204 non-null   int32
 3   season_total_pitches              1204 non-null   int64
 4   pitch_type                        1204 non-null   object
 5   season_total_count_by_pitch_type  1204 non-null   int64
 6   count_by_pitch_type               1204 non-null   int64
 7   release_speed_weighted_avg        1204 non-null   float64
 8   release_pos_x_weighted_avg        1204 non-null   float64
 9   release_pos_z_weighted_avg        1204 non-null   float64
 10  vx0_weighted_avg                  1204 non-null   float64
 11  vy0_weighted_avg                  1204 non-null   float64
 12  vz0_weighted_avg                  1204 non-null   float64
 13  ax_weighted_avg                   1204 non-null   float64
 14  ay_weighted_avg                   1204 non-null   float64
 15  az_weighted_avg                   1204 non-null   float64
 16  release_pos_y_weighted_avg        1204 non-null   float64
 17  Name                              1204 non-null   object
 18  Age                               1061 non-null   float64
dtypes: float64(11), int32(1), int64(4), object(3)
memory usage: 174.1+ KB

In [201]:
#better_2017_df.to_csv('data/better_2017_df.csv')

2018

In [6]:
#all_2018_stats_df = pd.read_csv('~/Documents/Flatiron/Project_5_/data/all_2018_stats_df.csv', index_col=0)

In [8]:
#all_2018_stats_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 412232 entries, 0 to 412231
Data columns (total 92 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   pitch_type                       410541 non-null  object
 1   game_date                        412232 non-null  object
 2   release_speed                    410620 non-null  float64
 3   release_pos_x                    410601 non-null  float64
 4   release_pos_z                    410601 non-null  float64
 5   player_name                      412232 non-null  object
 6   batter                           412232 non-null  int64
 7   pitcher                          412232 non-null  int64
 8   events                           106008 non-null  object
 9   description                      412232 non-null  object
 10  spin_dir                         0 non-null       float64
 11  spin_rate_deprecated             0 non-null       float64
 12  break_angle_deprecated           0 non-null       float64
 13  break_length_deprecated          0 non-null       float64
 14  zone                             410601 non-null  float64
 15  des                              412232 non-null  object
 16  game_type                        412232 non-null  object
 17  stand                            412232 non-null  object
 18  p_throws                         412232 non-null  object
 19  home_team                        412232 non-null  object
 20  away_team                        412232 non-null  object
 21  type                             412232 non-null  object
 22  hit_location                     93420 non-null   float64
 23  bb_type                          73252 non-null   object
 24  balls                            412232 non-null  int64
 25  strikes                          412232 non-null  int64
 26  game_year                        412232 non-null  int64
 27  pfx_x                            410598 non-null  float64
 28  pfx_z                            410598 non-null  float64
 29  plate_x                          410601 non-null  float64
 30  plate_z                          410601 non-null  float64
 31  on_3b                            33416 non-null   float64
 32  on_2b                            68056 non-null   float64
 33  on_1b                            119247 non-null  float64
 34  outs_when_up                     412232 non-null  int64
 35  inning                           412232 non-null  int64
 36  inning_topbot                    412232 non-null  object
 37  hc_x                             70209 non-null   float64
 38  hc_y                             70209 non-null   float64
 39  tfs_deprecated                   0 non-null       float64
 40  tfs_zulu_deprecated              0 non-null       float64
 41  fielder_2                        412232 non-null  int64
 42  umpire                           0 non-null       float64
 43  sv_id                            0 non-null       float64
 44  vx0                              410601 non-null  float64
 45  vy0                              410601 non-null  float64
 46  vz0                              410601 non-null  float64
 47  ax                               410601 non-null  float64
 48  ay                               410601 non-null  float64
 49  az                               410601 non-null  float64
 50  sz_top                           410601 non-null  float64
 51  sz_bot                           410601 non-null  float64
 52  hit_distance_sc                  111198 non-null  float64
 53  launch_speed                     116059 non-null  float64
 54  launch_angle                     116021 non-null  float64
 55  effective_speed                  410827 non-null  float64
 56  release_spin_rate                405223 non-null  float64
 57  release_extension                410601 non-null  float64
 58  game_pk                          412232 non-null  int64
 59  pitcher.1                        412232 non-null  int64
 60  fielder_2.1                      412232 non-null  int64
 61  fielder_3                        412232 non-null  int64
 62  fielder_4                        412232 non-null  int64
 63  fielder_5                        412232 non-null  int64
 64  fielder_6                        412232 non-null  int64
 65  fielder_7                        412232 non-null  int64
 66  fielder_8                        412232 non-null  int64
 67  fielder_9                        412232 non-null  int64
 68  release_pos_y                    410601 non-null  float64
 69  estimated_ba_using_speedangle    72117 non-null   float64
 70  estimated_woba_using_speedangle  72117 non-null   float64
 71  woba_value                       106008 non-null  float64
 72  woba_denom                       104872 non-null  float64
 73  babip_value                      106008 non-null  float64
 74  iso_value                        106008 non-null  float64
 75  launch_speed_angle               72117 non-null   float64
 76  at_bat_number                    412232 non-null  int64
 77  pitch_number                     412232 non-null  int64
 78  pitch_name                       410541 non-null  object
 79  home_score                       412232 non-null  int64
 80  away_score                       412232 non-null  int64
 81  bat_score                        412232 non-null  int64
 82  fld_score                        412232 non-null  int64
 83  post_away_score                  412232 non-null  int64
 84  post_home_score                  412232 non-null  int64
 85  post_bat_score                   412232 non-null  int64
 86  post_fld_score                   412232 non-null  int64
 87  if_fielding_alignment            410569 non-null  object
 88  of_fielding_alignment            410569 non-null  object
 89  spin_axis                        410601 non-null  float64
 90  delta_home_win_exp               412232 non-null  float64
 91  delta_run_exp                    412180 non-null  float64
dtypes: float64(47), int64(28), object(17)
memory usage: 292.5+ MB

In [203]:
"""
all_2018_stats_df.drop(columns=['batter', 'events', 'description', 'zone',
                                'des', 'game_type', 'stand', 'home_team',
                                'away_team', 'type', 'hit_location', 'bb_type',
                                'balls', 'strikes', 'pfx_x', 'spin_dir', 
                                'pfx_z', 'plate_x', 'plate_z', 'on_3b',
                                'on_2b', 'on_1b', 'outs_when_up', 'inning',
                                'inning_topbot', 'hc_x', 'hc_y', 'fielder_2',
                                'umpire', 'sv_id', 'hit_distance_sc', 'sz_top',
                                 'sz_bot', 'launch_speed', 'launch_angle', 'game_pk',
                                'pitcher.1', 'fielder_2.1', 'fielder_3', 'fielder_4',
                                'fielder_5', 'fielder_6', 'fielder_7', 'fielder_8',
                                'fielder_9', 'estimated_ba_using_speedangle',
                                'estimated_woba_using_speedangle', 'babip_value',
                                'launch_speed_angle', 'woba_value', 'woba_denom', 'iso_value', 
                                'at_bat_number', 'pitch_number', 'home_score', 'away_score',
                                'bat_score', 'fld_score', 'post_home_score', 'post_bat_score',
                                'post_fld_score', 'post_away_score', 'if_fielding_alignment',
                                'of_fielding_alignment', 'delta_home_win_exp',
                                'delta_run_exp', 'spin_rate_deprecated', 'break_angle_deprecated',
                               'break_length_deprecated', 'tfs_deprecated', 'tfs_zulu_deprecated'], inplace=True)
all_2018_stats_df.head()
"""

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,...,vz0,ax,ay,az,effective_speed,release_spin_rate,release_extension,release_pos_y,pitch_name,spin_axis
0,FF,2018-09-29,93.3,2.20,5.41,"PÃ©rez, Oliver",424144,L,2018,-8.330570,...,-3.537231,12.754514,28.834540,-16.456552,92.4,2177.0,5.8,54.68,4-Seam Fastball,144.0
1,SI,2018-09-29,92.6,2.50,5.22,"PÃ©rez, Oliver",424144,L,2018,-10.494050,...,-0.530389,20.104869,28.268887,-28.840385,92.3,1941.0,6.2,54.34,Sinker,101.0
2,SL,2018-09-29,79.2,2.72,4.81,"PÃ©rez, Oliver",424144,L,2018,-5.409580,...,1.272910,-5.716481,20.118242,-34.375437,77.8,2197.0,5.3,55.22,Slider,284.0
3,SI,2018-09-29,93.0,2.53,5.22,"PÃ©rez, Oliver",424144,L,2018,-8.334664,...,-1.445371,18.395080,28.551413,-26.370682,92.7,2095.0,6.1,54.38,Sinker,109.0
4,SL,2018-09-29,77.9,2.55,5.01,"PÃ©rez, Oliver",424144,L,2018,-5.795064,...,2.538368,-5.319335,19.644658,-34.813534,76.3,2186.0,5.2,55.32,Slider,287.0

In [204]:
"""
all_2018_stats_df.drop(columns=['spin_axis', 'effective_speed',
                               'release_spin_rate', 'release_extension'], inplace=True)
"""

In [205]:
#all_2018_stats_df = all_2018_stats_df.dropna(axis=0)

In [206]:
#all_2018_stats_df.reset_index(inplace=True)

In [207]:
#all_2018_stats_df.drop('index', axis=1)

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,vy0,vz0,ax,ay,az,release_pos_y,pitch_name
0,FF,2018-09-29,93.3,2.20,5.41,"PÃ©rez, Oliver",424144,L,2018,-8.330570,-135.489359,-3.537231,12.754514,28.834540,-16.456552,54.68,4-Seam Fastball
1,SI,2018-09-29,92.6,2.50,5.22,"PÃ©rez, Oliver",424144,L,2018,-10.494050,-134.458927,-0.530389,20.104869,28.268887,-28.840385,54.34,Sinker
2,SL,2018-09-29,79.2,2.72,4.81,"PÃ©rez, Oliver",424144,L,2018,-5.409580,-115.029257,1.272910,-5.716481,20.118242,-34.375437,55.22,Slider
3,SI,2018-09-29,93.0,2.53,5.22,"PÃ©rez, Oliver",424144,L,2018,-8.334664,-135.149771,-1.445371,18.395080,28.551413,-26.370682,54.38,Sinker
4,SL,2018-09-29,77.9,2.55,5.01,"PÃ©rez, Oliver",424144,L,2018,-5.795064,-113.095659,2.538368,-5.319335,19.644658,-34.813534,55.32,Slider
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
410536,CH,2018-03-31,81.4,2.79,5.52,"Yarbrough, Ryan",642232,L,2018,-10.837141,-117.922016,-2.950963,16.324749,24.142674,-25.860317,54.47,Changeup
410537,CH,2018-03-31,80.9,2.80,5.51,"Yarbrough, Ryan",642232,L,2018,-7.979526,-117.386848,-3.728000,16.341647,24.487218,-27.021521,54.53,Changeup
410538,FC,2018-03-31,86.4,2.97,5.41,"Yarbrough, Ryan",642232,L,2018,-10.306372,-125.226645,-4.913631,1.708010,26.151788,-22.852170,54.76,Cutter
410539,CH,2018-03-31,82.0,2.77,5.51,"Yarbrough, Ryan",642232,L,2018,-8.287884,-119.005354,-0.893259,15.547702,24.170189,-26.184568,54.58,Changeup
410540,SI,2018-03-31,88.5,2.70,5.76,"Yarbrough, Ryan",642232,L,2018,-8.404200,-128.534486,-4.793352,19.636916,27.939173,-24.751264,54.36,Sinker

In [208]:
"""
# Group by 'game_date' and 'pitcher' to calculate the total pitches
total_pitches = all_2018_stats_df.groupby(['game_date', 'pitcher', 'player_name']).size().reset_index(name='total_pitches')

# Group by 'game_date', 'pitcher', and 'pitch_type' to calculate the sum total of each pitch_type
total_pitches_by_type = all_2018_stats_df.groupby(['game_date', 'pitcher', 'player_name', 'pitch_type']).size().reset_index(name='count_by_pitch_type')

# Calculate averages of the specified metrics for each pitch type, grouped by game_date and pitcher
avg_metrics = all_2018_stats_df.groupby(['game_date', 'pitcher', 'player_name', 'pitch_type']).agg({
    'release_speed': 'mean',
    'release_pos_x': 'mean',
    'release_pos_z': 'mean',
    'vx0': 'mean',
    'vy0': 'mean',
    'vz0': 'mean',
    'ax': 'mean',
    'ay': 'mean',
    'az': 'mean',
    'release_pos_y': 'mean',
}).reset_index()

grouped_2018_df = total_pitches.merge(total_pitches_by_type, on=['game_date', 'pitcher', 'player_name'], how='left')
grouped_2018_df = grouped_2018_df.merge(avg_metrics, on=['game_date', 'pitcher', 'player_name', 'pitch_type'], how='left')

grouped_2018_df.head()
"""

,game_date,pitcher,player_name,total_pitches,pitch_type,count_by_pitch_type,release_speed,release_pos_x,release_pos_z,vx0,vy0,vz0,ax,ay,az,release_pos_y
0,2018-03-29,407822,"De La Rosa, Jorge",4,FC,2,84.350000,2.750000,5.830000,-8.086980,-122.356397,-3.333402,-2.799635,24.618739,-28.167485,55.245000
1,2018-03-29,407822,"De La Rosa, Jorge",4,FF,2,92.150000,3.095000,5.575000,-8.970112,-133.723969,-4.006840,14.595338,29.262826,-17.170422,55.115000
2,2018-03-29,430935,"Hamels, Cole",93,CH,14,81.814286,2.497857,6.220714,-7.437962,-118.814369,-5.946986,11.560955,22.878002,-25.216116,54.158571
3,2018-03-29,430935,"Hamels, Cole",93,CU,22,77.872727,2.865455,5.988636,-5.920584,-113.152613,-0.650188,-3.149052,20.597412,-38.032918,54.815000
4,2018-03-29,430935,"Hamels, Cole",93,FC,22,86.518182,2.756364,6.102727,-6.427376,-125.845940,-4.856190,-0.884203,23.576812,-24.288409,54.281818

In [209]:
"""grouped_2018_df['game_date'] = pd.to_datetime(grouped_2018_df['game_date'])
grouped_2018_df['season'] = grouped_2018_df['game_date'].dt.year

# Step 1: Season Total Pitches
season_total_pitches = grouped_2018_df.groupby(['pitcher', 'player_name', 'season'])['total_pitches'].sum().reset_index(name='season_total_pitches')

# Step 2: Season Total by Pitch Type
season_total_by_pitch_type = grouped_2018_df.groupby(['pitcher', 'player_name', 'season', 'pitch_type'])['count_by_pitch_type'].sum().reset_index(name='season_total_count_by_pitch_type')

# Weighted Averages Calculation Setup
weighted_avg_columns = ['release_speed', 'release_pos_x', 'release_pos_z', 'vx0', 'vy0', 'vz0', 'ax', 'ay', 'az', 'release_pos_y']
for col in weighted_avg_columns:
    grouped_2018_df[f'{col}_product'] = grouped_2018_df[col] * grouped_2018_df['count_by_pitch_type']

weighted_avg_aggregations = {f'{col}_product': 'sum' for col in weighted_avg_columns}
weighted_avg_aggregations['count_by_pitch_type'] = 'sum'

# Aggregate for weighted averages
weighted_avg_df = grouped_2018_df.groupby(['pitcher', 'player_name', 'season', 'pitch_type']).agg(weighted_avg_aggregations).reset_index()

# Calculate weighted averages
for col in weighted_avg_columns:
    weighted_avg_df[f'{col}_weighted_avg'] = weighted_avg_df[f'{col}_product'] / weighted_avg_df['count_by_pitch_type']

# Cleanup
weighted_avg_df.drop(columns=[f'{col}_product' for col in weighted_avg_columns], inplace=True)

# Merge season totals and weighted averages
final_2018_df = pd.merge(season_total_pitches, season_total_by_pitch_type, on=['pitcher', 'player_name', 'season'])
final_2018_df = pd.merge(final_2018_df, weighted_avg_df, on=['pitcher', 'player_name', 'season', 'pitch_type'])

final_2018_df.head()
"""

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,112526,"Colon, Bartolo",2018,10240,CH,248,248,80.779839,-1.500121,5.468347,4.205638,-117.358256,-2.966555,-11.008411,22.165748,-26.196100,55.261169
1,112526,"Colon, Bartolo",2018,10240,FC,62,62,85.533871,-1.556774,5.545000,2.670307,-124.394402,-3.081874,-0.999626,22.837186,-20.765071,55.386935
2,112526,"Colon, Bartolo",2018,10240,FF,365,365,89.320000,-1.232055,5.651151,3.858417,-129.755732,-4.303520,-8.182075,26.732912,-16.754152,55.367370
3,112526,"Colon, Bartolo",2018,10240,SI,1389,1389,86.858243,-1.491706,5.441663,6.244949,-126.074042,-2.451521,-15.729593,25.945832,-25.102962,55.342261
4,112526,"Colon, Bartolo",2018,10240,SL,164,164,80.471341,-1.567012,5.533415,4.223423,-116.920238,-2.083380,2.369800,20.415959,-30.702080,55.724512

In [210]:
"""
final_2018_df['player_name'] = final_2018_df['player_name'].str.lower().str.strip().str.replace(r'\*$', '', regex=True)
final_2018_df.head()
"""

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,112526,"colon, bartolo",2018,10240,CH,248,248,80.779839,-1.500121,5.468347,4.205638,-117.358256,-2.966555,-11.008411,22.165748,-26.196100,55.261169
1,112526,"colon, bartolo",2018,10240,FC,62,62,85.533871,-1.556774,5.545000,2.670307,-124.394402,-3.081874,-0.999626,22.837186,-20.765071,55.386935
2,112526,"colon, bartolo",2018,10240,FF,365,365,89.320000,-1.232055,5.651151,3.858417,-129.755732,-4.303520,-8.182075,26.732912,-16.754152,55.367370
3,112526,"colon, bartolo",2018,10240,SI,1389,1389,86.858243,-1.491706,5.441663,6.244949,-126.074042,-2.451521,-15.729593,25.945832,-25.102962,55.342261
4,112526,"colon, bartolo",2018,10240,SL,164,164,80.471341,-1.567012,5.533415,4.223423,-116.920238,-2.083380,2.369800,20.415959,-30.702080,55.724512

In [211]:
"""
def remove_accents(input_str):
    nfkd_form = unicodedata.normalize('NFKD', input_str)
    return "".join([c for c in nfkd_form if not unicodedata.combining(c)])

def clean_name(name):
    name = name.lower()
    name = remove_accents(name)
    name = re.sub(r'[-.]', '', name)
    name = re.sub(r'\s+', ' ', name).strip()
    return name

final_2018_df['player_name'] = final_2018_df['player_name'].apply(clean_name)
"""

In [212]:
"""
# Convert 'player_name' from "last name, first name" to "first name last name"
final_2018_df['Name'] = final_2018_df['player_name'].apply(lambda x: ' '.join(x.split(', ')[::-1]))
"""

In [213]:
"""
# Now, you can perform the merge using 'Name' and 'season' as the keys for both DataFrames
better_2018_df = pd.merge(final_2018_df, 
                          cleaning_filtered_df[['Name', 'season', 'Age']],
                          on=['Name', 'season'],
                          how='left')
"""

In [214]:
#better_2018_df.head()

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg,Name,Age
0,112526,"colon, bartolo",2018,10240,CH,248,248,80.779839,-1.500121,5.468347,4.205638,-117.358256,-2.966555,-11.008411,22.165748,-26.196100,55.261169,bartolo colon,45.0
1,112526,"colon, bartolo",2018,10240,FC,62,62,85.533871,-1.556774,5.545000,2.670307,-124.394402,-3.081874,-0.999626,22.837186,-20.765071,55.386935,bartolo colon,45.0
2,112526,"colon, bartolo",2018,10240,FF,365,365,89.320000,-1.232055,5.651151,3.858417,-129.755732,-4.303520,-8.182075,26.732912,-16.754152,55.367370,bartolo colon,45.0
3,112526,"colon, bartolo",2018,10240,SI,1389,1389,86.858243,-1.491706,5.441663,6.244949,-126.074042,-2.451521,-15.729593,25.945832,-25.102962,55.342261,bartolo colon,45.0
4,112526,"colon, bartolo",2018,10240,SL,164,164,80.471341,-1.567012,5.533415,4.223423,-116.920238,-2.083380,2.369800,20.415959,-30.702080,55.724512,bartolo colon,45.0

In [215]:
#better_2018_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1192 entries, 0 to 1191
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   pitcher                           1192 non-null   int64
 1   player_name                       1192 non-null   object
 2   season                            1192 non-null   int32
 3   season_total_pitches              1192 non-null   int64
 4   pitch_type                        1192 non-null   object
 5   season_total_count_by_pitch_type  1192 non-null   int64
 6   count_by_pitch_type               1192 non-null   int64
 7   release_speed_weighted_avg        1192 non-null   float64
 8   release_pos_x_weighted_avg        1192 non-null   float64
 9   release_pos_z_weighted_avg        1192 non-null   float64
 10  vx0_weighted_avg                  1192 non-null   float64
 11  vy0_weighted_avg                  1192 non-null   float64
 12  vz0_weighted_avg                  1192 non-null   float64
 13  ax_weighted_avg                   1192 non-null   float64
 14  ay_weighted_avg                   1192 non-null   float64
 15  az_weighted_avg                   1192 non-null   float64
 16  release_pos_y_weighted_avg        1192 non-null   float64
 17  Name                              1192 non-null   object
 18  Age                               1068 non-null   float64
dtypes: float64(11), int32(1), int64(4), object(3)
memory usage: 172.4+ KB

In [216]:
#better_2018_df.to_csv('data/better_2018_df.csv')

2019

In [217]:
#all_2019_stats_df = pd.read_csv('~/Documents/Flatiron/Project_5_/data/all_2019_stats_df.csv', index_col=0)

In [218]:
"""
all_2019_stats_df.drop(columns=['batter', 'events', 'description', 'zone',
                                'des', 'game_type', 'stand', 'home_team',
                                'away_team', 'type', 'hit_location', 'bb_type',
                                'balls', 'strikes', 'pfx_x', 'spin_dir', 
                                'pfx_z', 'plate_x', 'plate_z', 'on_3b',
                                'on_2b', 'on_1b', 'outs_when_up', 'inning',
                                'inning_topbot', 'hc_x', 'hc_y', 'fielder_2',
                                'umpire', 'sv_id', 'hit_distance_sc', 'sz_top',
                                 'sz_bot', 'launch_speed', 'launch_angle', 'game_pk',
                                'pitcher.1', 'fielder_2.1', 'fielder_3', 'fielder_4',
                                'fielder_5', 'fielder_6', 'fielder_7', 'fielder_8',
                                'fielder_9', 'estimated_ba_using_speedangle',
                                'estimated_woba_using_speedangle', 'babip_value',
                                'launch_speed_angle', 'woba_value', 'woba_denom', 'iso_value', 
                                'at_bat_number', 'pitch_number', 'home_score', 'away_score',
                                'bat_score', 'fld_score', 'post_home_score', 'post_bat_score',
                                'post_fld_score', 'post_away_score', 'if_fielding_alignment',
                                'of_fielding_alignment', 'delta_home_win_exp',
                                'delta_run_exp', 'spin_rate_deprecated', 'break_angle_deprecated',
                               'break_length_deprecated', 'tfs_deprecated', 'tfs_zulu_deprecated'], inplace=True)
all_2019_stats_df.head()
"""

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,...,vz0,ax,ay,az,effective_speed,release_spin_rate,release_extension,release_pos_y,pitch_name,spin_axis
0,SI,2019-09-25,92.8,2.67,5.27,"PÃ©rez, Oliver",424144,L,2019,-10.325351,...,-2.706251,20.815682,26.534344,-26.052975,92.9,2386.0,6.2,54.28,Sinker,107.0
1,SL,2019-09-25,79.0,2.76,5.05,"PÃ©rez, Oliver",424144,L,2019,-5.511426,...,-0.179789,-5.467883,18.886644,-33.229707,78.2,2382.0,5.5,55.00,Slider,277.0
2,SI,2019-09-25,92.3,2.69,5.23,"PÃ©rez, Oliver",424144,L,2019,-7.420359,...,-2.749173,20.450020,26.399585,-26.726142,91.9,2284.0,5.9,54.63,Sinker,105.0
3,SI,2019-09-25,93.4,2.50,5.46,"PÃ©rez, Oliver",424144,L,2019,-11.566874,...,-4.025866,19.220514,27.441481,-21.331724,93.7,2269.0,6.5,54.03,Sinker,121.0
4,SI,2019-09-25,92.0,2.68,5.32,"PÃ©rez, Oliver",424144,L,2019,-10.802773,...,-4.099021,18.767819,26.641947,-21.251070,92.3,2243.0,6.4,54.08,Sinker,122.0

In [219]:
"""
all_2019_stats_df.drop(columns=['spin_axis', 'effective_speed',
                               'release_spin_rate', 'release_extension'], inplace=True)
"""

In [220]:
#all_2019_stats_df = all_2019_stats_df.dropna(axis=0)

In [221]:
#all_2019_stats_df.reset_index(inplace=True)

In [222]:
#all_2019_stats_df.drop('index', axis=1)

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,vy0,vz0,ax,ay,az,release_pos_y,pitch_name
0,SI,2019-09-25,92.8,2.67,5.27,"PÃ©rez, Oliver",424144,L,2019,-10.325351,-134.826666,-2.706251,20.815682,26.534344,-26.052975,54.28,Sinker
1,SL,2019-09-25,79.0,2.76,5.05,"PÃ©rez, Oliver",424144,L,2019,-5.511426,-114.945924,-0.179789,-5.467883,18.886644,-33.229707,55.00,Slider
2,SI,2019-09-25,92.3,2.69,5.23,"PÃ©rez, Oliver",424144,L,2019,-7.420359,-134.215800,-2.749173,20.450020,26.399585,-26.726142,54.63,Sinker
3,SI,2019-09-25,93.4,2.50,5.46,"PÃ©rez, Oliver",424144,L,2019,-11.566874,-135.556339,-4.025866,19.220514,27.441481,-21.331724,54.03,Sinker
4,SI,2019-09-25,92.0,2.68,5.32,"PÃ©rez, Oliver",424144,L,2019,-10.802773,-133.636675,-4.099021,18.767819,26.641947,-21.251070,54.08,Sinker
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401447,SI,2019-03-26,88.3,2.79,5.64,"Yarbrough, Ryan",642232,L,2019,-7.996148,-128.255383,-2.633611,16.906768,28.249247,-21.586628,54.44,Sinker
401448,FC,2019-03-26,84.3,3.08,5.19,"Yarbrough, Ryan",642232,L,2019,-7.170905,-122.403881,2.954996,-1.771360,23.484370,-28.422812,54.73,Cutter
401449,FC,2019-03-26,83.3,3.07,5.21,"Yarbrough, Ryan",642232,L,2019,-6.172516,-121.149242,0.678418,-2.298028,22.493648,-28.647200,54.70,Cutter
401450,SI,2019-03-26,86.9,2.84,5.74,"Yarbrough, Ryan",642232,L,2019,-7.509314,-126.176510,-4.739281,13.766272,27.127831,-19.357119,54.64,Sinker
401451,SI,2019-03-26,86.5,2.74,5.70,"Yarbrough, Ryan",642232,L,2019,-4.331087,-125.750076,-3.128347,14.299762,27.619882,-24.031311,54.69,Sinker

In [223]:
"""
# Group by 'game_date' and 'pitcher' to calculate the total pitches
total_pitches = all_2019_stats_df.groupby(['game_date', 'pitcher', 'player_name']).size().reset_index(name='total_pitches')

# Group by 'game_date', 'pitcher', and 'pitch_type' to calculate the sum total of each pitch_type
total_pitches_by_type = all_2019_stats_df.groupby(['game_date', 'pitcher', 'player_name', 'pitch_type']).size().reset_index(name='count_by_pitch_type')

# Calculate averages of the specified metrics for each pitch type, grouped by game_date and pitcher
avg_metrics = all_2019_stats_df.groupby(['game_date', 'pitcher', 'player_name', 'pitch_type']).agg({
    'release_speed': 'mean',
    'release_pos_x': 'mean',
    'release_pos_z': 'mean',
    'vx0': 'mean',
    'vy0': 'mean',
    'vz0': 'mean',
    'ax': 'mean',
    'ay': 'mean',
    'az': 'mean',
    'release_pos_y': 'mean',
}).reset_index()

grouped_2019_df = total_pitches.merge(total_pitches_by_type, on=['game_date', 'pitcher', 'player_name'], how='left')
grouped_2019_df = grouped_2019_df.merge(avg_metrics, on=['game_date', 'pitcher', 'player_name', 'pitch_type'], how='left')

grouped_2019_df.head()
"""

,game_date,pitcher,player_name,total_pitches,pitch_type,count_by_pitch_type,release_speed,release_pos_x,release_pos_z,vx0,vy0,vz0,ax,ay,az,release_pos_y
0,2019-03-20,453178,"Kennedy, Ian",19,CH,1,87.400000,-2.770000,5.560000,6.301667,-127.036288,-3.434120,-14.165200,24.736687,-19.456550,54.930000
1,2019-03-20,453178,"Kennedy, Ian",19,FF,13,93.061538,-2.714615,5.355385,7.593764,-135.293943,-4.818766,-10.943347,27.017142,-13.161089,54.312308
2,2019-03-20,453178,"Kennedy, Ian",19,KC,4,79.200000,-2.655000,5.487500,5.685894,-115.126837,-0.767239,6.646469,21.869629,-42.475745,54.612500
3,2019-03-20,453178,"Kennedy, Ian",19,SL,1,90.200000,-2.930000,5.340000,4.683909,-131.308115,-2.696309,-0.977545,26.005499,-21.983700,54.520000
4,2019-03-20,542881,"Anderson, Tyler",84,CH,24,79.837500,1.571667,6.183750,-4.721592,-116.063364,-4.240269,9.170048,21.139655,-20.315252,54.670417

In [224]:
"""
grouped_2019_df['game_date'] = pd.to_datetime(grouped_2019_df['game_date'])
grouped_2019_df['season'] = grouped_2019_df['game_date'].dt.year

# Step 1: Season Total Pitches
season_total_pitches = grouped_2019_df.groupby(['pitcher', 'player_name', 'season'])['total_pitches'].sum().reset_index(name='season_total_pitches')

# Step 2: Season Total by Pitch Type
season_total_by_pitch_type = grouped_2019_df.groupby(['pitcher', 'player_name', 'season', 'pitch_type'])['count_by_pitch_type'].sum().reset_index(name='season_total_count_by_pitch_type')

# Weighted Averages Calculation Setup
weighted_avg_columns = ['release_speed', 'release_pos_x', 'release_pos_z', 'vx0', 'vy0', 'vz0', 'ax', 'ay', 'az', 'release_pos_y']
for col in weighted_avg_columns:
    grouped_2019_df[f'{col}_product'] = grouped_2019_df[col] * grouped_2019_df['count_by_pitch_type']

weighted_avg_aggregations = {f'{col}_product': 'sum' for col in weighted_avg_columns}
weighted_avg_aggregations['count_by_pitch_type'] = 'sum'

# Aggregate for weighted averages
weighted_avg_df = grouped_2019_df.groupby(['pitcher', 'player_name', 'season', 'pitch_type']).agg(weighted_avg_aggregations).reset_index()

# Calculate weighted averages
for col in weighted_avg_columns:
    weighted_avg_df[f'{col}_weighted_avg'] = weighted_avg_df[f'{col}_product'] / weighted_avg_df['count_by_pitch_type']

# Cleanup
weighted_avg_df.drop(columns=[f'{col}_product' for col in weighted_avg_columns], inplace=True)

# Merge season totals and weighted averages
final_2019_df = pd.merge(season_total_pitches, season_total_by_pitch_type, on=['pitcher', 'player_name', 'season'])
final_2019_df = pd.merge(final_2019_df, weighted_avg_df, on=['pitcher', 'player_name', 'season', 'pitch_type'])

final_2019_df.head()
"""

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,282332,"Sabathia, CC",2019,7786,CH,211,211,82.674408,2.393412,5.752796,-5.653338,-120.457872,-3.604889,8.409502,21.193982,-25.188489,53.380284
1,282332,"Sabathia, CC",2019,7786,FC,726,726,88.335537,2.273540,5.963884,-6.564797,-128.643475,-3.041200,1.314224,23.548896,-21.897561,53.815702
2,282332,"Sabathia, CC",2019,7786,FF,22,22,88.763636,2.331364,5.940909,-7.039296,-129.273508,-3.184720,7.442200,24.019079,-21.347738,53.662273
3,282332,"Sabathia, CC",2019,7786,SI,248,248,89.148790,2.275000,5.922339,-6.771127,-129.767979,-4.523327,14.151617,25.587384,-23.327270,53.587621
4,282332,"Sabathia, CC",2019,7786,SL,522,522,79.241954,2.375134,5.856552,-3.205584,-115.398091,-2.137905,-7.340410,21.275583,-30.861662,54.096513

In [225]:
"""
final_2019_df['player_name'] = final_2019_df['player_name'].str.lower().str.strip().str.replace(r'\*$', '', regex=True)
final_2019_df.head()
"""

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,282332,"sabathia, cc",2019,7786,CH,211,211,82.674408,2.393412,5.752796,-5.653338,-120.457872,-3.604889,8.409502,21.193982,-25.188489,53.380284
1,282332,"sabathia, cc",2019,7786,FC,726,726,88.335537,2.273540,5.963884,-6.564797,-128.643475,-3.041200,1.314224,23.548896,-21.897561,53.815702
2,282332,"sabathia, cc",2019,7786,FF,22,22,88.763636,2.331364,5.940909,-7.039296,-129.273508,-3.184720,7.442200,24.019079,-21.347738,53.662273
3,282332,"sabathia, cc",2019,7786,SI,248,248,89.148790,2.275000,5.922339,-6.771127,-129.767979,-4.523327,14.151617,25.587384,-23.327270,53.587621
4,282332,"sabathia, cc",2019,7786,SL,522,522,79.241954,2.375134,5.856552,-3.205584,-115.398091,-2.137905,-7.340410,21.275583,-30.861662,54.096513

In [226]:
"""
def remove_accents(input_str):
    nfkd_form = unicodedata.normalize('NFKD', input_str)
    return "".join([c for c in nfkd_form if not unicodedata.combining(c)])

def clean_name(name):
    name = name.lower()
    name = remove_accents(name)
    name = re.sub(r'[-.]', '', name)
    name = re.sub(r'\s+', ' ', name).strip()
    return name

final_2019_df['player_name'] = final_2019_df['player_name'].apply(clean_name)
"""

In [227]:
"""
# Convert 'player_name' from "last name, first name" to "first name last name"
final_2019_df['Name'] = final_2019_df['player_name'].apply(lambda x: ' '.join(x.split(', ')[::-1]))
"""

In [228]:
"""
# Now, you can perform the merge using 'Name' and 'season' as the keys for both DataFrames
better_2019_df = pd.merge(final_2019_df, 
                          cleaning_filtered_df[['Name', 'season', 'Age']],
                          on=['Name', 'season'],
                          how='left')
"""

In [229]:
#better_2019_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1154 entries, 0 to 1153
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   pitcher                           1154 non-null   int64
 1   player_name                       1154 non-null   object
 2   season                            1154 non-null   int32
 3   season_total_pitches              1154 non-null   int64
 4   pitch_type                        1154 non-null   object
 5   season_total_count_by_pitch_type  1154 non-null   int64
 6   count_by_pitch_type               1154 non-null   int64
 7   release_speed_weighted_avg        1154 non-null   float64
 8   release_pos_x_weighted_avg        1154 non-null   float64
 9   release_pos_z_weighted_avg        1154 non-null   float64
 10  vx0_weighted_avg                  1154 non-null   float64
 11  vy0_weighted_avg                  1154 non-null   float64
 12  vz0_weighted_avg                  1154 non-null   float64
 13  ax_weighted_avg                   1154 non-null   float64
 14  ay_weighted_avg                   1154 non-null   float64
 15  az_weighted_avg                   1154 non-null   float64
 16  release_pos_y_weighted_avg        1154 non-null   float64
 17  Name                              1154 non-null   object
 18  Age                               1057 non-null   float64
dtypes: float64(11), int32(1), int64(4), object(3)
memory usage: 166.9+ KB

In [230]:
#better_2019_df.head()

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg,Name,Age
0,282332,"sabathia, cc",2019,7786,CH,211,211,82.674408,2.393412,5.752796,-5.653338,-120.457872,-3.604889,8.409502,21.193982,-25.188489,53.380284,cc sabathia,38.0
1,282332,"sabathia, cc",2019,7786,FC,726,726,88.335537,2.273540,5.963884,-6.564797,-128.643475,-3.041200,1.314224,23.548896,-21.897561,53.815702,cc sabathia,38.0
2,282332,"sabathia, cc",2019,7786,FF,22,22,88.763636,2.331364,5.940909,-7.039296,-129.273508,-3.184720,7.442200,24.019079,-21.347738,53.662273,cc sabathia,38.0
3,282332,"sabathia, cc",2019,7786,SI,248,248,89.148790,2.275000,5.922339,-6.771127,-129.767979,-4.523327,14.151617,25.587384,-23.327270,53.587621,cc sabathia,38.0
4,282332,"sabathia, cc",2019,7786,SL,522,522,79.241954,2.375134,5.856552,-3.205584,-115.398091,-2.137905,-7.340410,21.275583,-30.861662,54.096513,cc sabathia,38.0

In [231]:
#better_2019_df.to_csv('data/better_2019_df.csv')

2020

In [232]:
#all_2020_stats_df = pd.read_csv('~/Documents/Flatiron/Project_5_/data/all_2020_stats_df.csv', index_col=0)

In [233]:
"""all_2020_stats_df.drop(columns=['batter', 'events', 'description', 'zone',
                                'des', 'game_type', 'stand', 'home_team',
                                'away_team', 'type', 'hit_location', 'bb_type',
                                'balls', 'strikes', 'pfx_x', 'spin_dir', 
                                'pfx_z', 'plate_x', 'plate_z', 'on_3b',
                                'on_2b', 'on_1b', 'outs_when_up', 'inning',
                                'inning_topbot', 'hc_x', 'hc_y', 'fielder_2',
                                'umpire', 'sv_id', 'hit_distance_sc', 'sz_top',
                                 'sz_bot', 'launch_speed', 'launch_angle', 'game_pk',
                                'pitcher.1', 'fielder_2.1', 'fielder_3', 'fielder_4',
                                'fielder_5', 'fielder_6', 'fielder_7', 'fielder_8',
                                'fielder_9', 'estimated_ba_using_speedangle',
                                'estimated_woba_using_speedangle', 'babip_value',
                                'launch_speed_angle', 'woba_value', 'woba_denom', 'iso_value', 
                                'at_bat_number', 'pitch_number', 'home_score', 'away_score',
                                'bat_score', 'fld_score', 'post_home_score', 'post_bat_score',
                                'post_fld_score', 'post_away_score', 'if_fielding_alignment',
                                'of_fielding_alignment', 'delta_home_win_exp',
                                'delta_run_exp', 'spin_rate_deprecated', 'break_angle_deprecated',
                               'break_length_deprecated', 'tfs_deprecated', 'tfs_zulu_deprecated'], inplace=True)
all_2020_stats_df.head()
"""

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,...,vz0,ax,ay,az,effective_speed,release_spin_rate,release_extension,release_pos_y,pitch_name,spin_axis
0,SI,2020-09-27,88.9,2.98,5.29,"PÃ©rez, Oliver",424144,L,2020,-12.281452,...,-0.989660,20.383213,23.814852,-26.805910,88.9,2130.0,6.2,54.34,Sinker,125.0
1,SL,2020-09-27,74.8,2.10,5.73,"PÃ©rez, Oliver",424144,L,2020,-2.377321,...,0.610107,-4.717873,18.807153,-34.566989,74.8,2069.0,6.2,54.28,Slider,309.0
2,SL,2020-09-27,75.3,2.01,5.74,"PÃ©rez, Oliver",424144,L,2020,-4.185552,...,-2.514557,-6.942147,18.406492,-34.069642,75.4,2244.0,6.2,54.35,Slider,312.0
3,SL,2020-09-27,75.8,2.38,5.20,"PÃ©rez, Oliver",424144,L,2020,-6.816068,...,0.343225,-3.627673,18.464630,-32.767026,75.7,2252.0,6.1,54.38,Slider,299.0
4,SL,2020-09-27,75.0,2.70,5.15,"PÃ©rez, Oliver",424144,L,2020,-6.094674,...,0.249817,-2.756490,18.526994,-33.136746,75.2,2113.0,6.3,54.16,Slider,293.0

In [234]:
"""
all_2020_stats_df.drop(columns=['spin_axis', 'effective_speed',
                               'release_spin_rate', 'release_extension'], inplace=True)
"""

In [235]:
#all_2020_stats_df = all_2020_stats_df.dropna(axis=0)

In [236]:
#all_2020_stats_df.reset_index(inplace=True)

In [237]:
#all_2020_stats_df.drop('index', axis=1)

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,vy0,vz0,ax,ay,az,release_pos_y,pitch_name
0,SI,2020-09-27,88.9,2.98,5.29,"PÃ©rez, Oliver",424144,L,2020,-12.281452,-129.035204,-0.989660,20.383213,23.814852,-26.805910,54.34,Sinker
1,SL,2020-09-27,74.8,2.10,5.73,"PÃ©rez, Oliver",424144,L,2020,-2.377321,-108.933706,0.610107,-4.717873,18.807153,-34.566989,54.28,Slider
2,SL,2020-09-27,75.3,2.01,5.74,"PÃ©rez, Oliver",424144,L,2020,-4.185552,-109.704080,-2.514557,-6.942147,18.406492,-34.069642,54.35,Slider
3,SL,2020-09-27,75.8,2.38,5.20,"PÃ©rez, Oliver",424144,L,2020,-6.816068,-110.223832,0.343225,-3.627673,18.464630,-32.767026,54.38,Slider
4,SL,2020-09-27,75.0,2.70,5.15,"PÃ©rez, Oliver",424144,L,2020,-6.094674,-109.181088,0.249817,-2.756490,18.526994,-33.136746,54.16,Slider
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131170,FC,2020-07-25,84.5,2.99,4.99,"Yarbrough, Ryan",642232,L,2020,-6.460159,-123.019148,-1.305808,-0.528992,22.870380,-23.006810,53.53,Cutter
131171,FC,2020-07-25,86.2,2.93,4.93,"Yarbrough, Ryan",642232,L,2020,-7.496199,-125.431888,-1.008751,1.494699,25.298971,-21.592304,53.67,Cutter
131172,FC,2020-07-25,84.0,3.08,4.95,"Yarbrough, Ryan",642232,L,2020,-4.905397,-122.368727,-0.873244,-1.433915,22.925346,-22.045424,53.77,Cutter
131173,FC,2020-07-25,83.3,2.91,5.03,"Yarbrough, Ryan",642232,L,2020,-8.406398,-121.098419,1.309863,0.968236,22.529711,-22.522682,53.82,Cutter
131174,SI,2020-07-25,88.3,2.50,5.62,"Yarbrough, Ryan",642232,L,2020,-8.490573,-128.299282,-3.881882,13.916636,27.271728,-18.517555,53.68,Sinker

In [238]:
"""
# Group by 'game_date' and 'pitcher' to calculate the total pitches
total_pitches = all_2020_stats_df.groupby(['game_date', 'pitcher', 'player_name']).size().reset_index(name='total_pitches')

# Group by 'game_date', 'pitcher', and 'pitch_type' to calculate the sum total of each pitch_type
total_pitches_by_type = all_2020_stats_df.groupby(['game_date', 'pitcher', 'player_name', 'pitch_type']).size().reset_index(name='count_by_pitch_type')

# Calculate averages of the specified metrics for each pitch type, grouped by game_date and pitcher
avg_metrics = all_2020_stats_df.groupby(['game_date', 'pitcher', 'player_name', 'pitch_type']).agg({
    'release_speed': 'mean',
    'release_pos_x': 'mean',
    'release_pos_z': 'mean',
    'vx0': 'mean',
    'vy0': 'mean',
    'vz0': 'mean',
    'ax': 'mean',
    'ay': 'mean',
    'az': 'mean',
    'release_pos_y': 'mean',
}).reset_index()

grouped_2020_df = total_pitches.merge(total_pitches_by_type, on=['game_date', 'pitcher', 'player_name'], how='left')
grouped_2020_df = grouped_2020_df.merge(avg_metrics, on=['game_date', 'pitcher', 'player_name', 'pitch_type'], how='left')

grouped_2020_df.head()
"""

,game_date,pitcher,player_name,total_pitches,pitch_type,count_by_pitch_type,release_speed,release_pos_x,release_pos_z,vx0,vy0,vz0,ax,ay,az,release_pos_y
0,2020-07-23,453286,"Scherzer, Max",99,CH,10,85.160000,-3.338000,5.277000,7.209278,-123.876290,-2.673986,-12.466199,22.869016,-30.895543,54.029000
1,2020-07-23,453286,"Scherzer, Max",99,CU,8,76.962500,-3.251250,5.551250,4.855014,-111.999641,-0.266828,9.097057,20.609434,-38.588100,54.156250
2,2020-07-23,453286,"Scherzer, Max",99,FC,4,91.625000,-3.377500,5.157500,10.801746,-133.068760,-3.643193,-3.388934,25.558378,-23.253194,54.135000
3,2020-07-23,453286,"Scherzer, Max",99,FF,43,95.039535,-3.243488,5.386279,10.403437,-138.046778,-3.919061,-11.913946,28.725355,-14.844396,54.179302
4,2020-07-23,453286,"Scherzer, Max",99,SL,34,86.217647,-3.335294,5.360588,8.623404,-125.340521,-3.481782,1.530001,23.354777,-29.563498,54.256765

In [239]:
"""
grouped_2020_df['game_date'] = pd.to_datetime(grouped_2020_df['game_date'])
grouped_2020_df['season'] = grouped_2020_df['game_date'].dt.year

# Step 1: Season Total Pitches
season_total_pitches = grouped_2020_df.groupby(['pitcher', 'player_name', 'season'])['total_pitches'].sum().reset_index(name='season_total_pitches')

# Step 2: Season Total by Pitch Type
season_total_by_pitch_type = grouped_2020_df.groupby(['pitcher', 'player_name', 'season', 'pitch_type'])['count_by_pitch_type'].sum().reset_index(name='season_total_count_by_pitch_type')

# Weighted Averages Calculation Setup
weighted_avg_columns = ['release_speed', 'release_pos_x', 'release_pos_z', 'vx0', 'vy0', 'vz0', 'ax', 'ay', 'az', 'release_pos_y']
for col in weighted_avg_columns:
    grouped_2020_df[f'{col}_product'] = grouped_2020_df[col] * grouped_2020_df['count_by_pitch_type']

weighted_avg_aggregations = {f'{col}_product': 'sum' for col in weighted_avg_columns}
weighted_avg_aggregations['count_by_pitch_type'] = 'sum'

# Aggregate for weighted averages
weighted_avg_df = grouped_2020_df.groupby(['pitcher', 'player_name', 'season', 'pitch_type']).agg(weighted_avg_aggregations).reset_index()

# Calculate weighted averages
for col in weighted_avg_columns:
    weighted_avg_df[f'{col}_weighted_avg'] = weighted_avg_df[f'{col}_product'] / weighted_avg_df['count_by_pitch_type']

# Cleanup
weighted_avg_df.drop(columns=[f'{col}_product' for col in weighted_avg_columns], inplace=True)

# Merge season totals and weighted averages
final_2020_df = pd.merge(season_total_pitches, season_total_by_pitch_type, on=['pitcher', 'player_name', 'season'])
final_2020_df = pd.merge(final_2020_df, weighted_avg_df, on=['pitcher', 'player_name', 'season', 'pitch_type'])

final_2020_df.head()
"""

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,424144,"PÃ©rez, Oliver",2020,810,FF,39,39,89.520513,2.129487,5.745897,-7.840932,-130.149708,-4.256842,12.609126,25.924687,-16.737557,54.185897
1,424144,"PÃ©rez, Oliver",2020,810,SI,121,121,89.959504,2.629256,5.343471,-9.472237,-130.706890,-2.087134,18.971616,25.758959,-24.803860,54.165537
2,424144,"PÃ©rez, Oliver",2020,810,SL,121,121,76.057851,2.562893,5.286198,-3.791649,-110.731949,0.716512,-6.102009,19.328535,-33.279869,54.316033
3,425794,"Wainwright, Adam",2020,4559,CH,23,23,81.847826,-1.399130,6.176522,3.939949,-119.145473,-4.111899,-11.555960,21.819291,-26.090190,53.900435
4,425794,"Wainwright, Adam",2020,4559,CU,356,356,73.492697,-1.181770,6.308933,0.455951,-106.920727,0.374703,10.527821,21.408362,-41.397857,54.014410

In [240]:
"""
final_2020_df['player_name'] = final_2020_df['player_name'].str.lower().str.strip().str.replace(r'\*$', '', regex=True)
final_2020_df.head()
"""

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,424144,"pÃ©rez, oliver",2020,810,FF,39,39,89.520513,2.129487,5.745897,-7.840932,-130.149708,-4.256842,12.609126,25.924687,-16.737557,54.185897
1,424144,"pÃ©rez, oliver",2020,810,SI,121,121,89.959504,2.629256,5.343471,-9.472237,-130.706890,-2.087134,18.971616,25.758959,-24.803860,54.165537
2,424144,"pÃ©rez, oliver",2020,810,SL,121,121,76.057851,2.562893,5.286198,-3.791649,-110.731949,0.716512,-6.102009,19.328535,-33.279869,54.316033
3,425794,"wainwright, adam",2020,4559,CH,23,23,81.847826,-1.399130,6.176522,3.939949,-119.145473,-4.111899,-11.555960,21.819291,-26.090190,53.900435
4,425794,"wainwright, adam",2020,4559,CU,356,356,73.492697,-1.181770,6.308933,0.455951,-106.920727,0.374703,10.527821,21.408362,-41.397857,54.014410

In [241]:
"""
def remove_accents(input_str):
    nfkd_form = unicodedata.normalize('NFKD', input_str)
    return "".join([c for c in nfkd_form if not unicodedata.combining(c)])

def clean_name(name):
    name = name.lower()
    name = remove_accents(name)
    name = re.sub(r'[-.]', '', name)
    name = re.sub(r'\s+', ' ', name).strip()
    return name

final_2020_df['player_name'] = final_2020_df['player_name'].apply(clean_name)
"""

In [242]:
"""
# Convert 'player_name' from "last name, first name" to "first name last name"
final_2020_df['Name'] = final_2020_df['player_name'].apply(lambda x: ' '.join(x.split(', ')[::-1]))
"""

In [243]:
"""# Now, you can perform the merge using 'Name' and 'season' as the keys for both DataFrames
better_2020_df = pd.merge(final_2020_df, 
                          cleaning_filtered_df[['Name', 'season', 'Age']],
                          on=['Name', 'season'],
                          how='left')
"""

In [244]:
#better_2020_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 945 entries, 0 to 944
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   pitcher                           945 non-null    int64
 1   player_name                       945 non-null    object
 2   season                            945 non-null    int32
 3   season_total_pitches              945 non-null    int64
 4   pitch_type                        945 non-null    object
 5   season_total_count_by_pitch_type  945 non-null    int64
 6   count_by_pitch_type               945 non-null    int64
 7   release_speed_weighted_avg        945 non-null    float64
 8   release_pos_x_weighted_avg        945 non-null    float64
 9   release_pos_z_weighted_avg        945 non-null    float64
 10  vx0_weighted_avg                  945 non-null    float64
 11  vy0_weighted_avg                  945 non-null    float64
 12  vz0_weighted_avg                  945 non-null    float64
 13  ax_weighted_avg                   945 non-null    float64
 14  ay_weighted_avg                   945 non-null    float64
 15  az_weighted_avg                   945 non-null    float64
 16  release_pos_y_weighted_avg        945 non-null    float64
 17  Name                              945 non-null    object
 18  Age                               856 non-null    float64
dtypes: float64(11), int32(1), int64(4), object(3)
memory usage: 136.7+ KB

In [245]:
#better_2020_df.head()

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg,Name,Age
0,424144,"perez, oliver",2020,810,FF,39,39,89.520513,2.129487,5.745897,-7.840932,-130.149708,-4.256842,12.609126,25.924687,-16.737557,54.185897,oliver perez,NaN
1,424144,"perez, oliver",2020,810,SI,121,121,89.959504,2.629256,5.343471,-9.472237,-130.706890,-2.087134,18.971616,25.758959,-24.803860,54.165537,oliver perez,NaN
2,424144,"perez, oliver",2020,810,SL,121,121,76.057851,2.562893,5.286198,-3.791649,-110.731949,0.716512,-6.102009,19.328535,-33.279869,54.316033,oliver perez,NaN
3,425794,"wainwright, adam",2020,4559,CH,23,23,81.847826,-1.399130,6.176522,3.939949,-119.145473,-4.111899,-11.555960,21.819291,-26.090190,53.900435,adam wainwright,38.0
4,425794,"wainwright, adam",2020,4559,CU,356,356,73.492697,-1.181770,6.308933,0.455951,-106.920727,0.374703,10.527821,21.408362,-41.397857,54.014410,adam wainwright,38.0

In [246]:
#better_2020_df.to_csv('data/better_2020_df.csv')

2021

In [247]:
#all_2021_stats_df = pd.read_csv('~/Documents/Flatiron/Project_5_/data/all_2021_stats_df.csv', index_col=0)

In [248]:
"""
all_2021_stats_df.drop(columns=['batter', 'events', 'description', 'zone',
                                'des', 'game_type', 'stand', 'home_team',
                                'away_team', 'type', 'hit_location', 'bb_type',
                                'balls', 'strikes', 'pfx_x', 'spin_dir', 
                                'pfx_z', 'plate_x', 'plate_z', 'on_3b',
                                'on_2b', 'on_1b', 'outs_when_up', 'inning',
                                'inning_topbot', 'hc_x', 'hc_y', 'fielder_2',
                                'umpire', 'sv_id', 'hit_distance_sc', 'sz_top',
                                 'sz_bot', 'launch_speed', 'launch_angle', 'game_pk',
                                'pitcher.1', 'fielder_2.1', 'fielder_3', 'fielder_4',
                                'fielder_5', 'fielder_6', 'fielder_7', 'fielder_8',
                                'fielder_9', 'estimated_ba_using_speedangle',
                                'estimated_woba_using_speedangle', 'babip_value',
                                'launch_speed_angle', 'woba_value', 'woba_denom', 'iso_value', 
                                'at_bat_number', 'pitch_number', 'home_score', 'away_score',
                                'bat_score', 'fld_score', 'post_home_score', 'post_bat_score',
                                'post_fld_score', 'post_away_score', 'if_fielding_alignment',
                                'of_fielding_alignment', 'delta_home_win_exp',
                                'delta_run_exp', 'spin_rate_deprecated', 'break_angle_deprecated',
                               'break_length_deprecated', 'tfs_deprecated', 'tfs_zulu_deprecated'], inplace=True)
all_2021_stats_df.head()
"""

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,...,vz0,ax,ay,az,effective_speed,release_spin_rate,release_extension,release_pos_y,pitch_name,spin_axis
0,SL,2021-04-22,77.1,2.64,5.04,"PÃ©rez, Oliver",424144,L,2021,-4.994353,...,-0.029166,-5.411125,18.340375,-32.951282,77.0,2025.0,6.0,54.54,Slider,295.0
1,SI,2021-04-22,89.2,2.40,5.35,"PÃ©rez, Oliver",424144,L,2021,-12.068774,...,-5.521146,20.596848,25.546150,-25.681085,89.0,1969.0,6.3,54.21,Sinker,128.0
2,SL,2021-04-22,75.8,2.80,5.12,"PÃ©rez, Oliver",424144,L,2021,-4.343389,...,1.596070,-6.340327,19.600470,-32.992715,75.2,2077.0,5.9,54.63,Slider,278.0
3,SL,2021-04-22,75.7,2.49,5.24,"PÃ©rez, Oliver",424144,L,2021,-2.947061,...,-0.821613,-6.826509,19.227540,-35.577637,75.6,2090.0,6.1,54.42,Slider,293.0
4,SL,2021-04-22,77.5,2.51,5.35,"PÃ©rez, Oliver",424144,L,2021,-4.293105,...,-1.364256,-5.827371,19.577191,-33.681240,77.2,2230.0,5.9,54.62,Slider,298.0

In [249]:
"""
all_2021_stats_df.drop(columns=['spin_axis', 'effective_speed',
                               'release_spin_rate', 'release_extension'], inplace=True)
"""

In [250]:
#all_2021_stats_df = all_2021_stats_df.dropna(axis=0)

In [251]:
#all_2021_stats_df.reset_index(inplace=True)

In [252]:
#all_2021_stats_df.drop('index', axis=1)

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,vy0,vz0,ax,ay,az,release_pos_y,pitch_name
0,SL,2021-04-22,77.1,2.64,5.04,"PÃ©rez, Oliver",424144,L,2021,-4.994353,-112.301166,-0.029166,-5.411125,18.340375,-32.951282,54.54,Slider
1,SI,2021-04-22,89.2,2.40,5.35,"PÃ©rez, Oliver",424144,L,2021,-12.068774,-129.268281,-5.521146,20.596848,25.546150,-25.681085,54.21,Sinker
2,SL,2021-04-22,75.8,2.80,5.12,"PÃ©rez, Oliver",424144,L,2021,-4.343389,-110.279975,1.596070,-6.340327,19.600470,-32.992715,54.63,Slider
3,SL,2021-04-22,75.7,2.49,5.24,"PÃ©rez, Oliver",424144,L,2021,-2.947061,-110.277133,-0.821613,-6.826509,19.227540,-35.577637,54.42,Slider
4,SL,2021-04-22,77.5,2.51,5.35,"PÃ©rez, Oliver",424144,L,2021,-4.293105,-112.915576,-1.364256,-5.827371,19.577191,-33.681240,54.62,Slider
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349392,FC,2021-04-02,80.4,2.97,5.19,"Yarbrough, Ryan",642232,L,2021,-6.941866,-116.842057,2.538122,-2.407899,21.550603,-28.315896,54.23,Cutter
349393,FC,2021-04-02,78.0,2.93,5.33,"Yarbrough, Ryan",642232,L,2021,-4.393366,-113.469491,5.358616,-4.010691,20.324781,-31.365379,54.26,Cutter
349394,CH,2021-04-02,77.7,2.40,5.72,"Yarbrough, Ryan",642232,L,2021,-5.088565,-113.034606,-2.115300,15.016157,22.156832,-24.777378,54.01,Changeup
349395,CH,2021-04-02,78.3,2.41,5.66,"Yarbrough, Ryan",642232,L,2021,-5.959473,-113.862229,-3.262805,15.839047,22.678801,-28.383158,54.18,Changeup
349396,SI,2021-04-02,84.0,2.32,5.97,"Yarbrough, Ryan",642232,L,2021,-6.439867,-122.162988,-4.397571,11.105702,25.535242,-17.419112,54.19,Sinker

In [253]:
"""# Group by 'game_date' and 'pitcher' to calculate the total pitches
total_pitches = all_2021_stats_df.groupby(['game_date', 'pitcher', 'player_name']).size().reset_index(name='total_pitches')

# Group by 'game_date', 'pitcher', and 'pitch_type' to calculate the sum total of each pitch_type
total_pitches_by_type = all_2021_stats_df.groupby(['game_date', 'pitcher', 'player_name', 'pitch_type']).size().reset_index(name='count_by_pitch_type')

# Calculate averages of the specified metrics for each pitch type, grouped by game_date and pitcher
avg_metrics = all_2021_stats_df.groupby(['game_date', 'pitcher', 'player_name', 'pitch_type']).agg({
    'release_speed': 'mean',
    'release_pos_x': 'mean',
    'release_pos_z': 'mean',
    'vx0': 'mean',
    'vy0': 'mean',
    'vz0': 'mean',
    'ax': 'mean',
    'ay': 'mean',
    'az': 'mean',
    'release_pos_y': 'mean',
}).reset_index()

grouped_2021_df = total_pitches.merge(total_pitches_by_type, on=['game_date', 'pitcher', 'player_name'], how='left')
grouped_2021_df = grouped_2021_df.merge(avg_metrics, on=['game_date', 'pitcher', 'player_name', 'pitch_type'], how='left')

grouped_2021_df.head()
"""

,game_date,pitcher,player_name,total_pitches,pitch_type,count_by_pitch_type,release_speed,release_pos_x,release_pos_z,vx0,vy0,vz0,ax,ay,az,release_pos_y
0,2021-04-01,425844,"Greinke, Zack",82,CH,20,86.980000,-1.844500,6.240000,4.828009,-126.479509,-6.668000,-12.306288,25.056190,-26.387963,54.353000
1,2021-04-01,425844,"Greinke, Zack",82,CU,14,71.978571,-1.740000,6.279286,1.723053,-104.718069,0.256374,7.187579,20.484950,-39.669285,54.455714
2,2021-04-01,425844,"Greinke, Zack",82,FF,35,88.600000,-1.834857,6.276571,4.529760,-128.863649,-6.167951,-1.719817,26.257371,-16.546970,54.318000
3,2021-04-01,425844,"Greinke, Zack",82,SL,13,81.515385,-1.974615,6.358462,3.742444,-118.652480,-3.717340,6.064068,22.818517,-33.496252,54.375385
4,2021-04-01,433589,"Petit, Yusmeiro",11,CH,2,79.700000,-2.220000,5.565000,5.038482,-115.953282,-1.490509,-10.934707,22.394118,-21.609805,53.265000

In [254]:
"""
grouped_2021_df['game_date'] = pd.to_datetime(grouped_2021_df['game_date'])
grouped_2021_df['season'] = grouped_2021_df['game_date'].dt.year

# Step 1: Season Total Pitches
season_total_pitches = grouped_2021_df.groupby(['pitcher', 'player_name', 'season'])['total_pitches'].sum().reset_index(name='season_total_pitches')

# Step 2: Season Total by Pitch Type
season_total_by_pitch_type = grouped_2021_df.groupby(['pitcher', 'player_name', 'season', 'pitch_type'])['count_by_pitch_type'].sum().reset_index(name='season_total_count_by_pitch_type')

# Weighted Averages Calculation Setup
weighted_avg_columns = ['release_speed', 'release_pos_x', 'release_pos_z', 'vx0', 'vy0', 'vz0', 'ax', 'ay', 'az', 'release_pos_y']
for col in weighted_avg_columns:
    grouped_2021_df[f'{col}_product'] = grouped_2021_df[col] * grouped_2021_df['count_by_pitch_type']

weighted_avg_aggregations = {f'{col}_product': 'sum' for col in weighted_avg_columns}
weighted_avg_aggregations['count_by_pitch_type'] = 'sum'

# Aggregate for weighted averages
weighted_avg_df = grouped_2021_df.groupby(['pitcher', 'player_name', 'season', 'pitch_type']).agg(weighted_avg_aggregations).reset_index()

# Calculate weighted averages
for col in weighted_avg_columns:
    weighted_avg_df[f'{col}_weighted_avg'] = weighted_avg_df[f'{col}_product'] / weighted_avg_df['count_by_pitch_type']

# Cleanup
weighted_avg_df.drop(columns=[f'{col}_product' for col in weighted_avg_columns], inplace=True)

# Merge season totals and weighted averages
final_2021_df = pd.merge(season_total_pitches, season_total_by_pitch_type, on=['pitcher', 'player_name', 'season'])
final_2021_df = pd.merge(final_2021_df, weighted_avg_df, on=['pitcher', 'player_name', 'season', 'pitch_type'])

final_2021_df.head()
"""

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,424144,"PÃ©rez, Oliver",2021,168,FF,12,12,88.925000,2.095833,5.750833,-8.655121,-129.162072,-4.748852,13.550496,26.530789,-16.935946,54.236667
1,424144,"PÃ©rez, Oliver",2021,168,SI,26,26,89.211538,2.453462,5.387308,-8.304638,-129.649446,-2.918503,19.609363,26.613081,-24.455613,54.227308
2,424144,"PÃ©rez, Oliver",2021,168,SL,18,18,75.938889,2.497222,5.275556,-4.443050,-110.550929,-0.091396,-5.435074,19.534750,-33.912365,54.515000
3,425794,"Wainwright, Adam",2021,16523,CH,196,196,82.740816,-1.333469,6.221888,4.252372,-120.425561,-4.381126,-12.050485,22.222483,-25.264899,54.000306
4,425794,"Wainwright, Adam",2021,16523,CS,13,13,65.423077,-1.343846,6.389231,-0.149149,-95.070420,2.627888,7.397234,17.501637,-40.406583,54.313077

In [255]:
"""
final_2021_df['player_name'] = final_2021_df['player_name'].str.lower().str.strip().str.replace(r'\*$', '', regex=True)
final_2021_df.head()
"""

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,424144,"pÃ©rez, oliver",2021,168,FF,12,12,88.925000,2.095833,5.750833,-8.655121,-129.162072,-4.748852,13.550496,26.530789,-16.935946,54.236667
1,424144,"pÃ©rez, oliver",2021,168,SI,26,26,89.211538,2.453462,5.387308,-8.304638,-129.649446,-2.918503,19.609363,26.613081,-24.455613,54.227308
2,424144,"pÃ©rez, oliver",2021,168,SL,18,18,75.938889,2.497222,5.275556,-4.443050,-110.550929,-0.091396,-5.435074,19.534750,-33.912365,54.515000
3,425794,"wainwright, adam",2021,16523,CH,196,196,82.740816,-1.333469,6.221888,4.252372,-120.425561,-4.381126,-12.050485,22.222483,-25.264899,54.000306
4,425794,"wainwright, adam",2021,16523,CS,13,13,65.423077,-1.343846,6.389231,-0.149149,-95.070420,2.627888,7.397234,17.501637,-40.406583,54.313077

In [256]:
"""
def remove_accents(input_str):
    nfkd_form = unicodedata.normalize('NFKD', input_str)
    return "".join([c for c in nfkd_form if not unicodedata.combining(c)])

def clean_name(name):
    name = name.lower()
    name = remove_accents(name)
    name = re.sub(r'[-.]', '', name)
    name = re.sub(r'\s+', ' ', name).strip()
    return name

final_2021_df['player_name'] = final_2021_df['player_name'].apply(clean_name)
"""

In [257]:
"""
# Convert 'player_name' from "last name, first name" to "first name last name"
final_2021_df['Name'] = final_2021_df['player_name'].apply(lambda x: ' '.join(x.split(', ')[::-1]))
"""

In [258]:
"""
# Now, you can perform the merge using 'Name' and 'season' as the keys for both DataFrames
better_2021_df = pd.merge(final_2021_df, 
                          cleaning_filtered_df[['Name', 'season', 'Age']],
                          on=['Name', 'season'],
                          how='left')
"""

In [259]:
#better_2021_df.head()

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg,Name,Age
0,424144,"perez, oliver",2021,168,FF,12,12,88.925000,2.095833,5.750833,-8.655121,-129.162072,-4.748852,13.550496,26.530789,-16.935946,54.236667,oliver perez,NaN
1,424144,"perez, oliver",2021,168,SI,26,26,89.211538,2.453462,5.387308,-8.304638,-129.649446,-2.918503,19.609363,26.613081,-24.455613,54.227308,oliver perez,NaN
2,424144,"perez, oliver",2021,168,SL,18,18,75.938889,2.497222,5.275556,-4.443050,-110.550929,-0.091396,-5.435074,19.534750,-33.912365,54.515000,oliver perez,NaN
3,425794,"wainwright, adam",2021,16523,CH,196,196,82.740816,-1.333469,6.221888,4.252372,-120.425561,-4.381126,-12.050485,22.222483,-25.264899,54.000306,adam wainwright,39.0
4,425794,"wainwright, adam",2021,16523,CS,13,13,65.423077,-1.343846,6.389231,-0.149149,-95.070420,2.627888,7.397234,17.501637,-40.406583,54.313077,adam wainwright,39.0

In [260]:
#better_2021_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1024 entries, 0 to 1023
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   pitcher                           1024 non-null   int64
 1   player_name                       1024 non-null   object
 2   season                            1024 non-null   int32
 3   season_total_pitches              1024 non-null   int64
 4   pitch_type                        1024 non-null   object
 5   season_total_count_by_pitch_type  1024 non-null   int64
 6   count_by_pitch_type               1024 non-null   int64
 7   release_speed_weighted_avg        1024 non-null   float64
 8   release_pos_x_weighted_avg        1024 non-null   float64
 9   release_pos_z_weighted_avg        1024 non-null   float64
 10  vx0_weighted_avg                  1024 non-null   float64
 11  vy0_weighted_avg                  1024 non-null   float64
 12  vz0_weighted_avg                  1024 non-null   float64
 13  ax_weighted_avg                   1024 non-null   float64
 14  ay_weighted_avg                   1024 non-null   float64
 15  az_weighted_avg                   1024 non-null   float64
 16  release_pos_y_weighted_avg        1024 non-null   float64
 17  Name                              1024 non-null   object
 18  Age                               932 non-null    float64
dtypes: float64(11), int32(1), int64(4), object(3)
memory usage: 148.1+ KB

In [261]:
#better_2021_df.to_csv('data/better_2021_df.csv')

2022

In [262]:
#all_2022_stats_df = pd.read_csv('~/Documents/Flatiron/Project_5_/data/all_2022_stats_df.csv', index_col=0)

In [263]:
"""all_2022_stats_df.drop(columns=['batter', 'events', 'description', 'zone',
                                'des', 'game_type', 'stand', 'home_team',
                                'away_team', 'type', 'hit_location', 'bb_type',
                                'balls', 'strikes', 'pfx_x', 'spin_dir', 
                                'pfx_z', 'plate_x', 'plate_z', 'on_3b',
                                'on_2b', 'on_1b', 'outs_when_up', 'inning',
                                'inning_topbot', 'hc_x', 'hc_y', 'fielder_2',
                                'umpire', 'sv_id', 'hit_distance_sc', 'sz_top',
                                 'sz_bot', 'launch_speed', 'launch_angle', 'game_pk',
                                'pitcher.1', 'fielder_2.1', 'fielder_3', 'fielder_4',
                                'fielder_5', 'fielder_6', 'fielder_7', 'fielder_8',
                                'fielder_9', 'estimated_ba_using_speedangle',
                                'estimated_woba_using_speedangle', 'babip_value',
                                'launch_speed_angle', 'woba_value', 'woba_denom', 'iso_value', 
                                'at_bat_number', 'pitch_number', 'home_score', 'away_score',
                                'bat_score', 'fld_score', 'post_home_score', 'post_bat_score',
                                'post_fld_score', 'post_away_score', 'if_fielding_alignment',
                                'of_fielding_alignment', 'delta_home_win_exp',
                                'delta_run_exp', 'spin_rate_deprecated', 'break_angle_deprecated',
                               'break_length_deprecated', 'tfs_deprecated', 'tfs_zulu_deprecated'], inplace=True)
all_2022_stats_df.head()
"""

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,...,vz0,ax,ay,az,effective_speed,release_spin_rate,release_extension,release_pos_y,pitch_name,spin_axis
0,SI,2022-04-24,87.8,2.74,5.20,"PÃ©rez, Oliver",424144,L,2022,-10.477507,...,-0.366773,19.671555,27.844065,-26.459826,87.2,2103.0,6.2,54.26,Sinker,122.0
1,SL,2022-04-24,75.8,2.12,5.60,"PÃ©rez, Oliver",424144,L,2022,-4.762824,...,-1.231512,-3.993342,22.764887,-34.864845,74.9,2236.0,6.1,54.44,Slider,309.0
2,SI,2022-04-24,87.3,2.45,5.41,"PÃ©rez, Oliver",424144,L,2022,-11.401632,...,-2.685717,20.323170,27.956678,-25.185323,86.5,2147.0,6.2,54.33,Sinker,129.0
3,SL,2022-04-24,76.9,2.35,5.38,"PÃ©rez, Oliver",424144,L,2022,-8.348966,...,-1.776512,-3.334614,23.340520,-33.618566,76.0,2177.0,6.2,54.30,Slider,300.0
4,SI,2022-04-24,87.1,2.49,5.42,"PÃ©rez, Oliver",424144,L,2022,-9.024408,...,-1.217999,18.127908,27.565163,-24.672644,86.7,2163.0,6.3,54.22,Sinker,133.0

In [264]:
"""all_2022_stats_df.drop(columns=['spin_axis', 'effective_speed',
                               'release_spin_rate', 'release_extension'], inplace=True)
"""

In [265]:
#all_2022_stats_df = all_2022_stats_df.dropna(axis=0)

In [266]:
#all_2022_stats_df.reset_index(inplace=True)

In [268]:
#all_2022_stats_df.drop('index', axis=1)

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,vy0,vz0,ax,ay,az,release_pos_y,pitch_name
0,SI,2022-04-24,87.8,2.74,5.20,"PÃ©rez, Oliver",424144,L,2022,-10.477507,-127.387193,-0.366773,19.671555,27.844065,-26.459826,54.26,Sinker
1,SL,2022-04-24,75.8,2.12,5.60,"PÃ©rez, Oliver",424144,L,2022,-4.762824,-110.159167,-1.231512,-3.993342,22.764887,-34.864845,54.44,Slider
2,SI,2022-04-24,87.3,2.45,5.41,"PÃ©rez, Oliver",424144,L,2022,-11.401632,-126.497800,-2.685717,20.323170,27.956678,-25.185323,54.33,Sinker
3,SL,2022-04-24,76.9,2.35,5.38,"PÃ©rez, Oliver",424144,L,2022,-8.348966,-111.579505,-1.776512,-3.334614,23.340520,-33.618566,54.30,Slider
4,SI,2022-04-24,87.1,2.49,5.42,"PÃ©rez, Oliver",424144,L,2022,-9.024408,-126.547500,-1.217999,18.127908,27.565163,-24.672644,54.22,Sinker
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329818,CH,2022-05-03,78.1,2.68,5.26,"Yarbrough, Ryan",642232,L,2022,-7.979635,-113.442978,-1.795577,10.714386,20.629198,-28.628349,53.98,Changeup
329819,FC,2022-05-03,83.1,3.05,5.03,"Yarbrough, Ryan",642232,L,2022,-8.334581,-120.930494,0.083679,1.480248,21.031878,-27.127189,54.06,Cutter
329820,FC,2022-05-03,81.8,2.98,5.14,"Yarbrough, Ryan",642232,L,2022,-9.122636,-118.907071,0.949405,2.709974,21.832306,-28.555316,54.03,Cutter
329821,CH,2022-05-03,77.8,2.60,5.39,"Yarbrough, Ryan",642232,L,2022,-8.402330,-112.938932,-2.259328,14.265565,21.751116,-28.037212,53.99,Changeup
329822,SI,2022-05-03,84.5,2.51,5.62,"Yarbrough, Ryan",642232,L,2022,-9.440585,-122.667165,-4.069518,14.755215,24.446936,-21.065933,54.02,Sinker

In [269]:
"""
# Group by 'game_date' and 'pitcher' to calculate the total pitches
total_pitches = all_2022_stats_df.groupby(['game_date', 'pitcher', 'player_name']).size().reset_index(name='total_pitches')

# Group by 'game_date', 'pitcher', and 'pitch_type' to calculate the sum total of each pitch_type
total_pitches_by_type = all_2022_stats_df.groupby(['game_date', 'pitcher', 'player_name', 'pitch_type']).size().reset_index(name='count_by_pitch_type')

# Calculate averages of the specified metrics for each pitch type, grouped by game_date and pitcher
avg_metrics = all_2022_stats_df.groupby(['game_date', 'pitcher', 'player_name', 'pitch_type']).agg({
    'release_speed': 'mean',
    'release_pos_x': 'mean',
    'release_pos_z': 'mean',
    'vx0': 'mean',
    'vy0': 'mean',
    'vz0': 'mean',
    'ax': 'mean',
    'ay': 'mean',
    'az': 'mean',
    'release_pos_y': 'mean',
}).reset_index()

grouped_2022_df = total_pitches.merge(total_pitches_by_type, on=['game_date', 'pitcher', 'player_name'], how='left')
grouped_2022_df = grouped_2022_df.merge(avg_metrics, on=['game_date', 'pitcher', 'player_name', 'pitch_type'], how='left')

grouped_2022_df.head()
"""

,game_date,pitcher,player_name,total_pitches,pitch_type,count_by_pitch_type,release_speed,release_pos_x,release_pos_z,vx0,vy0,vz0,ax,ay,az,release_pos_y
0,2022-04-07,424144,"PÃ©rez, Oliver",17,FF,1,89.900000,2.0300,5.74000,-9.318359,-130.529360,-2.925789,12.843168,30.543254,-13.743155,54.240000
1,2022-04-07,424144,"PÃ©rez, Oliver",17,SI,8,89.537500,2.5925,5.29250,-9.355620,-130.026518,-2.247511,19.655219,27.230138,-24.481376,54.248750
2,2022-04-07,424144,"PÃ©rez, Oliver",17,SL,8,77.200000,2.5975,5.26125,-5.923038,-112.245885,-0.436273,-3.795038,21.592220,-32.916980,54.345000
3,2022-04-07,425794,"Wainwright, Adam",81,CH,9,81.844444,-1.3300,6.27000,5.590011,-119.032142,-4.480621,-13.473002,22.912257,-24.876686,54.013333
4,2022-04-07,425794,"Wainwright, Adam",81,CS,2,69.150000,-1.2300,6.52000,-0.140925,-100.466403,2.325922,9.639156,20.962770,-41.685075,54.340000

In [270]:
"""
grouped_2022_df['game_date'] = pd.to_datetime(grouped_2022_df['game_date'])
grouped_2022_df['season'] = grouped_2022_df['game_date'].dt.year

# Step 1: Season Total Pitches
season_total_pitches = grouped_2022_df.groupby(['pitcher', 'player_name', 'season'])['total_pitches'].sum().reset_index(name='season_total_pitches')

# Step 2: Season Total by Pitch Type
season_total_by_pitch_type = grouped_2022_df.groupby(['pitcher', 'player_name', 'season', 'pitch_type'])['count_by_pitch_type'].sum().reset_index(name='season_total_count_by_pitch_type')

# Weighted Averages Calculation Setup
weighted_avg_columns = ['release_speed', 'release_pos_x', 'release_pos_z', 'vx0', 'vy0', 'vz0', 'ax', 'ay', 'az', 'release_pos_y']
for col in weighted_avg_columns:
    grouped_2022_df[f'{col}_product'] = grouped_2022_df[col] * grouped_2022_df['count_by_pitch_type']

weighted_avg_aggregations = {f'{col}_product': 'sum' for col in weighted_avg_columns}
weighted_avg_aggregations['count_by_pitch_type'] = 'sum'

# Aggregate for weighted averages
weighted_avg_df = grouped_2022_df.groupby(['pitcher', 'player_name', 'season', 'pitch_type']).agg(weighted_avg_aggregations).reset_index()

# Calculate weighted averages
for col in weighted_avg_columns:
    weighted_avg_df[f'{col}_weighted_avg'] = weighted_avg_df[f'{col}_product'] / weighted_avg_df['count_by_pitch_type']

# Cleanup
weighted_avg_df.drop(columns=[f'{col}_product' for col in weighted_avg_columns], inplace=True)

# Merge season totals and weighted averages
final_2022_df = pd.merge(season_total_pitches, season_total_by_pitch_type, on=['pitcher', 'player_name', 'season'])
final_2022_df = pd.merge(final_2022_df, weighted_avg_df, on=['pitcher', 'player_name', 'season', 'pitch_type'])

final_2022_df.head()
"""

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,424144,"PÃ©rez, Oliver",2022,179,FF,3,3,88.200000,2.146667,5.686667,-7.529349,-128.207624,-2.140213,12.110056,28.717999,-16.369227,54.323333
1,424144,"PÃ©rez, Oliver",2022,179,SI,43,43,88.374419,2.515349,5.368140,-9.023629,-128.309051,-2.396761,18.232210,28.215470,-24.538407,54.325581
2,424144,"PÃ©rez, Oliver",2022,179,SL,27,27,76.581481,2.511111,5.314444,-4.872970,-111.373723,-0.449206,-5.493451,21.330117,-33.493125,54.434815
3,425794,"Wainwright, Adam",2022,17279,CH,189,189,82.182540,-1.314709,6.223757,3.940298,-119.609919,-4.155740,-12.225405,22.425823,-25.149843,54.075979
4,425794,"Wainwright, Adam",2022,17279,CS,33,33,67.660606,-1.290909,6.383030,-0.424688,-98.354011,2.535486,8.542947,18.129059,-40.748865,54.366364

In [271]:
"""
final_2022_df['player_name'] = final_2022_df['player_name'].str.lower().str.strip().str.replace(r'\*$', '', regex=True)
final_2022_df.head()
"""

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,424144,"pÃ©rez, oliver",2022,179,FF,3,3,88.200000,2.146667,5.686667,-7.529349,-128.207624,-2.140213,12.110056,28.717999,-16.369227,54.323333
1,424144,"pÃ©rez, oliver",2022,179,SI,43,43,88.374419,2.515349,5.368140,-9.023629,-128.309051,-2.396761,18.232210,28.215470,-24.538407,54.325581
2,424144,"pÃ©rez, oliver",2022,179,SL,27,27,76.581481,2.511111,5.314444,-4.872970,-111.373723,-0.449206,-5.493451,21.330117,-33.493125,54.434815
3,425794,"wainwright, adam",2022,17279,CH,189,189,82.182540,-1.314709,6.223757,3.940298,-119.609919,-4.155740,-12.225405,22.425823,-25.149843,54.075979
4,425794,"wainwright, adam",2022,17279,CS,33,33,67.660606,-1.290909,6.383030,-0.424688,-98.354011,2.535486,8.542947,18.129059,-40.748865,54.366364

In [272]:
"""
def remove_accents(input_str):
    nfkd_form = unicodedata.normalize('NFKD', input_str)
    return "".join([c for c in nfkd_form if not unicodedata.combining(c)])

def clean_name(name):
    name = name.lower()
    name = remove_accents(name)
    name = re.sub(r'[-.]', '', name)
    name = re.sub(r'\s+', ' ', name).strip()
    return name

final_2022_df['player_name'] = final_2022_df['player_name'].apply(clean_name)
"""

In [273]:
"""
# Convert 'player_name' from "last name, first name" to "first name last name"
final_2022_df['Name'] = final_2022_df['player_name'].apply(lambda x: ' '.join(x.split(', ')[::-1]))
"""

In [274]:
"""
# Now, you can perform the merge using 'Name' and 'season' as the keys for both DataFrames
better_2022_df = pd.merge(final_2022_df, 
                          cleaning_filtered_df[['Name', 'season', 'Age']],
                          on=['Name', 'season'],
                          how='left')
"""

In [275]:
#better_2022_df.head()

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg,Name,Age
0,424144,"perez, oliver",2022,179,FF,3,3,88.200000,2.146667,5.686667,-7.529349,-128.207624,-2.140213,12.110056,28.717999,-16.369227,54.323333,oliver perez,NaN
1,424144,"perez, oliver",2022,179,SI,43,43,88.374419,2.515349,5.368140,-9.023629,-128.309051,-2.396761,18.232210,28.215470,-24.538407,54.325581,oliver perez,NaN
2,424144,"perez, oliver",2022,179,SL,27,27,76.581481,2.511111,5.314444,-4.872970,-111.373723,-0.449206,-5.493451,21.330117,-33.493125,54.434815,oliver perez,NaN
3,425794,"wainwright, adam",2022,17279,CH,189,189,82.182540,-1.314709,6.223757,3.940298,-119.609919,-4.155740,-12.225405,22.425823,-25.149843,54.075979,adam wainwright,40.0
4,425794,"wainwright, adam",2022,17279,CS,33,33,67.660606,-1.290909,6.383030,-0.424688,-98.354011,2.535486,8.542947,18.129059,-40.748865,54.366364,adam wainwright,40.0

In [276]:
#better_2022_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 981 entries, 0 to 980
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   pitcher                           981 non-null    int64
 1   player_name                       981 non-null    object
 2   season                            981 non-null    int32
 3   season_total_pitches              981 non-null    int64
 4   pitch_type                        981 non-null    object
 5   season_total_count_by_pitch_type  981 non-null    int64
 6   count_by_pitch_type               981 non-null    int64
 7   release_speed_weighted_avg        981 non-null    float64
 8   release_pos_x_weighted_avg        981 non-null    float64
 9   release_pos_z_weighted_avg        981 non-null    float64
 10  vx0_weighted_avg                  981 non-null    float64
 11  vy0_weighted_avg                  981 non-null    float64
 12  vz0_weighted_avg                  981 non-null    float64
 13  ax_weighted_avg                   981 non-null    float64
 14  ay_weighted_avg                   981 non-null    float64
 15  az_weighted_avg                   981 non-null    float64
 16  release_pos_y_weighted_avg        981 non-null    float64
 17  Name                              981 non-null    object
 18  Age                               882 non-null    float64
dtypes: float64(11), int32(1), int64(4), object(3)
memory usage: 141.9+ KB

In [277]:
#better_2022_df.to_csv('data/better_2022_df.csv')

2023

In [278]:
#all_2023_stats_df = pd.read_csv('~/Documents/Flatiron/Project_5_/data/all_2023_stats_df.csv', index_col=0)

In [293]:
"""all_2023_stats_df.drop(columns=['batter', 'events', 'description', 'zone',
                                'des', 'game_type', 'stand', 'home_team',
                                'away_team', 'type', 'hit_location', 'bb_type',
                                'balls', 'strikes', 'pfx_x', 'spin_dir', 
                                'pfx_z', 'plate_x', 'plate_z', 'on_3b',
                                'on_2b', 'on_1b', 'outs_when_up', 'inning',
                                'inning_topbot', 'hc_x', 'hc_y', 'fielder_2',
                                'umpire', 'sv_id', 'hit_distance_sc', 'sz_top',
                                 'sz_bot', 'launch_speed', 'launch_angle', 'game_pk',
                                'pitcher.1', 'fielder_2.1', 'fielder_3', 'fielder_4',
                                'fielder_5', 'fielder_6', 'fielder_7', 'fielder_8',
                                'fielder_9', 'estimated_ba_using_speedangle',
                                'estimated_woba_using_speedangle', 'babip_value',
                                'launch_speed_angle', 'woba_value', 'woba_denom', 'iso_value', 
                                'at_bat_number', 'pitch_number', 'home_score', 'away_score',
                                'bat_score', 'fld_score', 'post_home_score', 'post_bat_score',
                                'post_fld_score', 'post_away_score', 'if_fielding_alignment',
                                'of_fielding_alignment', 'delta_home_win_exp',
                                'delta_run_exp', 'spin_rate_deprecated', 'break_angle_deprecated',
                               'break_length_deprecated', 'tfs_deprecated', 'tfs_zulu_deprecated'], inplace=True)
all_2023_stats_df.head()
"""

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,...,vz0,ax,ay,az,effective_speed,release_spin_rate,release_extension,release_pos_y,pitch_name,spin_axis
0,FA,2023-04-14,52.1,-1.99,6.71,"PÃ©rez, Carlos",542208,R,2023,3.207484,...,4.632473,0.041683,9.422882,-28.872462,50.3,1409.0,4.5,55.97,Other,181.0
1,FA,2023-04-14,69.6,-2.30,6.58,"PÃ©rez, Carlos",542208,R,2023,5.097984,...,-1.305312,-1.659015,15.331715,-21.506290,67.3,1996.0,4.2,56.29,Other,209.0
2,FA,2023-04-14,65.1,-2.25,6.52,"PÃ©rez, Carlos",542208,R,2023,3.792762,...,-5.686951,-1.087140,14.372363,-27.730808,63.0,1725.0,4.4,56.06,Other,203.0
3,FA,2023-04-14,64.2,-2.37,6.50,"PÃ©rez, Carlos",542208,R,2023,6.962834,...,-0.385016,0.143677,13.947456,-24.517877,61.9,1768.0,4.3,56.20,Other,206.0
4,FA,2023-04-14,72.0,-2.45,6.49,"PÃ©rez, Carlos",542208,R,2023,6.066457,...,-5.760148,-6.510885,17.428031,-19.894389,69.6,1947.0,4.4,56.14,Other,222.0

In [294]:
"""
all_2023_stats_df.drop(columns=['spin_axis', 'effective_speed',
                               'release_spin_rate', 'release_extension'], inplace=True)
"""

In [295]:
#all_2023_stats_df = all_2023_stats_df.dropna(axis=0)

In [296]:
#all_2023_stats_df.reset_index(inplace=True)

In [297]:
#all_2023_stats_df.drop('index', axis=1)

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,pitcher,p_throws,game_year,vx0,vy0,vz0,ax,ay,az,release_pos_y,pitch_name
0,FA,2023-04-14,52.1,-1.99,6.71,"PÃ©rez, Carlos",542208,R,2023,3.207484,-75.567816,4.632473,0.041683,9.422882,-28.872462,55.97,Other
1,FA,2023-04-14,69.6,-2.30,6.58,"PÃ©rez, Carlos",542208,R,2023,5.097984,-101.349955,-1.305312,-1.659015,15.331715,-21.506290,56.29,Other
2,FA,2023-04-14,65.1,-2.25,6.52,"PÃ©rez, Carlos",542208,R,2023,3.792762,-94.718170,-5.686951,-1.087140,14.372363,-27.730808,56.06,Other
3,FA,2023-04-14,64.2,-2.37,6.50,"PÃ©rez, Carlos",542208,R,2023,6.962834,-93.282689,-0.385016,0.143677,13.947456,-24.517877,56.20,Other
4,FA,2023-04-14,72.0,-2.45,6.49,"PÃ©rez, Carlos",542208,R,2023,6.066457,-104.679076,-5.760148,-6.510885,17.428031,-19.894389,56.14,Other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
290106,CU,2023-04-01,70.1,3.02,5.35,"Yarbrough, Ryan",642232,L,2023,-4.986239,-101.947657,1.574009,-8.013767,16.335589,-33.143286,54.30,Curveball
290107,CU,2023-04-01,71.3,2.90,5.33,"Yarbrough, Ryan",642232,L,2023,-5.740243,-103.612875,2.628047,-9.716517,19.086301,-31.277661,54.23,Curveball
290108,CH,2023-04-01,79.6,2.71,5.48,"Yarbrough, Ryan",642232,L,2023,-7.998093,-115.608960,0.634920,13.978554,21.224275,-26.283701,54.28,Changeup
290109,SI,2023-04-01,87.8,2.84,5.59,"Yarbrough, Ryan",642232,L,2023,-8.798290,-127.583797,-1.747522,16.914240,25.116293,-22.316787,54.16,Sinker
290110,SI,2023-04-01,86.6,2.88,5.61,"Yarbrough, Ryan",642232,L,2023,-6.693130,-125.985176,-3.527661,15.448056,25.053194,-23.878824,54.33,Sinker

In [298]:
"""# Group by 'game_date' and 'pitcher' to calculate the total pitches
total_pitches = all_2023_stats_df.groupby(['game_date', 'pitcher', 'player_name']).size().reset_index(name='total_pitches')

# Group by 'game_date', 'pitcher', and 'pitch_type' to calculate the sum total of each pitch_type
total_pitches_by_type = all_2023_stats_df.groupby(['game_date', 'pitcher', 'player_name', 'pitch_type']).size().reset_index(name='count_by_pitch_type')

# Calculate averages of the specified metrics for each pitch type, grouped by game_date and pitcher
avg_metrics = all_2023_stats_df.groupby(['game_date', 'pitcher', 'player_name', 'pitch_type']).agg({
    'release_speed': 'mean',
    'release_pos_x': 'mean',
    'release_pos_z': 'mean',
    'vx0': 'mean',
    'vy0': 'mean',
    'vz0': 'mean',
    'ax': 'mean',
    'ay': 'mean',
    'az': 'mean',
    'release_pos_y': 'mean',
}).reset_index()

grouped_2023_df = total_pitches.merge(total_pitches_by_type, on=['game_date', 'pitcher', 'player_name'], how='left')
grouped_2023_df = grouped_2023_df.merge(avg_metrics, on=['game_date', 'pitcher', 'player_name', 'pitch_type'], how='left')

grouped_2023_df.head()
"""

,game_date,pitcher,player_name,total_pitches,pitch_type,count_by_pitch_type,release_speed,release_pos_x,release_pos_z,vx0,vy0,vz0,ax,ay,az,release_pos_y
0,2023-03-30,425844,"Greinke, Zack",80,CH,11,87.627273,-1.520909,6.121818,4.767156,-127.544337,-5.490345,-13.752449,23.755231,-26.014562,54.460909
1,2023-03-30,425844,"Greinke, Zack",80,CU,22,73.831818,-1.374545,6.168182,1.382591,-107.529828,0.365321,7.401075,19.367091,-39.397326,54.728182
2,2023-03-30,425844,"Greinke, Zack",80,FC,9,86.311111,-1.247778,6.278889,2.714861,-125.720972,-5.281623,6.046866,22.794688,-27.738011,54.554444
3,2023-03-30,425844,"Greinke, Zack",80,FF,6,90.366667,-1.258333,6.258333,4.030988,-131.534427,-7.167879,-0.944584,24.287110,-16.809026,54.491667
4,2023-03-30,425844,"Greinke, Zack",80,SI,13,90.707692,-1.402308,6.157692,7.035606,-131.939037,-3.372004,-16.063018,26.519280,-22.245099,54.551538

In [299]:
"""
grouped_2023_df['game_date'] = pd.to_datetime(grouped_2023_df['game_date'])
grouped_2023_df['season'] = grouped_2023_df['game_date'].dt.year

# Step 1: Season Total Pitches
season_total_pitches = grouped_2023_df.groupby(['pitcher', 'player_name', 'season'])['total_pitches'].sum().reset_index(name='season_total_pitches')

# Step 2: Season Total by Pitch Type
season_total_by_pitch_type = grouped_2023_df.groupby(['pitcher', 'player_name', 'season', 'pitch_type'])['count_by_pitch_type'].sum().reset_index(name='season_total_count_by_pitch_type')

# Weighted Averages Calculation Setup
weighted_avg_columns = ['release_speed', 'release_pos_x', 'release_pos_z', 'vx0', 'vy0', 'vz0', 'ax', 'ay', 'az', 'release_pos_y']
for col in weighted_avg_columns:
    grouped_2023_df[f'{col}_product'] = grouped_2023_df[col] * grouped_2023_df['count_by_pitch_type']

weighted_avg_aggregations = {f'{col}_product': 'sum' for col in weighted_avg_columns}
weighted_avg_aggregations['count_by_pitch_type'] = 'sum'

# Aggregate for weighted averages
weighted_avg_df = grouped_2023_df.groupby(['pitcher', 'player_name', 'season', 'pitch_type']).agg(weighted_avg_aggregations).reset_index()

# Calculate weighted averages
for col in weighted_avg_columns:
    weighted_avg_df[f'{col}_weighted_avg'] = weighted_avg_df[f'{col}_product'] / weighted_avg_df['count_by_pitch_type']

# Cleanup
weighted_avg_df.drop(columns=[f'{col}_product' for col in weighted_avg_columns], inplace=True)

# Merge season totals and weighted averages
final_2023_df = pd.merge(season_total_pitches, season_total_by_pitch_type, on=['pitcher', 'player_name', 'season'])
final_2023_df = pd.merge(final_2023_df, weighted_avg_df, on=['pitcher', 'player_name', 'season', 'pitch_type'])

final_2023_df.head()
"""

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,425794,"Wainwright, Adam",2023,9498,CH,91,91,81.504396,-1.330769,6.145385,4.245696,-118.558747,-4.409017,-11.711739,22.533321,-24.559338,53.993407
1,425794,"Wainwright, Adam",2023,9498,CS,3,3,65.733333,-1.520000,6.410000,-0.628298,-95.480064,4.033457,7.390874,17.302918,-40.738897,54.506667
2,425794,"Wainwright, Adam",2023,9498,CU,545,545,71.502569,-1.242385,6.286018,0.256395,-103.981304,0.991996,9.813901,20.820214,-40.697401,54.176661
3,425794,"Wainwright, Adam",2023,9498,FC,403,403,82.861290,-1.215806,6.287072,3.112750,-120.682959,-3.743577,3.994049,21.753104,-25.380865,54.015236
4,425794,"Wainwright, Adam",2023,9498,FF,176,176,85.715341,-1.229432,6.250625,2.547035,-124.786559,-4.628487,-2.092806,24.305957,-18.533098,53.974261

In [300]:
"""
final_2023_df['player_name'] = final_2023_df['player_name'].str.lower().str.strip().str.replace(r'\*$', '', regex=True)
final_2023_df.head()
"""

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg
0,425794,"wainwright, adam",2023,9498,CH,91,91,81.504396,-1.330769,6.145385,4.245696,-118.558747,-4.409017,-11.711739,22.533321,-24.559338,53.993407
1,425794,"wainwright, adam",2023,9498,CS,3,3,65.733333,-1.520000,6.410000,-0.628298,-95.480064,4.033457,7.390874,17.302918,-40.738897,54.506667
2,425794,"wainwright, adam",2023,9498,CU,545,545,71.502569,-1.242385,6.286018,0.256395,-103.981304,0.991996,9.813901,20.820214,-40.697401,54.176661
3,425794,"wainwright, adam",2023,9498,FC,403,403,82.861290,-1.215806,6.287072,3.112750,-120.682959,-3.743577,3.994049,21.753104,-25.380865,54.015236
4,425794,"wainwright, adam",2023,9498,FF,176,176,85.715341,-1.229432,6.250625,2.547035,-124.786559,-4.628487,-2.092806,24.305957,-18.533098,53.974261

In [301]:
"""
def remove_accents(input_str):
    nfkd_form = unicodedata.normalize('NFKD', input_str)
    return "".join([c for c in nfkd_form if not unicodedata.combining(c)])

def clean_name(name):
    name = name.lower()
    name = remove_accents(name)
    name = re.sub(r'[-.]', '', name)
    name = re.sub(r'\s+', ' ', name).strip()
    return name

final_2023_df['player_name'] = final_2023_df['player_name'].apply(clean_name)
"""

In [302]:
"""
# Convert 'player_name' from "last name, first name" to "first name last name"
final_2023_df['Name'] = final_2023_df['player_name'].apply(lambda x: ' '.join(x.split(', ')[::-1]))
"""

In [303]:
"""
# Now, you can perform the merge using 'Name' and 'season' as the keys for both DataFrames
better_2023_df = pd.merge(final_2023_df, 
                          cleaning_filtered_df[['Name', 'season', 'Age']],
                          on=['Name', 'season'],
                          how='left')
"""

In [304]:
#better_2023_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 877 entries, 0 to 876
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   pitcher                           877 non-null    int64
 1   player_name                       877 non-null    object
 2   season                            877 non-null    int32
 3   season_total_pitches              877 non-null    int64
 4   pitch_type                        877 non-null    object
 5   season_total_count_by_pitch_type  877 non-null    int64
 6   count_by_pitch_type               877 non-null    int64
 7   release_speed_weighted_avg        877 non-null    float64
 8   release_pos_x_weighted_avg        877 non-null    float64
 9   release_pos_z_weighted_avg        877 non-null    float64
 10  vx0_weighted_avg                  877 non-null    float64
 11  vy0_weighted_avg                  877 non-null    float64
 12  vz0_weighted_avg                  877 non-null    float64
 13  ax_weighted_avg                   877 non-null    float64
 14  ay_weighted_avg                   877 non-null    float64
 15  az_weighted_avg                   877 non-null    float64
 16  release_pos_y_weighted_avg        877 non-null    float64
 17  Name                              877 non-null    object
 18  Age                               815 non-null    float64
dtypes: float64(11), int32(1), int64(4), object(3)
memory usage: 126.9+ KB

In [305]:
#better_2023_df.head()

,pitcher,player_name,season,season_total_pitches,pitch_type,season_total_count_by_pitch_type,count_by_pitch_type,release_speed_weighted_avg,release_pos_x_weighted_avg,release_pos_z_weighted_avg,vx0_weighted_avg,vy0_weighted_avg,vz0_weighted_avg,ax_weighted_avg,ay_weighted_avg,az_weighted_avg,release_pos_y_weighted_avg,Name,Age
0,425794,"wainwright, adam",2023,9498,CH,91,91,81.504396,-1.330769,6.145385,4.245696,-118.558747,-4.409017,-11.711739,22.533321,-24.559338,53.993407,adam wainwright,41.0
1,425794,"wainwright, adam",2023,9498,CS,3,3,65.733333,-1.520000,6.410000,-0.628298,-95.480064,4.033457,7.390874,17.302918,-40.738897,54.506667,adam wainwright,41.0
2,425794,"wainwright, adam",2023,9498,CU,545,545,71.502569,-1.242385,6.286018,0.256395,-103.981304,0.991996,9.813901,20.820214,-40.697401,54.176661,adam wainwright,41.0
3,425794,"wainwright, adam",2023,9498,FC,403,403,82.861290,-1.215806,6.287072,3.112750,-120.682959,-3.743577,3.994049,21.753104,-25.380865,54.015236,adam wainwright,41.0
4,425794,"wainwright, adam",2023,9498,FF,176,176,85.715341,-1.229432,6.250625,2.547035,-124.786559,-4.628487,-2.092806,24.305957,-18.533098,53.974261,adam wainwright,41.0

In [306]:
#better_2023_df.to_csv('data/better_2023_df.csv')

END.